{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.Absence
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.Absence where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Absence

-- *** createAbsence

-- | @POST \/api\/v1\/absences@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createAbsence
  :: (Consumes CreateAbsence MimeJSON, MimeRender MimeJSON AbsenceCreate)
  => AbsenceCreate -- ^ "absenceCreate"
  -> SimpleBillyRequest CreateAbsence MimeJSON Absence MimeJSON
createAbsence absenceCreate =
  _mkRequest "POST" ["/api/v1/absences"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` absenceCreate

data CreateAbsence 
instance HasBodyParam CreateAbsence AbsenceCreate 

-- | @application/json@
instance Consumes CreateAbsence MimeJSON

-- | @application/json@
instance Produces CreateAbsence MimeJSON


-- *** deleteAbsence

-- | @DELETE \/api\/v1\/absences\/{id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteAbsence
  :: Id -- ^ "id"
  -> SimpleBillyRequest DeleteAbsence MimeNoContent NoContent MimeNoContent
deleteAbsence (Id id) =
  _mkRequest "DELETE" ["/api/v1/absences/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteAbsence  
instance Produces DeleteAbsence MimeNoContent


-- *** getAbsence

-- | @GET \/api\/v1\/absences\/{id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getAbsence
  :: Id -- ^ "id"
  -> SimpleBillyRequest GetAbsence MimeNoContent Absence MimeJSON
getAbsence (Id id) =
  _mkRequest "GET" ["/api/v1/absences/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetAbsence  
-- | @application/json@
instance Produces GetAbsence MimeJSON


-- *** getAbsences

-- | @GET \/api\/v1\/absences\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getAbsences
  :: SimpleBillyRequest GetAbsences MimeNoContent [Absence] MimeJSON
getAbsences =
  _mkRequest "GET" ["/api/v1/absences/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetAbsences  
instance HasOptionalParam GetAbsences Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam GetAbsences PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam GetAbsences Search where
  applyOptionalParam req (Search xs) =
    req `addQuery` toQuery ("search", Just xs)

-- | /Optional Param/ "include_deleted" - Soft-delete entities: set true to include rows with `deleted_at` set.
instance HasOptionalParam GetAbsences IncludeDeleted where
  applyOptionalParam req (IncludeDeleted xs) =
    req `addQuery` toQuery ("include_deleted", Just xs)
-- | @application/json@
instance Produces GetAbsences MimeJSON


-- *** updateAbsence

-- | @PUT \/api\/v1\/absences\/{id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateAbsence
  :: (Consumes UpdateAbsence MimeJSON, MimeRender MimeJSON AbsenceUpdate)
  => AbsenceUpdate -- ^ "absenceUpdate"
  -> Id -- ^ "id"
  -> SimpleBillyRequest UpdateAbsence MimeJSON Absence MimeJSON
updateAbsence absenceUpdate (Id id) =
  _mkRequest "PUT" ["/api/v1/absences/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` absenceUpdate

data UpdateAbsence 
instance HasBodyParam UpdateAbsence AbsenceUpdate 

-- | @application/json@
instance Consumes UpdateAbsence MimeJSON

-- | @application/json@
instance Produces UpdateAbsence MimeJSON

