{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.Activity
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.Activity where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Activity

-- *** createActivity

-- | @POST \/api\/v1\/activities@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createActivity
  :: (Consumes CreateActivity MimeJSON, MimeRender MimeJSON Activity)
  => Activity -- ^ "activity"
  -> SimpleBillyRequest CreateActivity MimeJSON Activity MimeJSON
createActivity activity =
  _mkRequest "POST" ["/api/v1/activities"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` activity

data CreateActivity 
instance HasBodyParam CreateActivity Activity 

-- | @application/json@
instance Consumes CreateActivity MimeJSON

-- | @application/json@
instance Produces CreateActivity MimeJSON


-- *** deleteActivity

-- | @DELETE \/api\/v1\/activities\/{activity_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteActivity
  :: ActivityId -- ^ "activityId"
  -> SimpleBillyRequest DeleteActivity MimeNoContent NoContent MimeNoContent
deleteActivity (ActivityId activityId) =
  _mkRequest "DELETE" ["/api/v1/activities/",toPath activityId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteActivity  
instance Produces DeleteActivity MimeNoContent


-- *** getActivity

-- | @GET \/api\/v1\/activities\/{activity_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getActivity
  :: ActivityId -- ^ "activityId"
  -> SimpleBillyRequest GetActivity MimeNoContent Activity MimeJSON
getActivity (ActivityId activityId) =
  _mkRequest "GET" ["/api/v1/activities/",toPath activityId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetActivity  
-- | @application/json@
instance Produces GetActivity MimeJSON


-- *** listActivities

-- | @GET \/api\/v1\/activities\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listActivities
  :: SimpleBillyRequest ListActivities MimeNoContent [Activity] MimeJSON
listActivities =
  _mkRequest "GET" ["/api/v1/activities/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListActivities  
instance HasOptionalParam ListActivities Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam ListActivities PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("pageSize", Just xs)
instance HasOptionalParam ListActivities ContactId where
  applyOptionalParam req (ContactId xs) =
    req `addQuery` toQuery ("contactId", Just xs)
instance HasOptionalParam ListActivities ActivityTypeText where
  applyOptionalParam req (ActivityTypeText xs) =
    req `addQuery` toQuery ("activityType", Just xs)
instance HasOptionalParam ListActivities Status where
  applyOptionalParam req (Status xs) =
    req `addQuery` toQuery ("status", Just xs)
instance HasOptionalParam ListActivities AssignedTo where
  applyOptionalParam req (AssignedTo xs) =
    req `addQuery` toQuery ("assignedTo", Just xs)

-- | /Optional Param/ "overdueOnly" - Only show overdue follow-ups.
instance HasOptionalParam ListActivities OverdueOnly where
  applyOptionalParam req (OverdueOnly xs) =
    req `addQuery` toQuery ("overdueOnly", Just xs)
-- | @application/json@
instance Produces ListActivities MimeJSON


-- *** updateActivity

-- | @PUT \/api\/v1\/activities\/{activity_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateActivity
  :: (Consumes UpdateActivity MimeJSON, MimeRender MimeJSON Body)
  => Body -- ^ "body"
  -> ActivityId -- ^ "activityId"
  -> SimpleBillyRequest UpdateActivity MimeJSON Activity MimeJSON
updateActivity body (ActivityId activityId) =
  _mkRequest "PUT" ["/api/v1/activities/",toPath activityId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` body

data UpdateActivity 
instance HasBodyParam UpdateActivity Body 

-- | @application/json@
instance Consumes UpdateActivity MimeJSON

-- | @application/json@
instance Produces UpdateActivity MimeJSON


-- *** updateActivityStatus

-- | @PUT \/api\/v1\/activities\/{activity_id}\/status@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateActivityStatus
  :: (Consumes UpdateActivityStatus MimeJSON, MimeRender MimeJSON ActivityStatusUpdate)
  => ActivityStatusUpdate -- ^ "activityStatusUpdate"
  -> ActivityId -- ^ "activityId"
  -> SimpleBillyRequest UpdateActivityStatus MimeJSON Activity MimeJSON
updateActivityStatus activityStatusUpdate (ActivityId activityId) =
  _mkRequest "PUT" ["/api/v1/activities/",toPath activityId,"/status"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` activityStatusUpdate

data UpdateActivityStatus 
instance HasBodyParam UpdateActivityStatus ActivityStatusUpdate 

-- | @application/json@
instance Consumes UpdateActivityStatus MimeJSON

-- | @application/json@
instance Produces UpdateActivityStatus MimeJSON

