{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.Ai
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.Ai where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Ai

-- *** aiSuggestApi

-- | @POST \/api\/v1\/support\/ai\/suggest@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
aiSuggestApi
  :: (Consumes AiSuggestApi MimeJSON, MimeRender MimeJSON AiSuggestionRequest)
  => AiSuggestionRequest -- ^ "aiSuggestionRequest"
  -> SimpleBillyRequest AiSuggestApi MimeJSON AiSuggestion MimeJSON
aiSuggestApi aiSuggestionRequest =
  _mkRequest "POST" ["/api/v1/support/ai/suggest"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` aiSuggestionRequest

data AiSuggestApi 
instance HasBodyParam AiSuggestApi AiSuggestionRequest 

-- | @application/json@
instance Consumes AiSuggestApi MimeJSON

-- | @application/json@
instance Produces AiSuggestApi MimeJSON


-- *** createWorkerApi

-- | @POST \/api\/v1\/support\/ai\/workers@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createWorkerApi
  :: (Consumes CreateWorkerApi MimeJSON, MimeRender MimeJSON AiConfigDto)
  => AiConfigDto -- ^ "aiConfigDto"
  -> SimpleBillyRequest CreateWorkerApi MimeJSON AiWorkerConfig MimeJSON
createWorkerApi aiConfigDto =
  _mkRequest "POST" ["/api/v1/support/ai/workers"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` aiConfigDto

data CreateWorkerApi 
instance HasBodyParam CreateWorkerApi AiConfigDto 

-- | @application/json@
instance Consumes CreateWorkerApi MimeJSON

-- | @application/json@
instance Produces CreateWorkerApi MimeJSON


-- *** listWorkersApi

-- | @GET \/api\/v1\/support\/ai\/workers@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listWorkersApi
  :: SimpleBillyRequest ListWorkersApi MimeNoContent [AiWorkerConfig] MimeJSON
listWorkersApi =
  _mkRequest "GET" ["/api/v1/support/ai/workers"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListWorkersApi  
-- | @application/json@
instance Produces ListWorkersApi MimeJSON


-- *** runWorkerApi

-- | @POST \/api\/v1\/support\/ai\/workers\/{worker_id}\/run@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
runWorkerApi
  :: (Consumes RunWorkerApi MimeJSON, MimeRender MimeJSON AiSuggestionRequest)
  => AiSuggestionRequest -- ^ "aiSuggestionRequest"
  -> WorkerId -- ^ "workerId"
  -> SimpleBillyRequest RunWorkerApi MimeJSON AiSuggestion MimeJSON
runWorkerApi aiSuggestionRequest (WorkerId workerId) =
  _mkRequest "POST" ["/api/v1/support/ai/workers/",toPath workerId,"/run"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` aiSuggestionRequest

data RunWorkerApi 
instance HasBodyParam RunWorkerApi AiSuggestionRequest 

-- | @application/json@
instance Consumes RunWorkerApi MimeJSON

-- | @application/json@
instance Produces RunWorkerApi MimeJSON

