{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.Auth
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.Auth where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Auth

-- *** acceptInvite

-- | @POST \/auth\/accept-invite@
-- 
-- Accept an invite: create the account (or reuse an existing one) and join the inviting tenant. The invite token proves control of the mailbox.
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
acceptInvite
  :: (Consumes AcceptInvite MimeJSON, MimeRender MimeJSON AcceptInviteRequest)
  => AcceptInviteRequest -- ^ "acceptInviteRequest"
  -> SimpleBillyRequest AcceptInvite MimeJSON NoContent MimeNoContent
acceptInvite acceptInviteRequest =
  _mkRequest "POST" ["/auth/accept-invite"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` acceptInviteRequest

data AcceptInvite 
instance HasBodyParam AcceptInvite AcceptInviteRequest 

-- | @application/json@
instance Consumes AcceptInvite MimeJSON

instance Produces AcceptInvite MimeNoContent


-- *** forgotPassword

-- | @POST \/auth\/forgot-password@
-- 
-- Send a password reset email to the user
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
forgotPassword
  :: (Consumes ForgotPassword MimeJSON, MimeRender MimeJSON ForgotPasswordRequest)
  => ForgotPasswordRequest -- ^ "forgotPasswordRequest"
  -> SimpleBillyRequest ForgotPassword MimeJSON NoContent MimeNoContent
forgotPassword forgotPasswordRequest =
  _mkRequest "POST" ["/auth/forgot-password"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` forgotPasswordRequest

data ForgotPassword 
instance HasBodyParam ForgotPassword ForgotPasswordRequest 

-- | @application/json@
instance Consumes ForgotPassword MimeJSON

instance Produces ForgotPassword MimeNoContent


-- *** login

-- | @POST \/auth\/login@
-- 
-- Authenticate a user with email + password (optional TOTP)
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
login
  :: (Consumes Login MimeJSON, MimeRender MimeJSON LoginRequest)
  => LoginRequest -- ^ "loginRequest"
  -> SimpleBillyRequest Login MimeJSON AuthResponse MimeJSON
login loginRequest =
  _mkRequest "POST" ["/auth/login"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` loginRequest

data Login 
instance HasBodyParam Login LoginRequest 

-- | @application/json@
instance Consumes Login MimeJSON

-- | @application/json@
instance Produces Login MimeJSON


-- *** logout

-- | @POST \/auth\/logout@
-- 
-- Log out the current user (kills the assay session)
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
logout
  :: SimpleBillyRequest Logout MimeNoContent NoContent MimeNoContent
logout =
  _mkRequest "POST" ["/auth/logout"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data Logout  
instance Produces Logout MimeNoContent


-- *** magicLinkLogin

-- | @POST \/auth\/magic-link@
-- 
-- Request a magic link login (sends an email with a one-time link)
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
magicLinkLogin
  :: (Consumes MagicLinkLogin MimeJSON, MimeRender MimeJSON MagicLinkRequest)
  => MagicLinkRequest -- ^ "magicLinkRequest"
  -> SimpleBillyRequest MagicLinkLogin MimeJSON NoContent MimeNoContent
magicLinkLogin magicLinkRequest =
  _mkRequest "POST" ["/auth/magic-link"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` magicLinkRequest

data MagicLinkLogin 
instance HasBodyParam MagicLinkLogin MagicLinkRequest 

-- | @application/json@
instance Consumes MagicLinkLogin MimeJSON

instance Produces MagicLinkLogin MimeNoContent


-- *** magicLinkVerify

-- | @POST \/auth\/magic-link\/verify@
-- 
-- Verify a magic link token and log the user in
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
magicLinkVerify
  :: (Consumes MagicLinkVerify MimeJSON, MimeRender MimeJSON MagicLinkVerifyRequest)
  => MagicLinkVerifyRequest -- ^ "magicLinkVerifyRequest"
  -> SimpleBillyRequest MagicLinkVerify MimeJSON AuthResponse MimeJSON
magicLinkVerify magicLinkVerifyRequest =
  _mkRequest "POST" ["/auth/magic-link/verify"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` magicLinkVerifyRequest

data MagicLinkVerify 
instance HasBodyParam MagicLinkVerify MagicLinkVerifyRequest 

-- | @application/json@
instance Consumes MagicLinkVerify MimeJSON

-- | @application/json@
instance Produces MagicLinkVerify MimeJSON


-- *** register

-- | @POST \/auth\/register@
-- 
-- Register a new user account
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
register
  :: (Consumes Register MimeJSON, MimeRender MimeJSON RegisterRequest)
  => RegisterRequest -- ^ "registerRequest"
  -> SimpleBillyRequest Register MimeJSON AuthResponse MimeJSON
register registerRequest =
  _mkRequest "POST" ["/auth/register"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` registerRequest

data Register 
instance HasBodyParam Register RegisterRequest 

-- | @application/json@
instance Consumes Register MimeJSON

-- | @application/json@
instance Produces Register MimeJSON


-- *** resetPassword

-- | @POST \/auth\/reset-password@
-- 
-- Reset the user's password using a reset token
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
resetPassword
  :: (Consumes ResetPassword MimeJSON, MimeRender MimeJSON ResetPasswordRequest)
  => ResetPasswordRequest -- ^ "resetPasswordRequest"
  -> SimpleBillyRequest ResetPassword MimeJSON NoContent MimeNoContent
resetPassword resetPasswordRequest =
  _mkRequest "POST" ["/auth/reset-password"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` resetPasswordRequest

data ResetPassword 
instance HasBodyParam ResetPassword ResetPasswordRequest 

-- | @application/json@
instance Consumes ResetPassword MimeJSON

instance Produces ResetPassword MimeNoContent


-- *** totpEnable

-- | @POST \/auth\/totp\/enable@
-- 
-- Enable TOTP two-factor authentication by verifying a code
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
totpEnable
  :: (Consumes TotpEnable MimeJSON, MimeRender MimeJSON TotpEnableRequest)
  => TotpEnableRequest -- ^ "totpEnableRequest"
  -> SimpleBillyRequest TotpEnable MimeJSON NoContent MimeNoContent
totpEnable totpEnableRequest =
  _mkRequest "POST" ["/auth/totp/enable"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` totpEnableRequest

data TotpEnable 
instance HasBodyParam TotpEnable TotpEnableRequest 

-- | @application/json@
instance Consumes TotpEnable MimeJSON

instance Produces TotpEnable MimeNoContent


-- *** totpSetup

-- | @GET \/auth\/totp\/setup@
-- 
-- Set up TOTP two-factor authentication (generates secret + backup codes)
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
totpSetup
  :: SimpleBillyRequest TotpSetup MimeNoContent TotpSetupResponse MimeJSON
totpSetup =
  _mkRequest "GET" ["/auth/totp/setup"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data TotpSetup  
-- | @application/json@
instance Produces TotpSetup MimeJSON


-- *** verifyEmail

-- | @POST \/auth\/verify-email@
-- 
-- Verify a user's email address using a verification token
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
verifyEmail
  :: (Consumes VerifyEmail MimeJSON, MimeRender MimeJSON VerifyEmailRequest)
  => VerifyEmailRequest -- ^ "verifyEmailRequest"
  -> SimpleBillyRequest VerifyEmail MimeJSON NoContent MimeNoContent
verifyEmail verifyEmailRequest =
  _mkRequest "POST" ["/auth/verify-email"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` verifyEmailRequest

data VerifyEmail 
instance HasBodyParam VerifyEmail VerifyEmailRequest 

-- | @application/json@
instance Consumes VerifyEmail MimeJSON

instance Produces VerifyEmail MimeNoContent

