{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.Billing
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.Billing where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Billing

-- *** getPlans

-- | @GET \/api\/v1\/plans@
-- 
-- All canonical plans (free/starter/business/enterprise) — the single source of truth lives in `crate::saasy::plans`, matching marketing.
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getPlans
  :: SimpleBillyRequest GetPlans MimeNoContent ApiResponseVecPlan MimeJSON
getPlans =
  _mkRequest "GET" ["/api/v1/plans"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetPlans  
-- | @application/json@
instance Produces GetPlans MimeJSON


-- *** getQuotaApi

-- | @GET \/api\/v1\/quota@
-- 
-- Effective limits + current usage for the calling tenant.
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getQuotaApi
  :: SimpleBillyRequest GetQuotaApi MimeNoContent NoContent MimeNoContent
getQuotaApi =
  _mkRequest "GET" ["/api/v1/quota"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetQuotaApi  
instance Produces GetQuotaApi MimeNoContent


-- *** getSubscriptionApi

-- | @GET \/api\/v1\/subscription@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getSubscriptionApi
  :: SimpleBillyRequest GetSubscriptionApi MimeNoContent ApiResponseSubscriptionOverview MimeJSON
getSubscriptionApi =
  _mkRequest "GET" ["/api/v1/subscription"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetSubscriptionApi  
-- | @application/json@
instance Produces GetSubscriptionApi MimeJSON


-- *** getUsageApi

-- | @GET \/api\/v1\/usage@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getUsageApi
  :: SimpleBillyRequest GetUsageApi MimeNoContent NoContent MimeNoContent
getUsageApi =
  _mkRequest "GET" ["/api/v1/usage"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetUsageApi  
instance HasOptionalParam GetUsageApi Meter where
  applyOptionalParam req (Meter xs) =
    req `addQuery` toQuery ("meter", Just xs)
instance Produces GetUsageApi MimeNoContent


-- *** paddleSubscriptionWebhook

-- | @POST \/api\/webhooks\/paddle\/subscription@
-- 
-- Paddle Billing subscription webhook. Verifies the `Paddle-Signature` header (HMAC-SHA256 over `\"{ts}:{raw_body}\"` with the webhook secret), then updates `billing_info` and `tenants.plan` for the tenant identified by the subscription `custom_data` (JSON `{\"tenant_id\": \"...\"}` or a bare tenant UUID).
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
paddleSubscriptionWebhook
  :: SimpleBillyRequest PaddleSubscriptionWebhook MimeNoContent NoContent MimeNoContent
paddleSubscriptionWebhook =
  _mkRequest "POST" ["/api/webhooks/paddle/subscription"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data PaddleSubscriptionWebhook  
instance Produces PaddleSubscriptionWebhook MimeNoContent


-- *** putQuotaApi

-- | @PUT \/api\/v1\/quota@
-- 
-- Write the per-tenant quota override (`admin:settings`). An empty object clears the override.
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
putQuotaApi
  :: (Consumes PutQuotaApi MimeJSON, MimeRender MimeJSON QuotaOverride)
  => QuotaOverride -- ^ "quotaOverride"
  -> SimpleBillyRequest PutQuotaApi MimeJSON NoContent MimeNoContent
putQuotaApi quotaOverride =
  _mkRequest "PUT" ["/api/v1/quota"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` quotaOverride

data PutQuotaApi 
instance HasBodyParam PutQuotaApi QuotaOverride 

-- | @application/json@
instance Consumes PutQuotaApi MimeJSON

instance Produces PutQuotaApi MimeNoContent

