{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.Bookkeeping
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.Bookkeeping where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Bookkeeping

-- *** allocatePaymentApi

-- | @POST \/api\/v1\/payments\/allocate@
-- 
-- Allocate a payment to an invoice
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
allocatePaymentApi
  :: (Consumes AllocatePaymentApi MimeJSON, MimeRender MimeJSON AllocatePaymentRequest)
  => AllocatePaymentRequest -- ^ "allocatePaymentRequest"
  -> SimpleBillyRequest AllocatePaymentApi MimeJSON NoContent MimeNoContent
allocatePaymentApi allocatePaymentRequest =
  _mkRequest "POST" ["/api/v1/payments/allocate"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` allocatePaymentRequest

data AllocatePaymentApi 
instance HasBodyParam AllocatePaymentApi AllocatePaymentRequest 

-- | @application/json@
instance Consumes AllocatePaymentApi MimeJSON

instance Produces AllocatePaymentApi MimeNoContent


-- *** bwaReportApi

-- | @GET \/api\/v1\/bookkeeping\/bwa@
-- 
-- Get BWA (Betriebswirtschaftliche Auswertung) report
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
bwaReportApi
  :: SimpleBillyRequest BwaReportApi MimeNoContent BWAReport MimeJSON
bwaReportApi =
  _mkRequest "GET" ["/api/v1/bookkeeping/bwa"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data BwaReportApi  
instance HasOptionalParam BwaReportApi Year where
  applyOptionalParam req (Year xs) =
    req `addQuery` toQuery ("year", Just xs)
instance HasOptionalParam BwaReportApi Month where
  applyOptionalParam req (Month xs) =
    req `addQuery` toQuery ("month", Just xs)
-- | @application/json@
instance Produces BwaReportApi MimeJSON


-- *** elsterStatusApi

-- | @GET \/api\/v1\/bookkeeping\/elster\/status@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
elsterStatusApi
  :: SimpleBillyRequest ElsterStatusApi MimeNoContent ElsterStatus MimeJSON
elsterStatusApi =
  _mkRequest "GET" ["/api/v1/bookkeeping/elster/status"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ElsterStatusApi  
-- | @application/json@
instance Produces ElsterStatusApi MimeJSON


-- *** elsterValidateApi

-- | @POST \/api\/v1\/bookkeeping\/ustva\/elster-validate@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
elsterValidateApi
  :: Zeitraum -- ^ "zeitraum"
  -> SimpleBillyRequest ElsterValidateApi MimeNoContent NoContent MimeNoContent
elsterValidateApi (Zeitraum zeitraum) =
  _mkRequest "POST" ["/api/v1/bookkeeping/ustva/elster-validate"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `addQuery` toQuery ("zeitraum", Just zeitraum)

data ElsterValidateApi  
instance Produces ElsterValidateApi MimeNoContent


-- *** elsterXmlApi

-- | @GET \/api\/v1\/bookkeeping\/ustva\/elster-xml@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
elsterXmlApi
  :: Zeitraum -- ^ "zeitraum"
  -> SimpleBillyRequest ElsterXmlApi MimeNoContent NoContent MimeNoContent
elsterXmlApi (Zeitraum zeitraum) =
  _mkRequest "GET" ["/api/v1/bookkeeping/ustva/elster-xml"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `addQuery` toQuery ("zeitraum", Just zeitraum)

data ElsterXmlApi  
instance Produces ElsterXmlApi MimeNoContent


-- *** getCashflow

-- | @GET \/api\/v1\/bookkeeping\/cashflow@
-- 
-- GET /api/v1/bookkeeping/cashflow Returns operating, investing, and financing cashflow for the given period.
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getCashflow
  :: SimpleBillyRequest GetCashflow MimeNoContent CashflowReport MimeJSON
getCashflow =
  _mkRequest "GET" ["/api/v1/bookkeeping/cashflow"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetCashflow  
instance HasOptionalParam GetCashflow Year where
  applyOptionalParam req (Year xs) =
    req `addQuery` toQuery ("year", Just xs)
instance HasOptionalParam GetCashflow Month where
  applyOptionalParam req (Month xs) =
    req `addQuery` toQuery ("month", Just xs)
-- | @application/json@
instance Produces GetCashflow MimeJSON


-- *** getLiquidity

-- | @GET \/api\/v1\/bookkeeping\/liquidity@
-- 
-- GET /api/v1/bookkeeping/liquidity Returns current liquidity position with ratios.
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getLiquidity
  :: SimpleBillyRequest GetLiquidity MimeNoContent LiquidityPosition MimeJSON
getLiquidity =
  _mkRequest "GET" ["/api/v1/bookkeeping/liquidity"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetLiquidity  
-- | @application/json@
instance Produces GetLiquidity MimeJSON


-- *** getOpenInvoicesApi

-- | @GET \/api\/v1\/payments\/open-invoices\/{customer_id}@
-- 
-- Get open invoices for a customer
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getOpenInvoicesApi
  :: CustomerId -- ^ "customerId"
  -> SimpleBillyRequest GetOpenInvoicesApi MimeNoContent [Invoice] MimeJSON
getOpenInvoicesApi (CustomerId customerId) =
  _mkRequest "GET" ["/api/v1/payments/open-invoices/",toPath customerId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetOpenInvoicesApi  
-- | @application/json@
instance Produces GetOpenInvoicesApi MimeJSON


-- *** getVerfahrensdokumentation

-- | @GET \/api\/v1\/bookkeeping\/verfahrensdokumentation@
-- 
-- GET /api/v1/bookkeeping/verfahrensdokumentation Returns the complete compliance catalog of all documented modules.
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getVerfahrensdokumentation
  :: SimpleBillyRequest GetVerfahrensdokumentation MimeNoContent Verfahrensdokumentation MimeJSON
getVerfahrensdokumentation =
  _mkRequest "GET" ["/api/v1/bookkeeping/verfahrensdokumentation"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetVerfahrensdokumentation  
-- | @application/json@
instance Produces GetVerfahrensdokumentation MimeJSON


-- *** runDunningApi

-- | @POST \/api\/v1\/bookkeeping\/dunning@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
runDunningApi
  :: SimpleBillyRequest RunDunningApi MimeNoContent DunningResult MimeJSON
runDunningApi =
  _mkRequest "POST" ["/api/v1/bookkeeping/dunning"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data RunDunningApi  
-- | @application/json@
instance Produces RunDunningApi MimeJSON

