{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.Budgets
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.Budgets where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Budgets

-- *** budgetsApi

-- | @GET \/api\/v1\/bookkeeping\/budgets@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
budgetsApi
  :: Year -- ^ "year"
  -> Month -- ^ "month"
  -> SimpleBillyRequest BudgetsApi MimeNoContent BudgetErgebnis MimeJSON
budgetsApi (Year year) (Month month) =
  _mkRequest "GET" ["/api/v1/bookkeeping/budgets"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `addQuery` toQuery ("year", Just year)
    `addQuery` toQuery ("month", Just month)

data BudgetsApi  
-- | @application/json@
instance Produces BudgetsApi MimeJSON


-- *** upsertBudgetGoalApi

-- | @PUT \/api\/v1\/bookkeeping\/budgets\/goals\/{category}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
upsertBudgetGoalApi
  :: (Consumes UpsertBudgetGoalApi MimeJSON, MimeRender MimeJSON BudgetGoalRequest)
  => BudgetGoalRequest -- ^ "budgetGoalRequest"
  -> Category -- ^ "category"
  -> SimpleBillyRequest UpsertBudgetGoalApi MimeJSON Budget MimeJSON
upsertBudgetGoalApi budgetGoalRequest (Category category) =
  _mkRequest "PUT" ["/api/v1/bookkeeping/budgets/goals/",toPath category]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` budgetGoalRequest

data UpsertBudgetGoalApi 
instance HasBodyParam UpsertBudgetGoalApi BudgetGoalRequest 

-- | @application/json@
instance Consumes UpsertBudgetGoalApi MimeJSON

-- | @application/json@
instance Produces UpsertBudgetGoalApi MimeJSON

