{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.ComplianceTraining
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.ComplianceTraining where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** ComplianceTraining

-- *** createComplianceTraining

-- | @POST \/api\/v1\/compliance-trainings@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createComplianceTraining
  :: (Consumes CreateComplianceTraining MimeJSON, MimeRender MimeJSON ComplianceTrainingCreate)
  => ComplianceTrainingCreate -- ^ "complianceTrainingCreate"
  -> SimpleBillyRequest CreateComplianceTraining MimeJSON ComplianceTraining MimeJSON
createComplianceTraining complianceTrainingCreate =
  _mkRequest "POST" ["/api/v1/compliance-trainings"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` complianceTrainingCreate

data CreateComplianceTraining 
instance HasBodyParam CreateComplianceTraining ComplianceTrainingCreate 

-- | @application/json@
instance Consumes CreateComplianceTraining MimeJSON

-- | @application/json@
instance Produces CreateComplianceTraining MimeJSON


-- *** deleteComplianceTraining

-- | @DELETE \/api\/v1\/compliance-trainings\/{id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteComplianceTraining
  :: Id -- ^ "id"
  -> SimpleBillyRequest DeleteComplianceTraining MimeNoContent NoContent MimeNoContent
deleteComplianceTraining (Id id) =
  _mkRequest "DELETE" ["/api/v1/compliance-trainings/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteComplianceTraining  
instance Produces DeleteComplianceTraining MimeNoContent


-- *** getComplianceTraining

-- | @GET \/api\/v1\/compliance-trainings\/{id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getComplianceTraining
  :: Id -- ^ "id"
  -> SimpleBillyRequest GetComplianceTraining MimeNoContent ComplianceTraining MimeJSON
getComplianceTraining (Id id) =
  _mkRequest "GET" ["/api/v1/compliance-trainings/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetComplianceTraining  
-- | @application/json@
instance Produces GetComplianceTraining MimeJSON


-- *** getComplianceTrainings

-- | @GET \/api\/v1\/compliance-trainings\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getComplianceTrainings
  :: SimpleBillyRequest GetComplianceTrainings MimeNoContent [ComplianceTraining] MimeJSON
getComplianceTrainings =
  _mkRequest "GET" ["/api/v1/compliance-trainings/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetComplianceTrainings  
instance HasOptionalParam GetComplianceTrainings Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam GetComplianceTrainings PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam GetComplianceTrainings Search where
  applyOptionalParam req (Search xs) =
    req `addQuery` toQuery ("search", Just xs)

-- | /Optional Param/ "include_deleted" - Soft-delete entities: set true to include rows with `deleted_at` set.
instance HasOptionalParam GetComplianceTrainings IncludeDeleted where
  applyOptionalParam req (IncludeDeleted xs) =
    req `addQuery` toQuery ("include_deleted", Just xs)
-- | @application/json@
instance Produces GetComplianceTrainings MimeJSON


-- *** updateComplianceTraining

-- | @PUT \/api\/v1\/compliance-trainings\/{id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateComplianceTraining
  :: (Consumes UpdateComplianceTraining MimeJSON, MimeRender MimeJSON ComplianceTrainingUpdate)
  => ComplianceTrainingUpdate -- ^ "complianceTrainingUpdate"
  -> Id -- ^ "id"
  -> SimpleBillyRequest UpdateComplianceTraining MimeJSON ComplianceTraining MimeJSON
updateComplianceTraining complianceTrainingUpdate (Id id) =
  _mkRequest "PUT" ["/api/v1/compliance-trainings/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` complianceTrainingUpdate

data UpdateComplianceTraining 
instance HasBodyParam UpdateComplianceTraining ComplianceTrainingUpdate 

-- | @application/json@
instance Consumes UpdateComplianceTraining MimeJSON

-- | @application/json@
instance Produces UpdateComplianceTraining MimeJSON

