{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.CreditNote
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.CreditNote where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** CreditNote

-- *** createCreditNote

-- | @POST \/api\/v1\/credit-notes@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createCreditNote
  :: (Consumes CreateCreditNote MimeJSON, MimeRender MimeJSON Body)
  => Body -- ^ "body"
  -> SimpleBillyRequest CreateCreditNote MimeJSON Invoice MimeJSON
createCreditNote body =
  _mkRequest "POST" ["/api/v1/credit-notes"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` body

data CreateCreditNote 
instance HasBodyParam CreateCreditNote Body 

-- | @application/json@
instance Consumes CreateCreditNote MimeJSON

-- | @application/json@
instance Produces CreateCreditNote MimeJSON


-- *** downloadCreditNotePdf

-- | @GET \/api\/v1\/credit-notes\/{credit_note_id}\/pdf@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
downloadCreditNotePdf
  :: CreditNoteId -- ^ "creditNoteId"
  -> SimpleBillyRequest DownloadCreditNotePdf MimeNoContent NoContent MimeNoContent
downloadCreditNotePdf (CreditNoteId creditNoteId) =
  _mkRequest "GET" ["/api/v1/credit-notes/",toPath creditNoteId,"/pdf"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DownloadCreditNotePdf  
instance Produces DownloadCreditNotePdf MimeNoContent


-- *** getCreditNote

-- | @GET \/api\/v1\/credit-notes\/{credit_note_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getCreditNote
  :: CreditNoteId -- ^ "creditNoteId"
  -> SimpleBillyRequest GetCreditNote MimeNoContent Invoice MimeJSON
getCreditNote (CreditNoteId creditNoteId) =
  _mkRequest "GET" ["/api/v1/credit-notes/",toPath creditNoteId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetCreditNote  
-- | @application/json@
instance Produces GetCreditNote MimeJSON


-- *** listCreditNotes

-- | @GET \/api\/v1\/credit-notes\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listCreditNotes
  :: SimpleBillyRequest ListCreditNotes MimeNoContent [Invoice] MimeJSON
listCreditNotes =
  _mkRequest "GET" ["/api/v1/credit-notes/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListCreditNotes  
instance HasOptionalParam ListCreditNotes Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam ListCreditNotes PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam ListCreditNotes Search where
  applyOptionalParam req (Search xs) =
    req `addQuery` toQuery ("search", Just xs)

-- | /Optional Param/ "include_deleted" - Soft-delete entities: set true to include rows with `deleted_at` set.
instance HasOptionalParam ListCreditNotes IncludeDeleted where
  applyOptionalParam req (IncludeDeleted xs) =
    req `addQuery` toQuery ("include_deleted", Just xs)
-- | @application/json@
instance Produces ListCreditNotes MimeJSON

