{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.Customer
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.Customer where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Customer

-- *** createCustomer

-- | @POST \/api\/v1\/customers@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createCustomer
  :: (Consumes CreateCustomer MimeJSON, MimeRender MimeJSON CustomerCreate)
  => CustomerCreate -- ^ "customerCreate"
  -> SimpleBillyRequest CreateCustomer MimeJSON Customer MimeJSON
createCustomer customerCreate =
  _mkRequest "POST" ["/api/v1/customers"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` customerCreate

data CreateCustomer 
instance HasBodyParam CreateCustomer CustomerCreate 

-- | @application/json@
instance Consumes CreateCustomer MimeJSON

-- | @application/json@
instance Produces CreateCustomer MimeJSON


-- *** customerRestore

-- | @POST \/api\/v1\/customers\/{customer_id}\/restore@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
customerRestore
  :: CustomerId -- ^ "customerId"
  -> SimpleBillyRequest CustomerRestore MimeNoContent Customer MimeJSON
customerRestore (CustomerId customerId) =
  _mkRequest "POST" ["/api/v1/customers/",toPath customerId,"/restore"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data CustomerRestore  
-- | @application/json@
instance Produces CustomerRestore MimeJSON


-- *** deleteCustomer

-- | @DELETE \/api\/v1\/customers\/{customer_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteCustomer
  :: CustomerId -- ^ "customerId"
  -> SimpleBillyRequest DeleteCustomer MimeNoContent NoContent MimeNoContent
deleteCustomer (CustomerId customerId) =
  _mkRequest "DELETE" ["/api/v1/customers/",toPath customerId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteCustomer  
instance Produces DeleteCustomer MimeNoContent


-- *** getCustomer

-- | @GET \/api\/v1\/customers\/{customer_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getCustomer
  :: CustomerId -- ^ "customerId"
  -> SimpleBillyRequest GetCustomer MimeNoContent Customer MimeJSON
getCustomer (CustomerId customerId) =
  _mkRequest "GET" ["/api/v1/customers/",toPath customerId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetCustomer  
-- | @application/json@
instance Produces GetCustomer MimeJSON


-- *** getCustomers

-- | @GET \/api\/v1\/customers\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getCustomers
  :: SimpleBillyRequest GetCustomers MimeNoContent [Customer] MimeJSON
getCustomers =
  _mkRequest "GET" ["/api/v1/customers/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetCustomers  
instance HasOptionalParam GetCustomers Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam GetCustomers PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam GetCustomers Search where
  applyOptionalParam req (Search xs) =
    req `addQuery` toQuery ("search", Just xs)

-- | /Optional Param/ "include_deleted" - Soft-delete entities: set true to include rows with `deleted_at` set.
instance HasOptionalParam GetCustomers IncludeDeleted where
  applyOptionalParam req (IncludeDeleted xs) =
    req `addQuery` toQuery ("include_deleted", Just xs)
-- | @application/json@
instance Produces GetCustomers MimeJSON


-- *** updateCustomer

-- | @PUT \/api\/v1\/customers\/{customer_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateCustomer
  :: (Consumes UpdateCustomer MimeJSON, MimeRender MimeJSON CustomerUpdate)
  => CustomerUpdate -- ^ "customerUpdate"
  -> CustomerId -- ^ "customerId"
  -> SimpleBillyRequest UpdateCustomer MimeJSON Customer MimeJSON
updateCustomer customerUpdate (CustomerId customerId) =
  _mkRequest "PUT" ["/api/v1/customers/",toPath customerId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` customerUpdate

data UpdateCustomer 
instance HasBodyParam UpdateCustomer CustomerUpdate 

-- | @application/json@
instance Consumes UpdateCustomer MimeJSON

-- | @application/json@
instance Produces UpdateCustomer MimeJSON

