{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.CustomerCommunication
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.CustomerCommunication where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** CustomerCommunication

-- *** createCommunication

-- | @POST \/api\/v1\/communications@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createCommunication
  :: (Consumes CreateCommunication MimeJSON, MimeRender MimeJSON CustomerCommunicationCreate)
  => CustomerCommunicationCreate -- ^ "customerCommunicationCreate"
  -> SimpleBillyRequest CreateCommunication MimeJSON CustomerCommunication MimeJSON
createCommunication customerCommunicationCreate =
  _mkRequest "POST" ["/api/v1/communications"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` customerCommunicationCreate

data CreateCommunication 
instance HasBodyParam CreateCommunication CustomerCommunicationCreate 

-- | @application/json@
instance Consumes CreateCommunication MimeJSON

-- | @application/json@
instance Produces CreateCommunication MimeJSON


-- *** customercommunicationRestore

-- | @POST \/api\/v1\/communications\/{communication_id}\/restore@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
customercommunicationRestore
  :: CommunicationId -- ^ "communicationId"
  -> SimpleBillyRequest CustomercommunicationRestore MimeNoContent CustomerCommunication MimeJSON
customercommunicationRestore (CommunicationId communicationId) =
  _mkRequest "POST" ["/api/v1/communications/",toPath communicationId,"/restore"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data CustomercommunicationRestore  
-- | @application/json@
instance Produces CustomercommunicationRestore MimeJSON


-- *** deleteCommunication

-- | @DELETE \/api\/v1\/communications\/{communication_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteCommunication
  :: CommunicationId -- ^ "communicationId"
  -> SimpleBillyRequest DeleteCommunication MimeNoContent NoContent MimeNoContent
deleteCommunication (CommunicationId communicationId) =
  _mkRequest "DELETE" ["/api/v1/communications/",toPath communicationId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteCommunication  
instance Produces DeleteCommunication MimeNoContent


-- *** getCommunication

-- | @GET \/api\/v1\/communications\/{communication_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getCommunication
  :: CommunicationId -- ^ "communicationId"
  -> SimpleBillyRequest GetCommunication MimeNoContent CustomerCommunication MimeJSON
getCommunication (CommunicationId communicationId) =
  _mkRequest "GET" ["/api/v1/communications/",toPath communicationId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetCommunication  
-- | @application/json@
instance Produces GetCommunication MimeJSON


-- *** getContactHistory

-- | @GET \/api\/v1\/contacts\/{contact_id}\/communications@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getContactHistory
  :: ContactId -- ^ "contactId"
  -> SimpleBillyRequest GetContactHistory MimeNoContent ContactHistoryResponse MimeJSON
getContactHistory (ContactId contactId) =
  _mkRequest "GET" ["/api/v1/contacts/",toPath contactId,"/communications"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetContactHistory  
-- | @application/json@
instance Produces GetContactHistory MimeJSON


-- *** listCommunications

-- | @GET \/api\/v1\/communications\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listCommunications
  :: SimpleBillyRequest ListCommunications MimeNoContent [CustomerCommunication] MimeJSON
listCommunications =
  _mkRequest "GET" ["/api/v1/communications/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListCommunications  
instance HasOptionalParam ListCommunications Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam ListCommunications PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)

-- | /Optional Param/ "contact_id" - Filter history to a single contact.
instance HasOptionalParam ListCommunications ContactId where
  applyOptionalParam req (ContactId xs) =
    req `addQuery` toQuery ("contact_id", Just xs)
instance HasOptionalParam ListCommunications Channel where
  applyOptionalParam req (Channel xs) =
    req `addQuery` toQuery ("channel", Just xs)
instance HasOptionalParam ListCommunications Direction where
  applyOptionalParam req (Direction xs) =
    req `addQuery` toQuery ("direction", Just xs)

-- | /Optional Param/ "from" - Only include communications after this ISO date (inclusive).
instance HasOptionalParam ListCommunications From where
  applyOptionalParam req (From xs) =
    req `addQuery` toQuery ("from", Just xs)

-- | /Optional Param/ "to" - Only include communications before this ISO date (inclusive).
instance HasOptionalParam ListCommunications To where
  applyOptionalParam req (To xs) =
    req `addQuery` toQuery ("to", Just xs)
-- | @application/json@
instance Produces ListCommunications MimeJSON


-- *** updateCommunication

-- | @PUT \/api\/v1\/communications\/{communication_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateCommunication
  :: (Consumes UpdateCommunication MimeJSON, MimeRender MimeJSON CustomerCommunicationUpdate)
  => CustomerCommunicationUpdate -- ^ "customerCommunicationUpdate"
  -> CommunicationId -- ^ "communicationId"
  -> SimpleBillyRequest UpdateCommunication MimeJSON CustomerCommunication MimeJSON
updateCommunication customerCommunicationUpdate (CommunicationId communicationId) =
  _mkRequest "PUT" ["/api/v1/communications/",toPath communicationId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` customerCommunicationUpdate

data UpdateCommunication 
instance HasBodyParam UpdateCommunication CustomerCommunicationUpdate 

-- | @application/json@
instance Consumes UpdateCommunication MimeJSON

-- | @application/json@
instance Produces UpdateCommunication MimeJSON

