{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.CustomerGroup
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.CustomerGroup where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** CustomerGroup

-- *** addGroupMembers

-- | @POST \/api\/v1\/customer-groups\/{customer_group_id}\/members@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
addGroupMembers
  :: (Consumes AddGroupMembers MimeJSON, MimeRender MimeJSON Body)
  => Body -- ^ "body"
  -> CustomerGroupId -- ^ "customerGroupId"
  -> SimpleBillyRequest AddGroupMembers MimeJSON CustomerGroup MimeJSON
addGroupMembers body (CustomerGroupId customerGroupId) =
  _mkRequest "POST" ["/api/v1/customer-groups/",toPath customerGroupId,"/members"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` body

data AddGroupMembers 
instance HasBodyParam AddGroupMembers Body 

-- | @application/json@
instance Consumes AddGroupMembers MimeJSON

-- | @application/json@
instance Produces AddGroupMembers MimeJSON


-- *** createCustomerGroup

-- | @POST \/api\/v1\/customer-groups@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createCustomerGroup
  :: (Consumes CreateCustomerGroup MimeJSON, MimeRender MimeJSON CustomerGroupCreate)
  => CustomerGroupCreate -- ^ "customerGroupCreate"
  -> SimpleBillyRequest CreateCustomerGroup MimeJSON CustomerGroup MimeJSON
createCustomerGroup customerGroupCreate =
  _mkRequest "POST" ["/api/v1/customer-groups"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` customerGroupCreate

data CreateCustomerGroup 
instance HasBodyParam CreateCustomerGroup CustomerGroupCreate 

-- | @application/json@
instance Consumes CreateCustomerGroup MimeJSON

-- | @application/json@
instance Produces CreateCustomerGroup MimeJSON


-- *** deleteCustomerGroup

-- | @DELETE \/api\/v1\/customer-groups\/{customer_group_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteCustomerGroup
  :: CustomerGroupId -- ^ "customerGroupId"
  -> SimpleBillyRequest DeleteCustomerGroup MimeNoContent NoContent MimeNoContent
deleteCustomerGroup (CustomerGroupId customerGroupId) =
  _mkRequest "DELETE" ["/api/v1/customer-groups/",toPath customerGroupId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteCustomerGroup  
instance Produces DeleteCustomerGroup MimeNoContent


-- *** getCustomerGroup

-- | @GET \/api\/v1\/customer-groups\/{customer_group_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getCustomerGroup
  :: CustomerGroupId -- ^ "customerGroupId"
  -> SimpleBillyRequest GetCustomerGroup MimeNoContent CustomerGroup MimeJSON
getCustomerGroup (CustomerGroupId customerGroupId) =
  _mkRequest "GET" ["/api/v1/customer-groups/",toPath customerGroupId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetCustomerGroup  
-- | @application/json@
instance Produces GetCustomerGroup MimeJSON


-- *** listCustomerGroups

-- | @GET \/api\/v1\/customer-groups\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listCustomerGroups
  :: SimpleBillyRequest ListCustomerGroups MimeNoContent [CustomerGroup] MimeJSON
listCustomerGroups =
  _mkRequest "GET" ["/api/v1/customer-groups/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListCustomerGroups  
instance HasOptionalParam ListCustomerGroups Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam ListCustomerGroups PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam ListCustomerGroups Search where
  applyOptionalParam req (Search xs) =
    req `addQuery` toQuery ("search", Just xs)

-- | /Optional Param/ "include_deleted" - Soft-delete entities: set true to include rows with `deleted_at` set.
instance HasOptionalParam ListCustomerGroups IncludeDeleted where
  applyOptionalParam req (IncludeDeleted xs) =
    req `addQuery` toQuery ("include_deleted", Just xs)
-- | @application/json@
instance Produces ListCustomerGroups MimeJSON


-- *** updateCustomerGroup

-- | @PUT \/api\/v1\/customer-groups\/{customer_group_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateCustomerGroup
  :: (Consumes UpdateCustomerGroup MimeJSON, MimeRender MimeJSON CustomerGroupUpdate)
  => CustomerGroupUpdate -- ^ "customerGroupUpdate"
  -> CustomerGroupId -- ^ "customerGroupId"
  -> SimpleBillyRequest UpdateCustomerGroup MimeJSON CustomerGroup MimeJSON
updateCustomerGroup customerGroupUpdate (CustomerGroupId customerGroupId) =
  _mkRequest "PUT" ["/api/v1/customer-groups/",toPath customerGroupId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` customerGroupUpdate

data UpdateCustomerGroup 
instance HasBodyParam UpdateCustomerGroup CustomerGroupUpdate 

-- | @application/json@
instance Consumes UpdateCustomerGroup MimeJSON

-- | @application/json@
instance Produces UpdateCustomerGroup MimeJSON

