{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.DeliveryAppointment
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.DeliveryAppointment where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** DeliveryAppointment

-- *** createDeliveryAppointment

-- | @POST \/api\/v1\/delivery-appointments@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createDeliveryAppointment
  :: (Consumes CreateDeliveryAppointment MimeJSON, MimeRender MimeJSON DeliveryAppointmentCreate)
  => DeliveryAppointmentCreate -- ^ "deliveryAppointmentCreate"
  -> SimpleBillyRequest CreateDeliveryAppointment MimeJSON DeliveryAppointment MimeJSON
createDeliveryAppointment deliveryAppointmentCreate =
  _mkRequest "POST" ["/api/v1/delivery-appointments"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` deliveryAppointmentCreate

data CreateDeliveryAppointment 
instance HasBodyParam CreateDeliveryAppointment DeliveryAppointmentCreate 

-- | @application/json@
instance Consumes CreateDeliveryAppointment MimeJSON

-- | @application/json@
instance Produces CreateDeliveryAppointment MimeJSON


-- *** deleteDeliveryAppointment

-- | @DELETE \/api\/v1\/delivery-appointments\/{appointment_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteDeliveryAppointment
  :: AppointmentId -- ^ "appointmentId"
  -> SimpleBillyRequest DeleteDeliveryAppointment MimeNoContent NoContent MimeNoContent
deleteDeliveryAppointment (AppointmentId appointmentId) =
  _mkRequest "DELETE" ["/api/v1/delivery-appointments/",toPath appointmentId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteDeliveryAppointment  
instance Produces DeleteDeliveryAppointment MimeNoContent


-- *** getDeliveryAppointment

-- | @GET \/api\/v1\/delivery-appointments\/{appointment_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getDeliveryAppointment
  :: AppointmentId -- ^ "appointmentId"
  -> SimpleBillyRequest GetDeliveryAppointment MimeNoContent DeliveryAppointment MimeJSON
getDeliveryAppointment (AppointmentId appointmentId) =
  _mkRequest "GET" ["/api/v1/delivery-appointments/",toPath appointmentId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetDeliveryAppointment  
-- | @application/json@
instance Produces GetDeliveryAppointment MimeJSON


-- *** getPublicDeliveryAppointmentStatus

-- | @GET \/api\/v1\/public\/delivery-appointments\/status@
-- 
-- Supplier/carrier checks appointment status (public, no auth). The appointment is only revealed when email AND token match.
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getPublicDeliveryAppointmentStatus
  :: AppointmentId -- ^ "appointmentId"
  -> Email -- ^ "email"
  -> Token -- ^ "token"
  -> SimpleBillyRequest GetPublicDeliveryAppointmentStatus MimeNoContent PublicDeliveryAppointmentStatusResponse MimeJSON
getPublicDeliveryAppointmentStatus (AppointmentId appointmentId) (Email email) (Token token) =
  _mkRequest "GET" ["/api/v1/public/delivery-appointments/status"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `addQuery` toQuery ("appointmentId", Just appointmentId)
    `addQuery` toQuery ("email", Just email)
    `addQuery` toQuery ("token", Just token)

data GetPublicDeliveryAppointmentStatus  
-- | @application/json@
instance Produces GetPublicDeliveryAppointmentStatus MimeJSON


-- *** listDeliveryAppointments

-- | @GET \/api\/v1\/delivery-appointments@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listDeliveryAppointments
  :: SimpleBillyRequest ListDeliveryAppointments MimeNoContent [DeliveryAppointment] MimeJSON
listDeliveryAppointments =
  _mkRequest "GET" ["/api/v1/delivery-appointments"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListDeliveryAppointments  
instance HasOptionalParam ListDeliveryAppointments Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam ListDeliveryAppointments PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam ListDeliveryAppointments Status where
  applyOptionalParam req (Status xs) =
    req `addQuery` toQuery ("status", Just xs)
instance HasOptionalParam ListDeliveryAppointments WarehouseId where
  applyOptionalParam req (WarehouseId xs) =
    req `addQuery` toQuery ("warehouse_id", Just xs)
instance HasOptionalParam ListDeliveryAppointments From where
  applyOptionalParam req (From xs) =
    req `addQuery` toQuery ("from", Just xs)
instance HasOptionalParam ListDeliveryAppointments To where
  applyOptionalParam req (To xs) =
    req `addQuery` toQuery ("to", Just xs)
-- | @application/json@
instance Produces ListDeliveryAppointments MimeJSON


-- *** requestPublicDeliveryAppointment

-- | @POST \/api\/v1\/public\/delivery-appointments\/request@
-- 
-- Supplier/carrier requests an inbound delivery slot (public, no auth). The tenant is derived from the warehouse found by `code` — never from the request.
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
requestPublicDeliveryAppointment
  :: (Consumes RequestPublicDeliveryAppointment MimeJSON, MimeRender MimeJSON PublicDeliveryAppointmentRequest)
  => PublicDeliveryAppointmentRequest -- ^ "publicDeliveryAppointmentRequest"
  -> SimpleBillyRequest RequestPublicDeliveryAppointment MimeJSON PublicDeliveryAppointmentResponse MimeJSON
requestPublicDeliveryAppointment publicDeliveryAppointmentRequest =
  _mkRequest "POST" ["/api/v1/public/delivery-appointments/request"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` publicDeliveryAppointmentRequest

data RequestPublicDeliveryAppointment 
instance HasBodyParam RequestPublicDeliveryAppointment PublicDeliveryAppointmentRequest 

-- | @application/json@
instance Consumes RequestPublicDeliveryAppointment MimeJSON

-- | @application/json@
instance Produces RequestPublicDeliveryAppointment MimeJSON


-- *** updateDeliveryAppointment

-- | @PUT \/api\/v1\/delivery-appointments\/{appointment_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateDeliveryAppointment
  :: (Consumes UpdateDeliveryAppointment MimeJSON, MimeRender MimeJSON Body)
  => Body -- ^ "body"
  -> AppointmentId -- ^ "appointmentId"
  -> SimpleBillyRequest UpdateDeliveryAppointment MimeJSON DeliveryAppointment MimeJSON
updateDeliveryAppointment body (AppointmentId appointmentId) =
  _mkRequest "PUT" ["/api/v1/delivery-appointments/",toPath appointmentId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` body

data UpdateDeliveryAppointment 
instance HasBodyParam UpdateDeliveryAppointment Body 

-- | @application/json@
instance Consumes UpdateDeliveryAppointment MimeJSON

-- | @application/json@
instance Produces UpdateDeliveryAppointment MimeJSON


-- *** updateDeliveryAppointmentStatus

-- | @PUT \/api\/v1\/delivery-appointments\/{appointment_id}\/status@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateDeliveryAppointmentStatus
  :: (Consumes UpdateDeliveryAppointmentStatus MimeJSON, MimeRender MimeJSON AppointmentStatusUpdate)
  => AppointmentStatusUpdate -- ^ "appointmentStatusUpdate"
  -> AppointmentId -- ^ "appointmentId"
  -> SimpleBillyRequest UpdateDeliveryAppointmentStatus MimeJSON DeliveryAppointment MimeJSON
updateDeliveryAppointmentStatus appointmentStatusUpdate (AppointmentId appointmentId) =
  _mkRequest "PUT" ["/api/v1/delivery-appointments/",toPath appointmentId,"/status"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` appointmentStatusUpdate

data UpdateDeliveryAppointmentStatus 
instance HasBodyParam UpdateDeliveryAppointmentStatus AppointmentStatusUpdate 

-- | @application/json@
instance Consumes UpdateDeliveryAppointmentStatus MimeJSON

-- | @application/json@
instance Produces UpdateDeliveryAppointmentStatus MimeJSON

