{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.EmailTemplate
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.EmailTemplate where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** EmailTemplate

-- *** createEmailTemplate

-- | @POST \/api\/v1\/email-templates@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createEmailTemplate
  :: (Consumes CreateEmailTemplate MimeJSON, MimeRender MimeJSON EmailTemplateCreate)
  => EmailTemplateCreate -- ^ "emailTemplateCreate"
  -> SimpleBillyRequest CreateEmailTemplate MimeJSON EmailTemplate MimeJSON
createEmailTemplate emailTemplateCreate =
  _mkRequest "POST" ["/api/v1/email-templates"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` emailTemplateCreate

data CreateEmailTemplate 
instance HasBodyParam CreateEmailTemplate EmailTemplateCreate 

-- | @application/json@
instance Consumes CreateEmailTemplate MimeJSON

-- | @application/json@
instance Produces CreateEmailTemplate MimeJSON


-- *** deleteEmailTemplate

-- | @DELETE \/api\/v1\/email-templates\/{email_template_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteEmailTemplate
  :: EmailTemplateId -- ^ "emailTemplateId"
  -> SimpleBillyRequest DeleteEmailTemplate MimeNoContent NoContent MimeNoContent
deleteEmailTemplate (EmailTemplateId emailTemplateId) =
  _mkRequest "DELETE" ["/api/v1/email-templates/",toPath emailTemplateId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteEmailTemplate  
instance Produces DeleteEmailTemplate MimeNoContent


-- *** getEmailTemplate

-- | @GET \/api\/v1\/email-templates\/{email_template_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getEmailTemplate
  :: EmailTemplateId -- ^ "emailTemplateId"
  -> SimpleBillyRequest GetEmailTemplate MimeNoContent EmailTemplate MimeJSON
getEmailTemplate (EmailTemplateId emailTemplateId) =
  _mkRequest "GET" ["/api/v1/email-templates/",toPath emailTemplateId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetEmailTemplate  
-- | @application/json@
instance Produces GetEmailTemplate MimeJSON


-- *** listEmailTemplates

-- | @GET \/api\/v1\/email-templates\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listEmailTemplates
  :: SimpleBillyRequest ListEmailTemplates MimeNoContent [EmailTemplate] MimeJSON
listEmailTemplates =
  _mkRequest "GET" ["/api/v1/email-templates/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListEmailTemplates  
instance HasOptionalParam ListEmailTemplates Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam ListEmailTemplates PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("pageSize", Just xs)
instance HasOptionalParam ListEmailTemplates Status where
  applyOptionalParam req (Status xs) =
    req `addQuery` toQuery ("status", Just xs)
instance HasOptionalParam ListEmailTemplates Search where
  applyOptionalParam req (Search xs) =
    req `addQuery` toQuery ("search", Just xs)
-- | @application/json@
instance Produces ListEmailTemplates MimeJSON


-- *** renderEmailTemplate

-- | @POST \/api\/v1\/email-templates\/{email_template_id}\/render@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
renderEmailTemplate
  :: (Consumes RenderEmailTemplate MimeJSON, MimeRender MimeJSON Body)
  => Body -- ^ "body"
  -> EmailTemplateId -- ^ "emailTemplateId"
  -> SimpleBillyRequest RenderEmailTemplate MimeJSON AnyType MimeJSON
renderEmailTemplate body (EmailTemplateId emailTemplateId) =
  _mkRequest "POST" ["/api/v1/email-templates/",toPath emailTemplateId,"/render"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` body

data RenderEmailTemplate 
instance HasBodyParam RenderEmailTemplate Body 

-- | @application/json@
instance Consumes RenderEmailTemplate MimeJSON

-- | @application/json@
instance Produces RenderEmailTemplate MimeJSON


-- *** updateEmailTemplate

-- | @PUT \/api\/v1\/email-templates\/{email_template_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateEmailTemplate
  :: (Consumes UpdateEmailTemplate MimeJSON, MimeRender MimeJSON EmailTemplateUpdate)
  => EmailTemplateUpdate -- ^ "emailTemplateUpdate"
  -> EmailTemplateId -- ^ "emailTemplateId"
  -> SimpleBillyRequest UpdateEmailTemplate MimeJSON EmailTemplate MimeJSON
updateEmailTemplate emailTemplateUpdate (EmailTemplateId emailTemplateId) =
  _mkRequest "PUT" ["/api/v1/email-templates/",toPath emailTemplateId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` emailTemplateUpdate

data UpdateEmailTemplate 
instance HasBodyParam UpdateEmailTemplate EmailTemplateUpdate 

-- | @application/json@
instance Consumes UpdateEmailTemplate MimeJSON

-- | @application/json@
instance Produces UpdateEmailTemplate MimeJSON

