{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.Emissions
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.Emissions where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Emissions

-- *** createEmissionEntryApi

-- | @POST \/api\/v1\/bookkeeping\/emissions\/entries@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createEmissionEntryApi
  :: (Consumes CreateEmissionEntryApi MimeJSON, MimeRender MimeJSON CreateEmissionEntry)
  => CreateEmissionEntry -- ^ "createEmissionEntry"
  -> SimpleBillyRequest CreateEmissionEntryApi MimeJSON EmissionEntry MimeJSON
createEmissionEntryApi createEmissionEntry =
  _mkRequest "POST" ["/api/v1/bookkeeping/emissions/entries"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` createEmissionEntry

data CreateEmissionEntryApi 
instance HasBodyParam CreateEmissionEntryApi CreateEmissionEntry 

-- | @application/json@
instance Consumes CreateEmissionEntryApi MimeJSON

-- | @application/json@
instance Produces CreateEmissionEntryApi MimeJSON


-- *** createEmissionTargetApi

-- | @POST \/api\/v1\/bookkeeping\/emissions\/targets@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createEmissionTargetApi
  :: (Consumes CreateEmissionTargetApi MimeJSON, MimeRender MimeJSON CreateEmissionTarget)
  => CreateEmissionTarget -- ^ "createEmissionTarget"
  -> SimpleBillyRequest CreateEmissionTargetApi MimeJSON EmissionTarget MimeJSON
createEmissionTargetApi createEmissionTarget =
  _mkRequest "POST" ["/api/v1/bookkeeping/emissions/targets"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` createEmissionTarget

data CreateEmissionTargetApi 
instance HasBodyParam CreateEmissionTargetApi CreateEmissionTarget 

-- | @application/json@
instance Consumes CreateEmissionTargetApi MimeJSON

-- | @application/json@
instance Produces CreateEmissionTargetApi MimeJSON


-- *** deleteEmissionEntryApi

-- | @DELETE \/api\/v1\/bookkeeping\/emissions\/entries\/{id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteEmissionEntryApi
  :: Id -- ^ "id"
  -> SimpleBillyRequest DeleteEmissionEntryApi MimeNoContent NoContent MimeNoContent
deleteEmissionEntryApi (Id id) =
  _mkRequest "DELETE" ["/api/v1/bookkeeping/emissions/entries/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteEmissionEntryApi  
instance Produces DeleteEmissionEntryApi MimeNoContent


-- *** deleteEmissionTargetApi

-- | @DELETE \/api\/v1\/bookkeeping\/emissions\/targets\/{id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteEmissionTargetApi
  :: Id -- ^ "id"
  -> SimpleBillyRequest DeleteEmissionTargetApi MimeNoContent NoContent MimeNoContent
deleteEmissionTargetApi (Id id) =
  _mkRequest "DELETE" ["/api/v1/bookkeeping/emissions/targets/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteEmissionTargetApi  
instance Produces DeleteEmissionTargetApi MimeNoContent


-- *** emissionsEntriesApi

-- | @GET \/api\/v1\/bookkeeping\/emissions\/entries@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
emissionsEntriesApi
  :: Year -- ^ "year"
  -> SimpleBillyRequest EmissionsEntriesApi MimeNoContent [EmissionEntry] MimeJSON
emissionsEntriesApi (Year year) =
  _mkRequest "GET" ["/api/v1/bookkeeping/emissions/entries"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `addQuery` toQuery ("year", Just year)

data EmissionsEntriesApi  
-- | @application/json@
instance Produces EmissionsEntriesApi MimeJSON


-- *** emissionsExportApi

-- | @GET \/api\/v1\/bookkeeping\/emissions\/export@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
emissionsExportApi
  :: Year -- ^ "year"
  -> SimpleBillyRequest EmissionsExportApi MimeNoContent EmissionsExportResponse MimeJSON
emissionsExportApi (Year year) =
  _mkRequest "GET" ["/api/v1/bookkeeping/emissions/export"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `addQuery` toQuery ("year", Just year)

data EmissionsExportApi  
-- | @application/json@
instance Produces EmissionsExportApi MimeJSON


-- *** emissionsFactorsApi

-- | @GET \/api\/v1\/bookkeeping\/emissions\/factors@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
emissionsFactorsApi
  :: SimpleBillyRequest EmissionsFactorsApi MimeNoContent [EmissionFactorResponse] MimeJSON
emissionsFactorsApi =
  _mkRequest "GET" ["/api/v1/bookkeeping/emissions/factors"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data EmissionsFactorsApi  
-- | @application/json@
instance Produces EmissionsFactorsApi MimeJSON


-- *** emissionsReportApi

-- | @GET \/api\/v1\/bookkeeping\/emissions\/report@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
emissionsReportApi
  :: Year -- ^ "year"
  -> SimpleBillyRequest EmissionsReportApi MimeNoContent EmissionsReport MimeJSON
emissionsReportApi (Year year) =
  _mkRequest "GET" ["/api/v1/bookkeeping/emissions/report"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `addQuery` toQuery ("year", Just year)

data EmissionsReportApi  
-- | @application/json@
instance Produces EmissionsReportApi MimeJSON


-- *** emissionsTargetsApi

-- | @GET \/api\/v1\/bookkeeping\/emissions\/targets@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
emissionsTargetsApi
  :: SimpleBillyRequest EmissionsTargetsApi MimeNoContent [EmissionTarget] MimeJSON
emissionsTargetsApi =
  _mkRequest "GET" ["/api/v1/bookkeeping/emissions/targets"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data EmissionsTargetsApi  
-- | @application/json@
instance Produces EmissionsTargetsApi MimeJSON

