{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.Gdpr
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.Gdpr where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Gdpr

-- *** acceptDpa

-- | @PUT \/api\/v1\/gdpr\/dpa@
-- 
-- Record DPA acceptance: sets dpa_accepted_at/by/version on the tenant settings row (created with company-type defaults if missing).
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
acceptDpa
  :: (Consumes AcceptDpa MimeJSON, MimeRender MimeJSON DpaAcceptRequest)
  => DpaAcceptRequest -- ^ "dpaAcceptRequest"
  -> SimpleBillyRequest AcceptDpa MimeJSON DpaStatus MimeJSON
acceptDpa dpaAcceptRequest =
  _mkRequest "PUT" ["/api/v1/gdpr/dpa"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` dpaAcceptRequest

data AcceptDpa 
instance HasBodyParam AcceptDpa DpaAcceptRequest 

-- | @application/json@
instance Consumes AcceptDpa MimeJSON

-- | @application/json@
instance Produces AcceptDpa MimeJSON


-- *** accountErasure

-- | @POST \/api\/v1\/gdpr\/account-erasure@
-- 
-- Erase ALL personal data of the tenant (TOS §11: deletion 90 days after termination).
-- 
-- Anonymizes every contact, anonymizes personal fields on bookkeeping records (orders/invoices/payments keep amounts and dates for GoBD), removes the tenant linkage of the (global, saasy-framework) users and marks the erasure on `tenant_settings.gdpr_erased_at`. No row is physically deleted. The audit triggers on the touched tables record who/when.
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
accountErasure
  :: SimpleBillyRequest AccountErasure MimeNoContent AnyType MimeJSON
accountErasure =
  _mkRequest "POST" ["/api/v1/gdpr/account-erasure"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data AccountErasure  
-- | @application/json@
instance Produces AccountErasure MimeJSON


-- *** erasureContact

-- | @POST \/api\/v1\/gdpr\/erasure\/{contact_id}@
-- 
-- Anonymize + soft-delete a contact: personal attributes are cleared, the record itself is kept for GoBD retention (Art. 17(3)(e) DSGVO). The audit trigger on `contacts` already records who/when.
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
erasureContact
  :: ContactId -- ^ "contactId"
  -> SimpleBillyRequest ErasureContact MimeNoContent AnyType MimeJSON
erasureContact (ContactId contactId) =
  _mkRequest "POST" ["/api/v1/gdpr/erasure/",toPath contactId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ErasureContact  
-- | @application/json@
instance Produces ErasureContact MimeJSON


-- *** exportContactData

-- | @GET \/api\/v1\/gdpr\/export\/{contact_id}@
-- 
-- Art. 15 data-subject access export for a contact.
-- 
-- Returns the contact itself plus the tenant-scoped rows linked to it.  ## Relations The `customers`/`orders`/`invoices`/`payments` tables have no FK to `contacts`; they are linked through the `customer_id` column, which per the app's conventions holds one of: - the admin customer's `customer_id` (a UUID, often the same value as   the contact's `contact_id`/`customer_number`), - the buyer's email for shop orders, or - the marketplace's external customer id for plugin orders.  The export therefore matches the contact's identifiers (`contact_id`, `customer_number`, `external_id`, `email`) plus any resolved customer ids against `customer_id`. `delivery_notes` and `customer_communications` reference contacts directly via `contact_id`. Soft-deleted rows are included (their data is still processed and retained for GoBD). Relations that genuinely do not exist for a contact stay empty but the key is always present.
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
exportContactData
  :: ContactId -- ^ "contactId"
  -> SimpleBillyRequest ExportContactData MimeNoContent AnyType MimeJSON
exportContactData (ContactId contactId) =
  _mkRequest "GET" ["/api/v1/gdpr/export/",toPath contactId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ExportContactData  
-- | @application/json@
instance Produces ExportContactData MimeJSON


-- *** exportGdpr

-- | @GET \/api\/v1\/gdpr\/export@
-- 
-- Export the current user's personal data (GDPR Art. 15/20).
-- 
-- No admin permission required: a user always exports their own data.
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
exportGdpr
  :: SimpleBillyRequest ExportGdpr MimeNoContent ApiResponseGdprExport MimeJSON
exportGdpr =
  _mkRequest "GET" ["/api/v1/gdpr/export"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ExportGdpr  
-- | @application/json@
instance Produces ExportGdpr MimeJSON


-- *** getDpa

-- | @GET \/api\/v1\/gdpr\/dpa@
-- 
-- Current DPA acceptance status (from tenant_settings).
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getDpa
  :: SimpleBillyRequest GetDpa MimeNoContent DpaStatus MimeJSON
getDpa =
  _mkRequest "GET" ["/api/v1/gdpr/dpa"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetDpa  
-- | @application/json@
instance Produces GetDpa MimeJSON

