{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.GenerateQrcode
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.GenerateQrcode where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** GenerateQrcode

-- *** generateQrcodeApi

-- | @GET \/api\/v1\/invoices\/{id}\/qrcode@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
generateQrcodeApi
  :: Iban -- ^ "iban"
  -> Id -- ^ "id"
  -> SimpleBillyRequest GenerateQrcodeApi MimeNoContent QRCodeResponse MimeJSON
generateQrcodeApi (Iban iban) (Id id) =
  _mkRequest "GET" ["/api/v1/invoices/",toPath id,"/qrcode"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `addQuery` toQuery ("iban", Just iban)

data GenerateQrcodeApi  
instance HasOptionalParam GenerateQrcodeApi HolderName where
  applyOptionalParam req (HolderName xs) =
    req `addQuery` toQuery ("holder_name", Just xs)
instance HasOptionalParam GenerateQrcodeApi Bic where
  applyOptionalParam req (Bic xs) =
    req `addQuery` toQuery ("bic", Just xs)
instance HasOptionalParam GenerateQrcodeApi Amount where
  applyOptionalParam req (Amount xs) =
    req `addQuery` toQuery ("amount", Just xs)
instance HasOptionalParam GenerateQrcodeApi Reference where
  applyOptionalParam req (Reference xs) =
    req `addQuery` toQuery ("reference", Just xs)
instance HasOptionalParam GenerateQrcodeApi Purpose where
  applyOptionalParam req (Purpose xs) =
    req `addQuery` toQuery ("purpose", Just xs)
-- | @application/json@
instance Produces GenerateQrcodeApi MimeJSON

