{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.Gewerbesteuer
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.Gewerbesteuer where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Gewerbesteuer

-- *** gewerbesteuerApi

-- | @GET \/api\/v1\/bookkeeping\/gewerbesteuer@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
gewerbesteuerApi
  :: Year -- ^ "year"
  -> SimpleBillyRequest GewerbesteuerApi MimeNoContent GewerbesteuerErgebnis MimeJSON
gewerbesteuerApi (Year year) =
  _mkRequest "GET" ["/api/v1/bookkeeping/gewerbesteuer"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `addQuery` toQuery ("year", Just year)

data GewerbesteuerApi  
instance HasOptionalParam GewerbesteuerApi Hebesatz where
  applyOptionalParam req (Hebesatz xs) =
    req `addQuery` toQuery ("hebesatz", Just xs)
instance HasOptionalParam GewerbesteuerApi Gewerbeertrag where
  applyOptionalParam req (Gewerbeertrag xs) =
    req `addQuery` toQuery ("gewerbeertrag", Just xs)
instance HasOptionalParam GewerbesteuerApi Country where
  applyOptionalParam req (Country xs) =
    req `addQuery` toQuery ("country", Just xs)
instance HasOptionalParam GewerbesteuerApi Gemeindeschluessel where
  applyOptionalParam req (Gemeindeschluessel xs) =
    req `addQuery` toQuery ("gemeindeschluessel", Just xs)
-- | @application/json@
instance Produces GewerbesteuerApi MimeJSON

