{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.Gez
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.Gez where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Gez

-- *** gezApi

-- | @GET \/api\/v1\/bookkeeping\/gez@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
gezApi
  :: SimpleBillyRequest GezApi MimeNoContent GezReport MimeJSON
gezApi =
  _mkRequest "GET" ["/api/v1/bookkeeping/gez"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GezApi  
instance HasOptionalParam GezApi Jahr where
  applyOptionalParam req (Jahr xs) =
    req `addQuery` toQuery ("jahr", Just xs)

-- | /Optional Param/ "betriebsstaetten" - Liste der Betriebsstätten als JSON, z.B. `[{\"name\":\"Filiale 1\",\"beschaefigte\":12}]`.
instance HasOptionalParam GezApi Betriebsstaetten where
  applyOptionalParam req (Betriebsstaetten xs) =
    req `addQuery` toQuery ("betriebsstaetten", Just xs)

-- | /Optional Param/ "kfz" - Gesamtzahl der betrieblich genutzten Kfz (falls keine Betriebsstätten angegeben sind).
instance HasOptionalParam GezApi Kfz where
  applyOptionalParam req (Kfz xs) =
    req `addQuery` toQuery ("kfz", Just xs)

-- | /Optional Param/ "hotelzimmer" - Gesamtzahl der Hotel-/Gästezimmer und Ferienwohnungen.
instance HasOptionalParam GezApi Hotelzimmer where
  applyOptionalParam req (Hotelzimmer xs) =
    req `addQuery` toQuery ("hotelzimmer", Just xs)

-- | /Optional Param/ "beschaefigte" - Gesamtzahl der Beschäftigten (verwendet nur, wenn `betriebsstaetten` fehlt; dann wird eine einzelne Betriebsstätte angenommen).
instance HasOptionalParam GezApi Beschaefigte where
  applyOptionalParam req (Beschaefigte xs) =
    req `addQuery` toQuery ("beschaefigte", Just xs)
-- | @application/json@
instance Produces GezApi MimeJSON

