{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.GoodsReceipt
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.GoodsReceipt where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** GoodsReceipt

-- *** createGoodsReceipt

-- | @POST \/api\/v1\/goods-receipts@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createGoodsReceipt
  :: (Consumes CreateGoodsReceipt MimeJSON, MimeRender MimeJSON GoodsReceipt)
  => GoodsReceipt -- ^ "goodsReceipt"
  -> SimpleBillyRequest CreateGoodsReceipt MimeJSON GoodsReceipt MimeJSON
createGoodsReceipt goodsReceipt =
  _mkRequest "POST" ["/api/v1/goods-receipts"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` goodsReceipt

data CreateGoodsReceipt 
instance HasBodyParam CreateGoodsReceipt GoodsReceipt 

-- | @application/json@
instance Consumes CreateGoodsReceipt MimeJSON

-- | @application/json@
instance Produces CreateGoodsReceipt MimeJSON


-- *** deleteGoodsReceipt

-- | @DELETE \/api\/v1\/goods-receipts\/{goods_receipt_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteGoodsReceipt
  :: GoodsReceiptId -- ^ "goodsReceiptId"
  -> SimpleBillyRequest DeleteGoodsReceipt MimeNoContent NoContent MimeNoContent
deleteGoodsReceipt (GoodsReceiptId goodsReceiptId) =
  _mkRequest "DELETE" ["/api/v1/goods-receipts/",toPath goodsReceiptId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteGoodsReceipt  
instance Produces DeleteGoodsReceipt MimeNoContent


-- *** getGoodsReceipt

-- | @GET \/api\/v1\/goods-receipts\/{goods_receipt_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getGoodsReceipt
  :: GoodsReceiptId -- ^ "goodsReceiptId"
  -> SimpleBillyRequest GetGoodsReceipt MimeNoContent GoodsReceipt MimeJSON
getGoodsReceipt (GoodsReceiptId goodsReceiptId) =
  _mkRequest "GET" ["/api/v1/goods-receipts/",toPath goodsReceiptId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetGoodsReceipt  
-- | @application/json@
instance Produces GetGoodsReceipt MimeJSON


-- *** listGoodsReceipts

-- | @GET \/api\/v1\/goods-receipts\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listGoodsReceipts
  :: SimpleBillyRequest ListGoodsReceipts MimeNoContent [GoodsReceipt] MimeJSON
listGoodsReceipts =
  _mkRequest "GET" ["/api/v1/goods-receipts/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListGoodsReceipts  
instance HasOptionalParam ListGoodsReceipts Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam ListGoodsReceipts PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam ListGoodsReceipts PurchaseOrderId where
  applyOptionalParam req (PurchaseOrderId xs) =
    req `addQuery` toQuery ("purchase_order_id", Just xs)
instance HasOptionalParam ListGoodsReceipts SupplierName where
  applyOptionalParam req (SupplierName xs) =
    req `addQuery` toQuery ("supplier_name", Just xs)
instance HasOptionalParam ListGoodsReceipts WarehouseId where
  applyOptionalParam req (WarehouseId xs) =
    req `addQuery` toQuery ("warehouse_id", Just xs)
-- | @application/json@
instance Produces ListGoodsReceipts MimeJSON

