{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.GroupFigure
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.GroupFigure where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** GroupFigure

-- *** createGroupFigure

-- | @POST \/api\/v1\/group-figures@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createGroupFigure
  :: (Consumes CreateGroupFigure MimeJSON, MimeRender MimeJSON GroupFigureCreate)
  => GroupFigureCreate -- ^ "groupFigureCreate"
  -> SimpleBillyRequest CreateGroupFigure MimeJSON GroupFigure MimeJSON
createGroupFigure groupFigureCreate =
  _mkRequest "POST" ["/api/v1/group-figures"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` groupFigureCreate

data CreateGroupFigure 
instance HasBodyParam CreateGroupFigure GroupFigureCreate 

-- | @application/json@
instance Consumes CreateGroupFigure MimeJSON

-- | @application/json@
instance Produces CreateGroupFigure MimeJSON


-- *** deleteGroupFigure

-- | @DELETE \/api\/v1\/group-figures\/{year}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteGroupFigure
  :: Year -- ^ "year"
  -> SimpleBillyRequest DeleteGroupFigure MimeNoContent NoContent MimeNoContent
deleteGroupFigure (Year year) =
  _mkRequest "DELETE" ["/api/v1/group-figures/",toPath year]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteGroupFigure  
instance Produces DeleteGroupFigure MimeNoContent


-- *** getGroupFigure

-- | @GET \/api\/v1\/group-figures\/{year}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getGroupFigure
  :: Year -- ^ "year"
  -> SimpleBillyRequest GetGroupFigure MimeNoContent GroupFigure MimeJSON
getGroupFigure (Year year) =
  _mkRequest "GET" ["/api/v1/group-figures/",toPath year]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetGroupFigure  
-- | @application/json@
instance Produces GetGroupFigure MimeJSON


-- *** getGroupFigures

-- | @GET \/api\/v1\/group-figures\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getGroupFigures
  :: SimpleBillyRequest GetGroupFigures MimeNoContent [GroupFigure] MimeJSON
getGroupFigures =
  _mkRequest "GET" ["/api/v1/group-figures/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetGroupFigures  
instance HasOptionalParam GetGroupFigures Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam GetGroupFigures PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam GetGroupFigures Search where
  applyOptionalParam req (Search xs) =
    req `addQuery` toQuery ("search", Just xs)

-- | /Optional Param/ "include_deleted" - Soft-delete entities: set true to include rows with `deleted_at` set.
instance HasOptionalParam GetGroupFigures IncludeDeleted where
  applyOptionalParam req (IncludeDeleted xs) =
    req `addQuery` toQuery ("include_deleted", Just xs)
-- | @application/json@
instance Produces GetGroupFigures MimeJSON


-- *** updateGroupFigure

-- | @PUT \/api\/v1\/group-figures\/{year}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateGroupFigure
  :: (Consumes UpdateGroupFigure MimeJSON, MimeRender MimeJSON GroupFigureUpdate)
  => GroupFigureUpdate -- ^ "groupFigureUpdate"
  -> Year -- ^ "year"
  -> SimpleBillyRequest UpdateGroupFigure MimeJSON GroupFigure MimeJSON
updateGroupFigure groupFigureUpdate (Year year) =
  _mkRequest "PUT" ["/api/v1/group-figures/",toPath year]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` groupFigureUpdate

data UpdateGroupFigure 
instance HasBodyParam UpdateGroupFigure GroupFigureUpdate 

-- | @application/json@
instance Consumes UpdateGroupFigure MimeJSON

-- | @application/json@
instance Produces UpdateGroupFigure MimeJSON

