{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.InventoryCount
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.InventoryCount where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** InventoryCount

-- *** createInventoryCount

-- | @POST \/api\/v1\/inventory-counts@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createInventoryCount
  :: (Consumes CreateInventoryCount MimeJSON, MimeRender MimeJSON InventoryCount)
  => InventoryCount -- ^ "inventoryCount"
  -> SimpleBillyRequest CreateInventoryCount MimeJSON InventoryCount MimeJSON
createInventoryCount inventoryCount =
  _mkRequest "POST" ["/api/v1/inventory-counts"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` inventoryCount

data CreateInventoryCount 
instance HasBodyParam CreateInventoryCount InventoryCount 

-- | @application/json@
instance Consumes CreateInventoryCount MimeJSON

-- | @application/json@
instance Produces CreateInventoryCount MimeJSON


-- *** deleteInventoryCount

-- | @DELETE \/api\/v1\/inventory-counts\/{inventory_count_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteInventoryCount
  :: InventoryCountId -- ^ "inventoryCountId"
  -> SimpleBillyRequest DeleteInventoryCount MimeNoContent NoContent MimeNoContent
deleteInventoryCount (InventoryCountId inventoryCountId) =
  _mkRequest "DELETE" ["/api/v1/inventory-counts/",toPath inventoryCountId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteInventoryCount  
instance Produces DeleteInventoryCount MimeNoContent


-- *** generateInventoryCount

-- | @POST \/api\/v1\/inventory-counts\/generate@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
generateInventoryCount
  :: (Consumes GenerateInventoryCount MimeJSON, MimeRender MimeJSON GenerateCountRequest)
  => GenerateCountRequest -- ^ "generateCountRequest"
  -> SimpleBillyRequest GenerateInventoryCount MimeJSON InventoryCount MimeJSON
generateInventoryCount generateCountRequest =
  _mkRequest "POST" ["/api/v1/inventory-counts/generate"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` generateCountRequest

data GenerateInventoryCount 
instance HasBodyParam GenerateInventoryCount GenerateCountRequest 

-- | @application/json@
instance Consumes GenerateInventoryCount MimeJSON

-- | @application/json@
instance Produces GenerateInventoryCount MimeJSON


-- *** getInventoryCount

-- | @GET \/api\/v1\/inventory-counts\/{inventory_count_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getInventoryCount
  :: InventoryCountId -- ^ "inventoryCountId"
  -> SimpleBillyRequest GetInventoryCount MimeNoContent InventoryCount MimeJSON
getInventoryCount (InventoryCountId inventoryCountId) =
  _mkRequest "GET" ["/api/v1/inventory-counts/",toPath inventoryCountId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetInventoryCount  
-- | @application/json@
instance Produces GetInventoryCount MimeJSON


-- *** listInventoryCounts

-- | @GET \/api\/v1\/inventory-counts\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listInventoryCounts
  :: SimpleBillyRequest ListInventoryCounts MimeNoContent [InventoryCount] MimeJSON
listInventoryCounts =
  _mkRequest "GET" ["/api/v1/inventory-counts/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListInventoryCounts  
instance HasOptionalParam ListInventoryCounts Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam ListInventoryCounts PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam ListInventoryCounts Status where
  applyOptionalParam req (Status xs) =
    req `addQuery` toQuery ("status", Just xs)
instance HasOptionalParam ListInventoryCounts WarehouseId where
  applyOptionalParam req (WarehouseId xs) =
    req `addQuery` toQuery ("warehouse_id", Just xs)
-- | @application/json@
instance Produces ListInventoryCounts MimeJSON


-- *** updateInventoryCount

-- | @PUT \/api\/v1\/inventory-counts\/{inventory_count_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateInventoryCount
  :: (Consumes UpdateInventoryCount MimeJSON, MimeRender MimeJSON Body)
  => Body -- ^ "body"
  -> InventoryCountId -- ^ "inventoryCountId"
  -> SimpleBillyRequest UpdateInventoryCount MimeJSON InventoryCount MimeJSON
updateInventoryCount body (InventoryCountId inventoryCountId) =
  _mkRequest "PUT" ["/api/v1/inventory-counts/",toPath inventoryCountId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` body

data UpdateInventoryCount 
instance HasBodyParam UpdateInventoryCount Body 

-- | @application/json@
instance Consumes UpdateInventoryCount MimeJSON

-- | @application/json@
instance Produces UpdateInventoryCount MimeJSON


-- *** updateInventoryCountStatus

-- | @PUT \/api\/v1\/inventory-counts\/{inventory_count_id}\/status@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateInventoryCountStatus
  :: (Consumes UpdateInventoryCountStatus MimeJSON, MimeRender MimeJSON InventoryCountStatusUpdate)
  => InventoryCountStatusUpdate -- ^ "inventoryCountStatusUpdate"
  -> InventoryCountId -- ^ "inventoryCountId"
  -> SimpleBillyRequest UpdateInventoryCountStatus MimeJSON InventoryCount MimeJSON
updateInventoryCountStatus inventoryCountStatusUpdate (InventoryCountId inventoryCountId) =
  _mkRequest "PUT" ["/api/v1/inventory-counts/",toPath inventoryCountId,"/status"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` inventoryCountStatusUpdate

data UpdateInventoryCountStatus 
instance HasBodyParam UpdateInventoryCountStatus InventoryCountStatusUpdate 

-- | @application/json@
instance Consumes UpdateInventoryCountStatus MimeJSON

-- | @application/json@
instance Produces UpdateInventoryCountStatus MimeJSON

