{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.Invoice
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.Invoice where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Invoice

-- *** createInvoice

-- | @POST \/api\/v1\/invoices@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createInvoice
  :: (Consumes CreateInvoice MimeJSON, MimeRender MimeJSON InvoiceCreate)
  => InvoiceCreate -- ^ "invoiceCreate"
  -> SimpleBillyRequest CreateInvoice MimeJSON Invoice MimeJSON
createInvoice invoiceCreate =
  _mkRequest "POST" ["/api/v1/invoices"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` invoiceCreate

data CreateInvoice 
instance HasBodyParam CreateInvoice InvoiceCreate 

-- | @application/json@
instance Consumes CreateInvoice MimeJSON

-- | @application/json@
instance Produces CreateInvoice MimeJSON


-- *** deleteInvoice

-- | @DELETE \/api\/v1\/invoices\/{id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteInvoice
  :: Id -- ^ "id"
  -> SimpleBillyRequest DeleteInvoice MimeNoContent NoContent MimeNoContent
deleteInvoice (Id id) =
  _mkRequest "DELETE" ["/api/v1/invoices/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteInvoice  
instance Produces DeleteInvoice MimeNoContent


-- *** downloadInvoicePdf

-- | @GET \/api\/v1\/invoices\/{id}\/pdf@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
downloadInvoicePdf
  :: Id -- ^ "id"
  -> SimpleBillyRequest DownloadInvoicePdf MimeNoContent NoContent MimeNoContent
downloadInvoicePdf (Id id) =
  _mkRequest "GET" ["/api/v1/invoices/",toPath id,"/pdf"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DownloadInvoicePdf  
instance Produces DownloadInvoicePdf MimeNoContent


-- *** getInvoice

-- | @GET \/api\/v1\/invoices\/{id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getInvoice
  :: Id -- ^ "id"
  -> SimpleBillyRequest GetInvoice MimeNoContent Invoice MimeJSON
getInvoice (Id id) =
  _mkRequest "GET" ["/api/v1/invoices/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetInvoice  
-- | @application/json@
instance Produces GetInvoice MimeJSON


-- *** getInvoicePdfUrl

-- | @GET \/api\/v1\/invoices\/{id}\/pdf-url@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getInvoicePdfUrl
  :: Id -- ^ "id"
  -> SimpleBillyRequest GetInvoicePdfUrl MimeNoContent InvoicePdfUrlResponse MimeJSON
getInvoicePdfUrl (Id id) =
  _mkRequest "GET" ["/api/v1/invoices/",toPath id,"/pdf-url"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetInvoicePdfUrl  
-- | @application/json@
instance Produces GetInvoicePdfUrl MimeJSON


-- *** getInvoices

-- | @GET \/api\/v1\/invoices\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getInvoices
  :: SimpleBillyRequest GetInvoices MimeNoContent [Invoice] MimeJSON
getInvoices =
  _mkRequest "GET" ["/api/v1/invoices/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetInvoices  
instance HasOptionalParam GetInvoices Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam GetInvoices PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam GetInvoices Search where
  applyOptionalParam req (Search xs) =
    req `addQuery` toQuery ("search", Just xs)

-- | /Optional Param/ "include_deleted" - Soft-delete entities: set true to include rows with `deleted_at` set.
instance HasOptionalParam GetInvoices IncludeDeleted where
  applyOptionalParam req (IncludeDeleted xs) =
    req `addQuery` toQuery ("include_deleted", Just xs)
-- | @application/json@
instance Produces GetInvoices MimeJSON


-- *** invoiceRestore

-- | @POST \/api\/v1\/invoices\/{id}\/restore@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
invoiceRestore
  :: Id -- ^ "id"
  -> SimpleBillyRequest InvoiceRestore MimeNoContent Invoice MimeJSON
invoiceRestore (Id id) =
  _mkRequest "POST" ["/api/v1/invoices/",toPath id,"/restore"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data InvoiceRestore  
-- | @application/json@
instance Produces InvoiceRestore MimeJSON


-- *** updateInvoice

-- | @PUT \/api\/v1\/invoices\/{id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateInvoice
  :: (Consumes UpdateInvoice MimeJSON, MimeRender MimeJSON Body)
  => Body -- ^ "body"
  -> Id -- ^ "id"
  -> SimpleBillyRequest UpdateInvoice MimeJSON Invoice MimeJSON
updateInvoice body (Id id) =
  _mkRequest "PUT" ["/api/v1/invoices/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` body

data UpdateInvoice 
instance HasBodyParam UpdateInvoice Body 

-- | @application/json@
instance Consumes UpdateInvoice MimeJSON

-- | @application/json@
instance Produces UpdateInvoice MimeJSON

