{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.JobPosting
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.JobPosting where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** JobPosting

-- *** createJobPosting

-- | @POST \/api\/v1\/job-postings@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createJobPosting
  :: (Consumes CreateJobPosting MimeJSON, MimeRender MimeJSON JobPostingCreate)
  => JobPostingCreate -- ^ "jobPostingCreate"
  -> SimpleBillyRequest CreateJobPosting MimeJSON JobPosting MimeJSON
createJobPosting jobPostingCreate =
  _mkRequest "POST" ["/api/v1/job-postings"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` jobPostingCreate

data CreateJobPosting 
instance HasBodyParam CreateJobPosting JobPostingCreate 

-- | @application/json@
instance Consumes CreateJobPosting MimeJSON

-- | @application/json@
instance Produces CreateJobPosting MimeJSON


-- *** deleteJobPosting

-- | @DELETE \/api\/v1\/job-postings\/{id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteJobPosting
  :: Id -- ^ "id"
  -> SimpleBillyRequest DeleteJobPosting MimeNoContent NoContent MimeNoContent
deleteJobPosting (Id id) =
  _mkRequest "DELETE" ["/api/v1/job-postings/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteJobPosting  
instance Produces DeleteJobPosting MimeNoContent


-- *** getJobPosting

-- | @GET \/api\/v1\/job-postings\/{id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getJobPosting
  :: Id -- ^ "id"
  -> SimpleBillyRequest GetJobPosting MimeNoContent JobPosting MimeJSON
getJobPosting (Id id) =
  _mkRequest "GET" ["/api/v1/job-postings/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetJobPosting  
-- | @application/json@
instance Produces GetJobPosting MimeJSON


-- *** listJobPostings

-- | @GET \/api\/v1\/job-postings@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listJobPostings
  :: SimpleBillyRequest ListJobPostings MimeNoContent [JobPosting] MimeJSON
listJobPostings =
  _mkRequest "GET" ["/api/v1/job-postings"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListJobPostings  
instance HasOptionalParam ListJobPostings Status where
  applyOptionalParam req (Status xs) =
    req `addQuery` toQuery ("status", Just xs)
instance HasOptionalParam ListJobPostings Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam ListJobPostings PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("pageSize", Just xs)
-- | @application/json@
instance Produces ListJobPostings MimeJSON


-- *** updateJobPosting

-- | @PUT \/api\/v1\/job-postings\/{id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateJobPosting
  :: (Consumes UpdateJobPosting MimeJSON, MimeRender MimeJSON JobPostingUpdate)
  => JobPostingUpdate -- ^ "jobPostingUpdate"
  -> Id -- ^ "id"
  -> SimpleBillyRequest UpdateJobPosting MimeJSON JobPosting MimeJSON
updateJobPosting jobPostingUpdate (Id id) =
  _mkRequest "PUT" ["/api/v1/job-postings/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` jobPostingUpdate

data UpdateJobPosting 
instance HasBodyParam UpdateJobPosting JobPostingUpdate 

-- | @application/json@
instance Consumes UpdateJobPosting MimeJSON

-- | @application/json@
instance Produces UpdateJobPosting MimeJSON

