{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.KycRecord
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.KycRecord where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** KycRecord

-- *** createKycRecord

-- | @POST \/api\/v1\/kyc-records@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createKycRecord
  :: (Consumes CreateKycRecord MimeJSON, MimeRender MimeJSON KycRecordCreate)
  => KycRecordCreate -- ^ "kycRecordCreate"
  -> SimpleBillyRequest CreateKycRecord MimeJSON KycRecord MimeJSON
createKycRecord kycRecordCreate =
  _mkRequest "POST" ["/api/v1/kyc-records"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` kycRecordCreate

data CreateKycRecord 
instance HasBodyParam CreateKycRecord KycRecordCreate 

-- | @application/json@
instance Consumes CreateKycRecord MimeJSON

-- | @application/json@
instance Produces CreateKycRecord MimeJSON


-- *** deleteKycRecord

-- | @DELETE \/api\/v1\/kyc-records\/{id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteKycRecord
  :: Id -- ^ "id"
  -> SimpleBillyRequest DeleteKycRecord MimeNoContent NoContent MimeNoContent
deleteKycRecord (Id id) =
  _mkRequest "DELETE" ["/api/v1/kyc-records/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteKycRecord  
instance Produces DeleteKycRecord MimeNoContent


-- *** getKycRecord

-- | @GET \/api\/v1\/kyc-records\/{id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getKycRecord
  :: Id -- ^ "id"
  -> SimpleBillyRequest GetKycRecord MimeNoContent KycRecord MimeJSON
getKycRecord (Id id) =
  _mkRequest "GET" ["/api/v1/kyc-records/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetKycRecord  
-- | @application/json@
instance Produces GetKycRecord MimeJSON


-- *** getKycRecords

-- | @GET \/api\/v1\/kyc-records\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getKycRecords
  :: SimpleBillyRequest GetKycRecords MimeNoContent [KycRecord] MimeJSON
getKycRecords =
  _mkRequest "GET" ["/api/v1/kyc-records/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetKycRecords  
instance HasOptionalParam GetKycRecords Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam GetKycRecords PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam GetKycRecords Search where
  applyOptionalParam req (Search xs) =
    req `addQuery` toQuery ("search", Just xs)

-- | /Optional Param/ "include_deleted" - Soft-delete entities: set true to include rows with `deleted_at` set.
instance HasOptionalParam GetKycRecords IncludeDeleted where
  applyOptionalParam req (IncludeDeleted xs) =
    req `addQuery` toQuery ("include_deleted", Just xs)
-- | @application/json@
instance Produces GetKycRecords MimeJSON


-- *** updateKycRecord

-- | @PUT \/api\/v1\/kyc-records\/{id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateKycRecord
  :: (Consumes UpdateKycRecord MimeJSON, MimeRender MimeJSON KycRecordUpdate)
  => KycRecordUpdate -- ^ "kycRecordUpdate"
  -> Id -- ^ "id"
  -> SimpleBillyRequest UpdateKycRecord MimeJSON KycRecord MimeJSON
updateKycRecord kycRecordUpdate (Id id) =
  _mkRequest "PUT" ["/api/v1/kyc-records/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` kycRecordUpdate

data UpdateKycRecord 
instance HasBodyParam UpdateKycRecord KycRecordUpdate 

-- | @application/json@
instance Consumes UpdateKycRecord MimeJSON

-- | @application/json@
instance Produces UpdateKycRecord MimeJSON

