{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.LegalDocument
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.LegalDocument where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** LegalDocument

-- *** getLegalDocuments

-- | @GET \/api\/v1\/legal\/documents@
-- 
-- List all legal documents of the tenant. Missing documents are seeded from the default texts (with tenant placeholders replaced) on first access.
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getLegalDocuments
  :: SimpleBillyRequest GetLegalDocuments MimeNoContent [LegalDocument] MimeJSON
getLegalDocuments =
  _mkRequest "GET" ["/api/v1/legal/documents"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetLegalDocuments  
-- | @application/json@
instance Produces GetLegalDocuments MimeJSON


-- *** resetLegalDocuments

-- | @POST \/api\/v1\/legal\/documents\/reset@
-- 
-- Restore default texts for all documents (or a single doc_type/lang when the optional filter is given). Returns the full tenant list.
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
resetLegalDocuments
  :: (Consumes ResetLegalDocuments MimeJSON, MimeRender MimeJSON LegalDocumentReset)
  => LegalDocumentReset -- ^ "legalDocumentReset"
  -> SimpleBillyRequest ResetLegalDocuments MimeJSON [LegalDocument] MimeJSON
resetLegalDocuments legalDocumentReset =
  _mkRequest "POST" ["/api/v1/legal/documents/reset"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` legalDocumentReset

data ResetLegalDocuments 
instance HasBodyParam ResetLegalDocuments LegalDocumentReset 

-- | @application/json@
instance Consumes ResetLegalDocuments MimeJSON

-- | @application/json@
instance Produces ResetLegalDocuments MimeJSON


-- *** upsertLegalDocuments

-- | @PUT \/api\/v1\/legal\/documents@
-- 
-- Upsert legal documents per (doc_type, lang). Returns the full tenant list.
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
upsertLegalDocuments
  :: (Consumes UpsertLegalDocuments MimeJSON, MimeRender MimeJSON LegalDocumentUpsert2)
  => LegalDocumentUpsert2 -- ^ "legalDocumentUpsert"
  -> SimpleBillyRequest UpsertLegalDocuments MimeJSON [LegalDocument] MimeJSON
upsertLegalDocuments legalDocumentUpsert =
  _mkRequest "PUT" ["/api/v1/legal/documents"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` legalDocumentUpsert

data UpsertLegalDocuments 
instance HasBodyParam UpsertLegalDocuments LegalDocumentUpsert2 

-- | @application/json@
instance Consumes UpsertLegalDocuments MimeJSON

-- | @application/json@
instance Produces UpsertLegalDocuments MimeJSON

