{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.Notifications
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.Notifications where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Notifications

-- *** deleteNotification

-- | @DELETE \/api\/v1\/notifications\/{id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteNotification
  :: Id -- ^ "id"
  -> SimpleBillyRequest DeleteNotification MimeNoContent NoContent MimeNoContent
deleteNotification (Id id) =
  _mkRequest "DELETE" ["/api/v1/notifications/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteNotification  
instance Produces DeleteNotification MimeNoContent


-- *** listNotifications

-- | @GET \/api\/v1\/notifications@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listNotifications
  :: SimpleBillyRequest ListNotifications MimeNoContent [NotificationDto] MimeJSON
listNotifications =
  _mkRequest "GET" ["/api/v1/notifications"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListNotifications  
-- | @application/json@
instance Produces ListNotifications MimeJSON


-- *** markAllRead

-- | @PUT \/api\/v1\/notifications\/read-all@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
markAllRead
  :: SimpleBillyRequest MarkAllRead MimeNoContent Integer MimePlainText
markAllRead =
  _mkRequest "PUT" ["/api/v1/notifications/read-all"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data MarkAllRead  
-- | @text/plain@
instance Produces MarkAllRead MimePlainText


-- *** markAsRead

-- | @PUT \/api\/v1\/notifications\/{id}\/read@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
markAsRead
  :: Id -- ^ "id"
  -> SimpleBillyRequest MarkAsRead MimeNoContent NoContent MimeNoContent
markAsRead (Id id) =
  _mkRequest "PUT" ["/api/v1/notifications/",toPath id,"/read"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data MarkAsRead  
instance Produces MarkAsRead MimeNoContent


-- *** unreadCount

-- | @GET \/api\/v1\/notifications\/unread-count@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
unreadCount
  :: SimpleBillyRequest UnreadCount MimeNoContent Integer MimePlainText
unreadCount =
  _mkRequest "GET" ["/api/v1/notifications/unread-count"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data UnreadCount  
-- | @text/plain@
instance Produces UnreadCount MimePlainText

