{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.Order
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.Order where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Order

-- *** addOrderTags

-- | @POST \/api\/v1\/orders\/{order_id}\/tags@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
addOrderTags
  :: (Consumes AddOrderTags MimeJSON, MimeRender MimeJSON OrderTagsRequest)
  => OrderTagsRequest -- ^ "orderTagsRequest"
  -> OrderId -- ^ "orderId"
  -> SimpleBillyRequest AddOrderTags MimeJSON Order MimeJSON
addOrderTags orderTagsRequest (OrderId orderId) =
  _mkRequest "POST" ["/api/v1/orders/",toPath orderId,"/tags"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` orderTagsRequest

data AddOrderTags 
instance HasBodyParam AddOrderTags OrderTagsRequest 

-- | @application/json@
instance Consumes AddOrderTags MimeJSON

-- | @application/json@
instance Produces AddOrderTags MimeJSON


-- *** findOrderByExternalRef

-- | @GET \/api\/v1\/orders\/by-ext-ref\/{ext_ref}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
findOrderByExternalRef
  :: ExtRef -- ^ "extRef"
  -> SimpleBillyRequest FindOrderByExternalRef MimeNoContent Order MimeJSON
findOrderByExternalRef (ExtRef extRef) =
  _mkRequest "GET" ["/api/v1/orders/by-ext-ref/",toPath extRef]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data FindOrderByExternalRef  
-- | @application/json@
instance Produces FindOrderByExternalRef MimeJSON


-- *** getOrder

-- | @GET \/api\/v1\/order\/{order_number}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getOrder
  :: OrderNumber -- ^ "orderNumber"
  -> SimpleBillyRequest GetOrder MimeNoContent Order MimeJSON
getOrder (OrderNumber orderNumber) =
  _mkRequest "GET" ["/api/v1/order/",toPath orderNumber]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetOrder  
-- | @application/json@
instance Produces GetOrder MimeJSON


-- *** getOrders

-- | @GET \/api\/v1\/orders@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getOrders
  :: SimpleBillyRequest GetOrders MimeNoContent [Order] MimeJSON
getOrders =
  _mkRequest "GET" ["/api/v1/orders"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetOrders  
instance HasOptionalParam GetOrders Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam GetOrders PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam GetOrders Search where
  applyOptionalParam req (Search xs) =
    req `addQuery` toQuery ("search", Just xs)

-- | /Optional Param/ "include_deleted" - Soft-delete entities: set true to include rows with `deleted_at` set.
instance HasOptionalParam GetOrders IncludeDeleted where
  applyOptionalParam req (IncludeDeleted xs) =
    req `addQuery` toQuery ("include_deleted", Just xs)
-- | @application/json@
instance Produces GetOrders MimeJSON


-- *** patchOrder

-- | @PATCH \/api\/v1\/orders\/{order_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
patchOrder
  :: (Consumes PatchOrder MimeJSON, MimeRender MimeJSON Body)
  => Body -- ^ "body"
  -> OrderId -- ^ "orderId"
  -> SimpleBillyRequest PatchOrder MimeJSON Order MimeJSON
patchOrder body (OrderId orderId) =
  _mkRequest "PATCH" ["/api/v1/orders/",toPath orderId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` body

data PatchOrder 
instance HasBodyParam PatchOrder Body 

-- | @application/json@
instance Consumes PatchOrder MimeJSON

-- | @application/json@
instance Produces PatchOrder MimeJSON


-- *** replaceOrderTags

-- | @PUT \/api\/v1\/orders\/{order_id}\/tags@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
replaceOrderTags
  :: (Consumes ReplaceOrderTags MimeJSON, MimeRender MimeJSON OrderTagsRequest)
  => OrderTagsRequest -- ^ "orderTagsRequest"
  -> OrderId -- ^ "orderId"
  -> SimpleBillyRequest ReplaceOrderTags MimeJSON Order MimeJSON
replaceOrderTags orderTagsRequest (OrderId orderId) =
  _mkRequest "PUT" ["/api/v1/orders/",toPath orderId,"/tags"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` orderTagsRequest

data ReplaceOrderTags 
instance HasBodyParam ReplaceOrderTags OrderTagsRequest 

-- | @application/json@
instance Consumes ReplaceOrderTags MimeJSON

-- | @application/json@
instance Produces ReplaceOrderTags MimeJSON


-- *** updateOrderState

-- | @PUT \/api\/v1\/orders\/{order_id}\/state@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateOrderState
  :: (Consumes UpdateOrderState MimeJSON, MimeRender MimeJSON OrderStateUpdate)
  => OrderStateUpdate -- ^ "orderStateUpdate"
  -> OrderId -- ^ "orderId"
  -> SimpleBillyRequest UpdateOrderState MimeJSON Order MimeJSON
updateOrderState orderStateUpdate (OrderId orderId) =
  _mkRequest "PUT" ["/api/v1/orders/",toPath orderId,"/state"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` orderStateUpdate

data UpdateOrderState 
instance HasBodyParam UpdateOrderState OrderStateUpdate 

-- | @application/json@
instance Consumes UpdateOrderState MimeJSON

-- | @application/json@
instance Produces UpdateOrderState MimeJSON

