{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.OrderConfirmation
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.OrderConfirmation where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** OrderConfirmation

-- *** createConfirmation

-- | @POST \/api\/v1\/order-confirmations@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createConfirmation
  :: (Consumes CreateConfirmation MimeJSON, MimeRender MimeJSON OrderConfirmationCreate)
  => OrderConfirmationCreate -- ^ "orderConfirmationCreate"
  -> SimpleBillyRequest CreateConfirmation MimeJSON OrderConfirmation MimeJSON
createConfirmation orderConfirmationCreate =
  _mkRequest "POST" ["/api/v1/order-confirmations"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` orderConfirmationCreate

data CreateConfirmation 
instance HasBodyParam CreateConfirmation OrderConfirmationCreate 

-- | @application/json@
instance Consumes CreateConfirmation MimeJSON

-- | @application/json@
instance Produces CreateConfirmation MimeJSON


-- *** deleteConfirmation

-- | @DELETE \/api\/v1\/order-confirmations\/{confirmation_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteConfirmation
  :: ConfirmationId -- ^ "confirmationId"
  -> SimpleBillyRequest DeleteConfirmation MimeNoContent NoContent MimeNoContent
deleteConfirmation (ConfirmationId confirmationId) =
  _mkRequest "DELETE" ["/api/v1/order-confirmations/",toPath confirmationId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteConfirmation  
instance Produces DeleteConfirmation MimeNoContent


-- *** downloadConfirmationPdf

-- | @GET \/api\/v1\/order-confirmations\/{confirmation_id}\/pdf@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
downloadConfirmationPdf
  :: ConfirmationId -- ^ "confirmationId"
  -> SimpleBillyRequest DownloadConfirmationPdf MimeNoContent NoContent MimeNoContent
downloadConfirmationPdf (ConfirmationId confirmationId) =
  _mkRequest "GET" ["/api/v1/order-confirmations/",toPath confirmationId,"/pdf"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DownloadConfirmationPdf  
instance Produces DownloadConfirmationPdf MimeNoContent


-- *** getConfirmation

-- | @GET \/api\/v1\/order-confirmations\/{confirmation_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getConfirmation
  :: ConfirmationId -- ^ "confirmationId"
  -> SimpleBillyRequest GetConfirmation MimeNoContent OrderConfirmation MimeJSON
getConfirmation (ConfirmationId confirmationId) =
  _mkRequest "GET" ["/api/v1/order-confirmations/",toPath confirmationId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetConfirmation  
-- | @application/json@
instance Produces GetConfirmation MimeJSON


-- *** listConfirmations

-- | @GET \/api\/v1\/order-confirmations\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listConfirmations
  :: SimpleBillyRequest ListConfirmations MimeNoContent [OrderConfirmation] MimeJSON
listConfirmations =
  _mkRequest "GET" ["/api/v1/order-confirmations/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListConfirmations  
instance HasOptionalParam ListConfirmations Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam ListConfirmations PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam ListConfirmations Search where
  applyOptionalParam req (Search xs) =
    req `addQuery` toQuery ("search", Just xs)

-- | /Optional Param/ "include_deleted" - Soft-delete entities: set true to include rows with `deleted_at` set.
instance HasOptionalParam ListConfirmations IncludeDeleted where
  applyOptionalParam req (IncludeDeleted xs) =
    req `addQuery` toQuery ("include_deleted", Just xs)
-- | @application/json@
instance Produces ListConfirmations MimeJSON


-- *** orderconfirmationRestore

-- | @POST \/api\/v1\/order-confirmations\/{confirmation_id}\/restore@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
orderconfirmationRestore
  :: ConfirmationId -- ^ "confirmationId"
  -> SimpleBillyRequest OrderconfirmationRestore MimeNoContent OrderConfirmation MimeJSON
orderconfirmationRestore (ConfirmationId confirmationId) =
  _mkRequest "POST" ["/api/v1/order-confirmations/",toPath confirmationId,"/restore"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data OrderconfirmationRestore  
-- | @application/json@
instance Produces OrderconfirmationRestore MimeJSON


-- *** pursueConfirmation

-- | @POST \/api\/v1\/order-confirmations\/{confirmation_id}\/pursue@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
pursueConfirmation
  :: ConfirmationId -- ^ "confirmationId"
  -> SimpleBillyRequest PursueConfirmation MimeNoContent DeliveryNote MimeJSON
pursueConfirmation (ConfirmationId confirmationId) =
  _mkRequest "POST" ["/api/v1/order-confirmations/",toPath confirmationId,"/pursue"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data PursueConfirmation  
-- | @application/json@
instance Produces PursueConfirmation MimeJSON

