{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.Packing
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.Packing where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Packing

-- *** completePacking

-- | @POST \/api\/v1\/packing\/{order_number}\/complete@
-- 
-- Mark packing as complete and transition order to shipped
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
completePacking
  :: (Consumes CompletePacking MimeJSON, MimeRender MimeJSON PackingCompleteRequest)
  => PackingCompleteRequest -- ^ "packingCompleteRequest"
  -> OrderNumber -- ^ "orderNumber"
  -> SimpleBillyRequest CompletePacking MimeJSON PackingCompleteResponse MimeJSON
completePacking packingCompleteRequest (OrderNumber orderNumber) =
  _mkRequest "POST" ["/api/v1/packing/",toPath orderNumber,"/complete"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` packingCompleteRequest

data CompletePacking 
instance HasBodyParam CompletePacking PackingCompleteRequest 

-- | @application/json@
instance Consumes CompletePacking MimeJSON

-- | @application/json@
instance Produces CompletePacking MimeJSON


-- *** getPackingQueue

-- | @GET \/api\/v1\/packing\/queue@
-- 
-- Get the packing queue - orders ready for packing
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getPackingQueue
  :: SimpleBillyRequest GetPackingQueue MimeNoContent PackingQueue MimeJSON
getPackingQueue =
  _mkRequest "GET" ["/api/v1/packing/queue"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetPackingQueue  
instance HasOptionalParam GetPackingQueue Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam GetPackingQueue PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam GetPackingQueue Search where
  applyOptionalParam req (Search xs) =
    req `addQuery` toQuery ("search", Just xs)
-- | @application/json@
instance Produces GetPackingQueue MimeJSON


-- *** printDeliveryNote

-- | @POST \/api\/v1\/packing\/{order_number}\/print-delivery-note@
-- 
-- Print delivery note (Lieferschein) for an order
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
printDeliveryNote
  :: OrderNumber -- ^ "orderNumber"
  -> SimpleBillyRequest PrintDeliveryNote MimeNoContent PrintDeliveryNoteResponse MimeJSON
printDeliveryNote (OrderNumber orderNumber) =
  _mkRequest "POST" ["/api/v1/packing/",toPath orderNumber,"/print-delivery-note"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data PrintDeliveryNote  
-- | @application/json@
instance Produces PrintDeliveryNote MimeJSON


-- *** printLabel

-- | @POST \/api\/v1\/packing\/{order_number}\/print-label@
-- 
-- Print shipping label for an order
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
printLabel
  :: OrderNumber -- ^ "orderNumber"
  -> SimpleBillyRequest PrintLabel MimeNoContent PrintLabelResponse MimeJSON
printLabel (OrderNumber orderNumber) =
  _mkRequest "POST" ["/api/v1/packing/",toPath orderNumber,"/print-label"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data PrintLabel  
-- | @application/json@
instance Produces PrintLabel MimeJSON


-- *** recordPackingVideo

-- | @POST \/api\/v1\/packing\/{order_number}\/record-video@
-- 
-- Record video of packing process
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
recordPackingVideo
  :: (Consumes RecordPackingVideo MimeJSON, MimeRender MimeJSON Body)
  => Body -- ^ "body"
  -> OrderNumber -- ^ "orderNumber"
  -> SimpleBillyRequest RecordPackingVideo MimeJSON PackingVideoResponse MimeJSON
recordPackingVideo body (OrderNumber orderNumber) =
  _mkRequest "POST" ["/api/v1/packing/",toPath orderNumber,"/record-video"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` body

data RecordPackingVideo 
instance HasBodyParam RecordPackingVideo Body 

-- | @application/json@
instance Consumes RecordPackingVideo MimeJSON

-- | @application/json@
instance Produces RecordPackingVideo MimeJSON

