{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.Participation
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.Participation where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Participation

-- *** createParticipation

-- | @POST \/api\/v1\/participations@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createParticipation
  :: (Consumes CreateParticipation MimeJSON, MimeRender MimeJSON ParticipationCreate)
  => ParticipationCreate -- ^ "participationCreate"
  -> SimpleBillyRequest CreateParticipation MimeJSON Participation MimeJSON
createParticipation participationCreate =
  _mkRequest "POST" ["/api/v1/participations"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` participationCreate

data CreateParticipation 
instance HasBodyParam CreateParticipation ParticipationCreate 

-- | @application/json@
instance Consumes CreateParticipation MimeJSON

-- | @application/json@
instance Produces CreateParticipation MimeJSON


-- *** deleteParticipation

-- | @DELETE \/api\/v1\/participations\/{id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteParticipation
  :: Id -- ^ "id"
  -> SimpleBillyRequest DeleteParticipation MimeNoContent NoContent MimeNoContent
deleteParticipation (Id id) =
  _mkRequest "DELETE" ["/api/v1/participations/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteParticipation  
instance Produces DeleteParticipation MimeNoContent


-- *** getParticipation

-- | @GET \/api\/v1\/participations\/{id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getParticipation
  :: Id -- ^ "id"
  -> SimpleBillyRequest GetParticipation MimeNoContent Participation MimeJSON
getParticipation (Id id) =
  _mkRequest "GET" ["/api/v1/participations/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetParticipation  
-- | @application/json@
instance Produces GetParticipation MimeJSON


-- *** getParticipations

-- | @GET \/api\/v1\/participations\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getParticipations
  :: SimpleBillyRequest GetParticipations MimeNoContent [Participation] MimeJSON
getParticipations =
  _mkRequest "GET" ["/api/v1/participations/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetParticipations  
instance HasOptionalParam GetParticipations Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam GetParticipations PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam GetParticipations Search where
  applyOptionalParam req (Search xs) =
    req `addQuery` toQuery ("search", Just xs)

-- | /Optional Param/ "include_deleted" - Soft-delete entities: set true to include rows with `deleted_at` set.
instance HasOptionalParam GetParticipations IncludeDeleted where
  applyOptionalParam req (IncludeDeleted xs) =
    req `addQuery` toQuery ("include_deleted", Just xs)
-- | @application/json@
instance Produces GetParticipations MimeJSON


-- *** updateParticipation

-- | @PUT \/api\/v1\/participations\/{id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateParticipation
  :: (Consumes UpdateParticipation MimeJSON, MimeRender MimeJSON ParticipationUpdate)
  => ParticipationUpdate -- ^ "participationUpdate"
  -> Id -- ^ "id"
  -> SimpleBillyRequest UpdateParticipation MimeJSON Participation MimeJSON
updateParticipation participationUpdate (Id id) =
  _mkRequest "PUT" ["/api/v1/participations/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` participationUpdate

data UpdateParticipation 
instance HasBodyParam UpdateParticipation ParticipationUpdate 

-- | @application/json@
instance Consumes UpdateParticipation MimeJSON

-- | @application/json@
instance Produces UpdateParticipation MimeJSON

