{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.PaymentGateway
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.PaymentGateway where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** PaymentGateway

-- *** createPaymentGatewayApi

-- | @POST \/api\/v1\/payment-gateways@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createPaymentGatewayApi
  :: (Consumes CreatePaymentGatewayApi MimeJSON, MimeRender MimeJSON Body)
  => Body -- ^ "body"
  -> SimpleBillyRequest CreatePaymentGatewayApi MimeJSON PaymentGateway MimeJSON
createPaymentGatewayApi body =
  _mkRequest "POST" ["/api/v1/payment-gateways"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` body

data CreatePaymentGatewayApi 
instance HasBodyParam CreatePaymentGatewayApi Body 

-- | @application/json@
instance Consumes CreatePaymentGatewayApi MimeJSON

-- | @application/json@
instance Produces CreatePaymentGatewayApi MimeJSON


-- *** deletePaymentGatewayApi

-- | @DELETE \/api\/v1\/payment-gateways\/{gateway_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deletePaymentGatewayApi
  :: GatewayId -- ^ "gatewayId"
  -> SimpleBillyRequest DeletePaymentGatewayApi MimeNoContent NoContent MimeNoContent
deletePaymentGatewayApi (GatewayId gatewayId) =
  _mkRequest "DELETE" ["/api/v1/payment-gateways/",toPath gatewayId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeletePaymentGatewayApi  
instance Produces DeletePaymentGatewayApi MimeNoContent


-- *** listPaymentGatewaysApi

-- | @GET \/api\/v1\/payment-gateways\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listPaymentGatewaysApi
  :: SimpleBillyRequest ListPaymentGatewaysApi MimeNoContent [PaymentGateway] MimeJSON
listPaymentGatewaysApi =
  _mkRequest "GET" ["/api/v1/payment-gateways/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListPaymentGatewaysApi  
-- | @application/json@
instance Produces ListPaymentGatewaysApi MimeJSON


-- *** oauthAuthorizeApi0

-- | @POST \/api\/v1\/payment-gateways\/oauth\/authorize@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
oauthAuthorizeApi0
  :: (Consumes OauthAuthorizeApi0 MimeJSON, MimeRender MimeJSON GatewayOAuthAuthorizeRequest)
  => GatewayOAuthAuthorizeRequest -- ^ "gatewayOAuthAuthorizeRequest"
  -> SimpleBillyRequest OauthAuthorizeApi0 MimeJSON GatewayOAuthAuthorizeResponse MimeJSON
oauthAuthorizeApi0 gatewayOAuthAuthorizeRequest =
  _mkRequest "POST" ["/api/v1/payment-gateways/oauth/authorize"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` gatewayOAuthAuthorizeRequest

data OauthAuthorizeApi0 
instance HasBodyParam OauthAuthorizeApi0 GatewayOAuthAuthorizeRequest 

-- | @application/json@
instance Consumes OauthAuthorizeApi0 MimeJSON

-- | @application/json@
instance Produces OauthAuthorizeApi0 MimeJSON


-- *** oauthCallbackApi0

-- | @POST \/api\/v1\/payment-gateways\/oauth\/callback@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
oauthCallbackApi0
  :: (Consumes OauthCallbackApi0 MimeJSON, MimeRender MimeJSON GatewayOAuthCallbackRequest)
  => GatewayOAuthCallbackRequest -- ^ "gatewayOAuthCallbackRequest"
  -> SimpleBillyRequest OauthCallbackApi0 MimeJSON PaymentGateway MimeJSON
oauthCallbackApi0 gatewayOAuthCallbackRequest =
  _mkRequest "POST" ["/api/v1/payment-gateways/oauth/callback"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` gatewayOAuthCallbackRequest

data OauthCallbackApi0 
instance HasBodyParam OauthCallbackApi0 GatewayOAuthCallbackRequest 

-- | @application/json@
instance Consumes OauthCallbackApi0 MimeJSON

-- | @application/json@
instance Produces OauthCallbackApi0 MimeJSON


-- *** updatePaymentGatewayApi

-- | @PUT \/api\/v1\/payment-gateways\/{gateway_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updatePaymentGatewayApi
  :: (Consumes UpdatePaymentGatewayApi MimeJSON, MimeRender MimeJSON Body)
  => Body -- ^ "body"
  -> GatewayId -- ^ "gatewayId"
  -> SimpleBillyRequest UpdatePaymentGatewayApi MimeJSON PaymentGateway MimeJSON
updatePaymentGatewayApi body (GatewayId gatewayId) =
  _mkRequest "PUT" ["/api/v1/payment-gateways/",toPath gatewayId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` body

data UpdatePaymentGatewayApi 
instance HasBodyParam UpdatePaymentGatewayApi Body 

-- | @application/json@
instance Consumes UpdatePaymentGatewayApi MimeJSON

-- | @application/json@
instance Produces UpdatePaymentGatewayApi MimeJSON

