{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.Payroll
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.Payroll where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Payroll

-- *** payrollApprove

-- | @POST \/api\/v1\/payroll\/{id}\/approve@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
payrollApprove
  :: Id -- ^ "id"
  -> SimpleBillyRequest PayrollApprove MimeNoContent PayrollRunApi MimeJSON
payrollApprove (Id id) =
  _mkRequest "POST" ["/api/v1/payroll/",toPath id,"/approve"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data PayrollApprove  
-- | @application/json@
instance Produces PayrollApprove MimeJSON


-- *** payrollAutopay

-- | @POST \/api\/v1\/payroll\/{id}\/autopay@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
payrollAutopay
  :: (Consumes PayrollAutopay MimeJSON)
  => Id -- ^ "id"
  -> SimpleBillyRequest PayrollAutopay MimeJSON AnyType MimeJSON
payrollAutopay (Id id) =
  _mkRequest "POST" ["/api/v1/payroll/",toPath id,"/autopay"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data PayrollAutopay 
instance HasBodyParam PayrollAutopay Body 

-- | @application/json@
instance Consumes PayrollAutopay MimeJSON

-- | @application/json@
instance Produces PayrollAutopay MimeJSON


-- *** payrollCalculate

-- | @POST \/api\/v1\/payroll\/{id}\/calculate@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
payrollCalculate
  :: Id -- ^ "id"
  -> SimpleBillyRequest PayrollCalculate MimeNoContent PayrollRunApi MimeJSON
payrollCalculate (Id id) =
  _mkRequest "POST" ["/api/v1/payroll/",toPath id,"/calculate"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data PayrollCalculate  
-- | @application/json@
instance Produces PayrollCalculate MimeJSON


-- *** payrollCreate

-- | @POST \/api\/v1\/payroll@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
payrollCreate
  :: (Consumes PayrollCreate MimeJSON, MimeRender MimeJSON PayrollCreatePayload)
  => PayrollCreatePayload -- ^ "payrollCreatePayload"
  -> SimpleBillyRequest PayrollCreate MimeJSON PayrollRunApi MimeJSON
payrollCreate payrollCreatePayload =
  _mkRequest "POST" ["/api/v1/payroll"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` payrollCreatePayload

data PayrollCreate 
instance HasBodyParam PayrollCreate PayrollCreatePayload 

-- | @application/json@
instance Consumes PayrollCreate MimeJSON

-- | @application/json@
instance Produces PayrollCreate MimeJSON


-- *** payrollDelete

-- | @DELETE \/api\/v1\/payroll\/{id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
payrollDelete
  :: Id -- ^ "id"
  -> SimpleBillyRequest PayrollDelete MimeNoContent NoContent MimeNoContent
payrollDelete (Id id) =
  _mkRequest "DELETE" ["/api/v1/payroll/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data PayrollDelete  
instance Produces PayrollDelete MimeNoContent


-- *** payrollElsterExport

-- | @POST \/api\/v1\/payroll\/{id}\/elster-export@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
payrollElsterExport
  :: Id -- ^ "id"
  -> SimpleBillyRequest PayrollElsterExport MimeNoContent NoContent MimeNoContent
payrollElsterExport (Id id) =
  _mkRequest "POST" ["/api/v1/payroll/",toPath id,"/elster-export"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data PayrollElsterExport  
instance Produces PayrollElsterExport MimeNoContent


-- *** payrollEmail

-- | @POST \/api\/v1\/payroll\/{id}\/email@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
payrollEmail
  :: Id -- ^ "id"
  -> SimpleBillyRequest PayrollEmail MimeNoContent AnyType MimeJSON
payrollEmail (Id id) =
  _mkRequest "POST" ["/api/v1/payroll/",toPath id,"/email"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data PayrollEmail  
-- | @application/json@
instance Produces PayrollEmail MimeJSON


-- *** payrollEntryPdf

-- | @GET \/api\/v1\/payroll\/{id}\/entries\/{entry_id}\/pdf@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
payrollEntryPdf
  :: Id -- ^ "id"
  -> EntryId -- ^ "entryId"
  -> SimpleBillyRequest PayrollEntryPdf MimeNoContent NoContent MimeNoContent
payrollEntryPdf (Id id) (EntryId entryId) =
  _mkRequest "GET" ["/api/v1/payroll/",toPath id,"/entries/",toPath entryId,"/pdf"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data PayrollEntryPdf  
instance Produces PayrollEntryPdf MimeNoContent


-- *** payrollGet

-- | @GET \/api\/v1\/payroll\/{id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
payrollGet
  :: Id -- ^ "id"
  -> SimpleBillyRequest PayrollGet MimeNoContent PayrollRunApi MimeJSON
payrollGet (Id id) =
  _mkRequest "GET" ["/api/v1/payroll/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data PayrollGet  
-- | @application/json@
instance Produces PayrollGet MimeJSON


-- *** payrollList

-- | @GET \/api\/v1\/payroll@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
payrollList
  :: SimpleBillyRequest PayrollList MimeNoContent [PayrollRunApi] MimeJSON
payrollList =
  _mkRequest "GET" ["/api/v1/payroll"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data PayrollList  
instance HasOptionalParam PayrollList Year where
  applyOptionalParam req (Year xs) =
    req `addQuery` toQuery ("year", Just xs)
instance HasOptionalParam PayrollList Status where
  applyOptionalParam req (Status xs) =
    req `addQuery` toQuery ("status", Just xs)
-- | @application/json@
instance Produces PayrollList MimeJSON


-- *** payrollPay

-- | @POST \/api\/v1\/payroll\/{id}\/pay@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
payrollPay
  :: (Consumes PayrollPay MimeJSON, MimeRender MimeJSON PayrollPayPayload)
  => PayrollPayPayload -- ^ "payrollPayPayload"
  -> Id -- ^ "id"
  -> SimpleBillyRequest PayrollPay MimeJSON PayrollRunApi MimeJSON
payrollPay payrollPayPayload (Id id) =
  _mkRequest "POST" ["/api/v1/payroll/",toPath id,"/pay"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` payrollPayPayload

data PayrollPay 
instance HasBodyParam PayrollPay PayrollPayPayload 

-- | @application/json@
instance Consumes PayrollPay MimeJSON

-- | @application/json@
instance Produces PayrollPay MimeJSON


-- *** payrollPdf

-- | @GET \/api\/v1\/payroll\/{id}\/pdf@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
payrollPdf
  :: Id -- ^ "id"
  -> SimpleBillyRequest PayrollPdf MimeNoContent NoContent MimeNoContent
payrollPdf (Id id) =
  _mkRequest "GET" ["/api/v1/payroll/",toPath id,"/pdf"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data PayrollPdf  
instance Produces PayrollPdf MimeNoContent


-- *** payrollSummary0

-- | @GET \/api\/v1\/payroll\/summary\/{year}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
payrollSummary0
  :: Year -- ^ "year"
  -> SimpleBillyRequest PayrollSummary0 MimeNoContent YearlyPayrollSummary MimeJSON
payrollSummary0 (Year year) =
  _mkRequest "GET" ["/api/v1/payroll/summary/",toPath year]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data PayrollSummary0  
-- | @application/json@
instance Produces PayrollSummary0 MimeJSON


-- *** payrollSvMeldungen

-- | @POST \/api\/v1\/payroll\/{id}\/sv-meldungen@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
payrollSvMeldungen
  :: Id -- ^ "id"
  -> SimpleBillyRequest PayrollSvMeldungen MimeNoContent AnyType MimeJSON
payrollSvMeldungen (Id id) =
  _mkRequest "POST" ["/api/v1/payroll/",toPath id,"/sv-meldungen"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data PayrollSvMeldungen  
-- | @application/json@
instance Produces PayrollSvMeldungen MimeJSON

