{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.Pos
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.Pos where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Pos

-- *** posBilling

-- | @GET \/api\/pos\/billing@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
posBilling
  :: SimpleBillyRequest PosBilling MimeNoContent AnyType MimeJSON
posBilling =
  _mkRequest "GET" ["/api/pos/billing"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data PosBilling  
-- | @application/json@
instance Produces PosBilling MimeJSON


-- *** posCreateOrder

-- | @POST \/api\/pos\/orders@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
posCreateOrder
  :: (Consumes PosCreateOrder MimeJSON, MimeRender MimeJSON Body)
  => Body -- ^ "body"
  -> SimpleBillyRequest PosCreateOrder MimeJSON AnyType MimeJSON
posCreateOrder body =
  _mkRequest "POST" ["/api/pos/orders"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` body

data PosCreateOrder 
instance HasBodyParam PosCreateOrder Body 

-- | @application/json@
instance Consumes PosCreateOrder MimeJSON

-- | @application/json@
instance Produces PosCreateOrder MimeJSON


-- *** posCreateRegister

-- | @POST \/api\/pos\/registers@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
posCreateRegister
  :: (Consumes PosCreateRegister MimeJSON, MimeRender MimeJSON PosRegisterCreate)
  => PosRegisterCreate -- ^ "posRegisterCreate"
  -> SimpleBillyRequest PosCreateRegister MimeJSON PosRegister MimeJSON
posCreateRegister posRegisterCreate =
  _mkRequest "POST" ["/api/pos/registers"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` posRegisterCreate

data PosCreateRegister 
instance HasBodyParam PosCreateRegister PosRegisterCreate 

-- | @application/json@
instance Consumes PosCreateRegister MimeJSON

-- | @application/json@
instance Produces PosCreateRegister MimeJSON


-- *** posCreateTable

-- | @POST \/api\/pos\/tables@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
posCreateTable
  :: (Consumes PosCreateTable MimeJSON, MimeRender MimeJSON PosTableCreate)
  => PosTableCreate -- ^ "posTableCreate"
  -> SimpleBillyRequest PosCreateTable MimeJSON PosTable MimeJSON
posCreateTable posTableCreate =
  _mkRequest "POST" ["/api/pos/tables"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` posTableCreate

data PosCreateTable 
instance HasBodyParam PosCreateTable PosTableCreate 

-- | @application/json@
instance Consumes PosCreateTable MimeJSON

-- | @application/json@
instance Produces PosCreateTable MimeJSON


-- *** posDisableRegister

-- | @POST \/api\/pos\/registers\/{id}\/disable@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
posDisableRegister
  :: Id -- ^ "id"
  -> SimpleBillyRequest PosDisableRegister MimeNoContent PosRegister MimeJSON
posDisableRegister (Id id) =
  _mkRequest "POST" ["/api/pos/registers/",toPath id,"/disable"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data PosDisableRegister  
-- | @application/json@
instance Produces PosDisableRegister MimeJSON


-- *** posFreeTable

-- | @POST \/api\/pos\/tables\/{id}\/free@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
posFreeTable
  :: Id -- ^ "id"
  -> SimpleBillyRequest PosFreeTable MimeNoContent PosTable MimeJSON
posFreeTable (Id id) =
  _mkRequest "POST" ["/api/pos/tables/",toPath id,"/free"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data PosFreeTable  
-- | @application/json@
instance Produces PosFreeTable MimeJSON


-- *** posKasseClosing

-- | @POST \/api\/pos\/kasse\/closing@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
posKasseClosing
  :: (Consumes PosKasseClosing MimeJSON, MimeRender MimeJSON Body)
  => Body -- ^ "body"
  -> SimpleBillyRequest PosKasseClosing MimeJSON AnyType MimeJSON
posKasseClosing body =
  _mkRequest "POST" ["/api/pos/kasse/closing"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` body

data PosKasseClosing 
instance HasBodyParam PosKasseClosing Body 

-- | @application/json@
instance Consumes PosKasseClosing MimeJSON

-- | @application/json@
instance Produces PosKasseClosing MimeJSON


-- *** posKasseEntries

-- | @GET \/api\/pos\/kasse\/entries@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
posKasseEntries
  :: SimpleBillyRequest PosKasseEntries MimeNoContent AnyType MimeJSON
posKasseEntries =
  _mkRequest "GET" ["/api/pos/kasse/entries"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data PosKasseEntries  
-- | @application/json@
instance Produces PosKasseEntries MimeJSON


-- *** posKasseExport

-- | @GET \/api\/pos\/kasse\/export@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
posKasseExport
  :: SimpleBillyRequest PosKasseExport MimeNoContent AnyType MimeJSON
posKasseExport =
  _mkRequest "GET" ["/api/pos/kasse/export"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data PosKasseExport  
-- | @application/json@
instance Produces PosKasseExport MimeJSON


-- *** posKassePayInOut

-- | @POST \/api\/pos\/kasse\/pay-in-out@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
posKassePayInOut
  :: (Consumes PosKassePayInOut MimeJSON, MimeRender MimeJSON Body)
  => Body -- ^ "body"
  -> SimpleBillyRequest PosKassePayInOut MimeJSON AnyType MimeJSON
posKassePayInOut body =
  _mkRequest "POST" ["/api/pos/kasse/pay-in-out"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` body

data PosKassePayInOut 
instance HasBodyParam PosKassePayInOut Body 

-- | @application/json@
instance Consumes PosKassePayInOut MimeJSON

-- | @application/json@
instance Produces PosKassePayInOut MimeJSON


-- *** posListOrders

-- | @GET \/api\/pos\/orders@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
posListOrders
  :: SimpleBillyRequest PosListOrders MimeNoContent AnyType MimeJSON
posListOrders =
  _mkRequest "GET" ["/api/pos/orders"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data PosListOrders  

-- | /Optional Param/ "status" - Filter by order status
instance HasOptionalParam PosListOrders Status where
  applyOptionalParam req (Status xs) =
    req `addQuery` toQuery ("status", Just xs)
-- | @application/json@
instance Produces PosListOrders MimeJSON


-- *** posListProducts

-- | @GET \/api\/pos\/products@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
posListProducts
  :: SimpleBillyRequest PosListProducts MimeNoContent AnyType MimeJSON
posListProducts =
  _mkRequest "GET" ["/api/pos/products"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data PosListProducts  

-- | /Optional Param/ "q" - Product search
instance HasOptionalParam PosListProducts Q where
  applyOptionalParam req (Q xs) =
    req `addQuery` toQuery ("q", Just xs)
-- | @application/json@
instance Produces PosListProducts MimeJSON


-- *** posListRegisters

-- | @GET \/api\/pos\/registers@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
posListRegisters
  :: SimpleBillyRequest PosListRegisters MimeNoContent [PosRegister] MimeJSON
posListRegisters =
  _mkRequest "GET" ["/api/pos/registers"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data PosListRegisters  
-- | @application/json@
instance Produces PosListRegisters MimeJSON


-- *** posListTables

-- | @GET \/api\/pos\/tables@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
posListTables
  :: SimpleBillyRequest PosListTables MimeNoContent [PosTable] MimeJSON
posListTables =
  _mkRequest "GET" ["/api/pos/tables"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data PosListTables  
-- | @application/json@
instance Produces PosListTables MimeJSON


-- *** posOrderPrint

-- | @GET \/api\/pos\/orders\/{order_number}\/print@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
posOrderPrint
  :: OrderNumber -- ^ "orderNumber"
  -> SimpleBillyRequest PosOrderPrint MimeNoContent AnyType MimeJSON
posOrderPrint (OrderNumber orderNumber) =
  _mkRequest "GET" ["/api/pos/orders/",toPath orderNumber,"/print"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data PosOrderPrint  
-- | @application/json@
instance Produces PosOrderPrint MimeJSON


-- *** posOrderReceipt

-- | @GET \/api\/pos\/orders\/{order_number}\/receipt@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
posOrderReceipt
  :: OrderNumber -- ^ "orderNumber"
  -> SimpleBillyRequest PosOrderReceipt MimeNoContent AnyType MimeJSON
posOrderReceipt (OrderNumber orderNumber) =
  _mkRequest "GET" ["/api/pos/orders/",toPath orderNumber,"/receipt"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data PosOrderReceipt  
-- | @application/json@
instance Produces PosOrderReceipt MimeJSON


-- *** posPayOrder

-- | @POST \/api\/pos\/orders\/{order_number}\/pay@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
posPayOrder
  :: (Consumes PosPayOrder MimeJSON, MimeRender MimeJSON Body)
  => Body -- ^ "body"
  -> OrderNumber -- ^ "orderNumber"
  -> SimpleBillyRequest PosPayOrder MimeJSON AnyType MimeJSON
posPayOrder body (OrderNumber orderNumber) =
  _mkRequest "POST" ["/api/pos/orders/",toPath orderNumber,"/pay"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` body

data PosPayOrder 
instance HasBodyParam PosPayOrder Body 

-- | @application/json@
instance Consumes PosPayOrder MimeJSON

-- | @application/json@
instance Produces PosPayOrder MimeJSON


-- *** posSumupCheckout

-- | @POST \/api\/pos\/sumup\/checkout@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
posSumupCheckout
  :: (Consumes PosSumupCheckout MimeJSON, MimeRender MimeJSON Body)
  => Body -- ^ "body"
  -> SimpleBillyRequest PosSumupCheckout MimeJSON AnyType MimeJSON
posSumupCheckout body =
  _mkRequest "POST" ["/api/pos/sumup/checkout"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` body

data PosSumupCheckout 
instance HasBodyParam PosSumupCheckout Body 

-- | @application/json@
instance Consumes PosSumupCheckout MimeJSON

-- | @application/json@
instance Produces PosSumupCheckout MimeJSON

