{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.PostingCategory
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.PostingCategory where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** PostingCategory

-- *** createPostingCategory

-- | @POST \/api\/v1\/posting-categories@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createPostingCategory
  :: (Consumes CreatePostingCategory MimeJSON, MimeRender MimeJSON Body)
  => Body -- ^ "body"
  -> SimpleBillyRequest CreatePostingCategory MimeJSON PostingCategory MimeJSON
createPostingCategory body =
  _mkRequest "POST" ["/api/v1/posting-categories"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` body

data CreatePostingCategory 
instance HasBodyParam CreatePostingCategory Body 

-- | @application/json@
instance Consumes CreatePostingCategory MimeJSON

-- | @application/json@
instance Produces CreatePostingCategory MimeJSON


-- *** deletePostingCategory

-- | @DELETE \/api\/v1\/posting-categories\/{category_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deletePostingCategory
  :: CategoryId -- ^ "categoryId"
  -> SimpleBillyRequest DeletePostingCategory MimeNoContent NoContent MimeNoContent
deletePostingCategory (CategoryId categoryId) =
  _mkRequest "DELETE" ["/api/v1/posting-categories/",toPath categoryId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeletePostingCategory  
instance Produces DeletePostingCategory MimeNoContent


-- *** listPostingCategories

-- | @GET \/api\/v1\/posting-categories@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listPostingCategories
  :: SimpleBillyRequest ListPostingCategories MimeNoContent [PostingCategory] MimeJSON
listPostingCategories =
  _mkRequest "GET" ["/api/v1/posting-categories"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListPostingCategories  
-- | @application/json@
instance Produces ListPostingCategories MimeJSON


-- *** seedPostingCategories

-- | @POST \/api\/v1\/posting-categories\/seed\/{skr_version}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
seedPostingCategories
  :: SkrVersion -- ^ "skrVersion"
  -> SimpleBillyRequest SeedPostingCategories MimeNoContent NoContent MimeNoContent
seedPostingCategories (SkrVersion skrVersion) =
  _mkRequest "POST" ["/api/v1/posting-categories/seed/",toPath skrVersion]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data SeedPostingCategories  
instance Produces SeedPostingCategories MimeNoContent


-- *** updatePostingCategory

-- | @PUT \/api\/v1\/posting-categories\/{category_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updatePostingCategory
  :: (Consumes UpdatePostingCategory MimeJSON, MimeRender MimeJSON Body)
  => Body -- ^ "body"
  -> CategoryId -- ^ "categoryId"
  -> SimpleBillyRequest UpdatePostingCategory MimeJSON PostingCategory MimeJSON
updatePostingCategory body (CategoryId categoryId) =
  _mkRequest "PUT" ["/api/v1/posting-categories/",toPath categoryId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` body

data UpdatePostingCategory 
instance HasBodyParam UpdatePostingCategory Body 

-- | @application/json@
instance Consumes UpdatePostingCategory MimeJSON

-- | @application/json@
instance Produces UpdatePostingCategory MimeJSON

