{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.PriceTier
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.PriceTier where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** PriceTier

-- *** createPriceTier

-- | @POST \/api\/v1\/price-tiers@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createPriceTier
  :: (Consumes CreatePriceTier MimeJSON, MimeRender MimeJSON PriceTierCreate)
  => PriceTierCreate -- ^ "priceTierCreate"
  -> SimpleBillyRequest CreatePriceTier MimeJSON PriceTier MimeJSON
createPriceTier priceTierCreate =
  _mkRequest "POST" ["/api/v1/price-tiers"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` priceTierCreate

data CreatePriceTier 
instance HasBodyParam CreatePriceTier PriceTierCreate 

-- | @application/json@
instance Consumes CreatePriceTier MimeJSON

-- | @application/json@
instance Produces CreatePriceTier MimeJSON


-- *** deletePriceTier

-- | @DELETE \/api\/v1\/price-tiers\/{price_tier_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deletePriceTier
  :: PriceTierId -- ^ "priceTierId"
  -> SimpleBillyRequest DeletePriceTier MimeNoContent NoContent MimeNoContent
deletePriceTier (PriceTierId priceTierId) =
  _mkRequest "DELETE" ["/api/v1/price-tiers/",toPath priceTierId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeletePriceTier  
instance Produces DeletePriceTier MimeNoContent


-- *** getPriceTier

-- | @GET \/api\/v1\/price-tiers\/{price_tier_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getPriceTier
  :: PriceTierId -- ^ "priceTierId"
  -> SimpleBillyRequest GetPriceTier MimeNoContent PriceTier MimeJSON
getPriceTier (PriceTierId priceTierId) =
  _mkRequest "GET" ["/api/v1/price-tiers/",toPath priceTierId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetPriceTier  
-- | @application/json@
instance Produces GetPriceTier MimeJSON


-- *** getResolvedPrice

-- | @GET \/api\/v1\/price-tiers\/resolved@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getResolvedPrice
  :: ProductId -- ^ "productId"
  -> SimpleBillyRequest GetResolvedPrice MimeNoContent ResolvedPriceResponse MimeJSON
getResolvedPrice (ProductId productId) =
  _mkRequest "GET" ["/api/v1/price-tiers/resolved"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `addQuery` toQuery ("productId", Just productId)

data GetResolvedPrice  
instance HasOptionalParam GetResolvedPrice Quantity where
  applyOptionalParam req (Quantity xs) =
    req `addQuery` toQuery ("quantity", Just xs)

-- | /Optional Param/ "contactId" - Contact used to match customer-group-scoped tiers.
instance HasOptionalParam GetResolvedPrice ContactId where
  applyOptionalParam req (ContactId xs) =
    req `addQuery` toQuery ("contactId", Just xs)
-- | @application/json@
instance Produces GetResolvedPrice MimeJSON


-- *** listPriceTiers

-- | @GET \/api\/v1\/price-tiers\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listPriceTiers
  :: SimpleBillyRequest ListPriceTiers MimeNoContent [PriceTier] MimeJSON
listPriceTiers =
  _mkRequest "GET" ["/api/v1/price-tiers/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListPriceTiers  
instance HasOptionalParam ListPriceTiers Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam ListPriceTiers PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam ListPriceTiers ProductId where
  applyOptionalParam req (ProductId xs) =
    req `addQuery` toQuery ("product_id", Just xs)
instance HasOptionalParam ListPriceTiers CustomerGroupId where
  applyOptionalParam req (CustomerGroupId xs) =
    req `addQuery` toQuery ("customer_group_id", Just xs)
-- | @application/json@
instance Produces ListPriceTiers MimeJSON


-- *** updatePriceTier

-- | @PUT \/api\/v1\/price-tiers\/{price_tier_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updatePriceTier
  :: (Consumes UpdatePriceTier MimeJSON, MimeRender MimeJSON PriceTierUpdate)
  => PriceTierUpdate -- ^ "priceTierUpdate"
  -> PriceTierId -- ^ "priceTierId"
  -> SimpleBillyRequest UpdatePriceTier MimeJSON PriceTier MimeJSON
updatePriceTier priceTierUpdate (PriceTierId priceTierId) =
  _mkRequest "PUT" ["/api/v1/price-tiers/",toPath priceTierId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` priceTierUpdate

data UpdatePriceTier 
instance HasBodyParam UpdatePriceTier PriceTierUpdate 

-- | @application/json@
instance Consumes UpdatePriceTier MimeJSON

-- | @application/json@
instance Produces UpdatePriceTier MimeJSON

