{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.ProductVariant
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.ProductVariant where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** ProductVariant

-- *** createProductVariant

-- | @POST \/api\/v1\/product-variants@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createProductVariant
  :: (Consumes CreateProductVariant MimeJSON, MimeRender MimeJSON ProductVariant)
  => ProductVariant -- ^ "productVariant"
  -> SimpleBillyRequest CreateProductVariant MimeJSON ProductVariant MimeJSON
createProductVariant productVariant =
  _mkRequest "POST" ["/api/v1/product-variants"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` productVariant

data CreateProductVariant 
instance HasBodyParam CreateProductVariant ProductVariant 

-- | @application/json@
instance Consumes CreateProductVariant MimeJSON

-- | @application/json@
instance Produces CreateProductVariant MimeJSON


-- *** deleteProductVariant

-- | @DELETE \/api\/v1\/product-variants\/{variant_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteProductVariant
  :: VariantId -- ^ "variantId"
  -> SimpleBillyRequest DeleteProductVariant MimeNoContent NoContent MimeNoContent
deleteProductVariant (VariantId variantId) =
  _mkRequest "DELETE" ["/api/v1/product-variants/",toPath variantId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteProductVariant  
instance Produces DeleteProductVariant MimeNoContent


-- *** generateProductVariants

-- | @POST \/api\/v1\/product-variants\/generate@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
generateProductVariants
  :: (Consumes GenerateProductVariants MimeJSON, MimeRender MimeJSON GenerateVariantsRequest)
  => GenerateVariantsRequest -- ^ "generateVariantsRequest"
  -> SimpleBillyRequest GenerateProductVariants MimeJSON [ProductVariant] MimeJSON
generateProductVariants generateVariantsRequest =
  _mkRequest "POST" ["/api/v1/product-variants/generate"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` generateVariantsRequest

data GenerateProductVariants 
instance HasBodyParam GenerateProductVariants GenerateVariantsRequest 

-- | @application/json@
instance Consumes GenerateProductVariants MimeJSON

-- | @application/json@
instance Produces GenerateProductVariants MimeJSON


-- *** getProductVariant

-- | @GET \/api\/v1\/product-variants\/{variant_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getProductVariant
  :: VariantId -- ^ "variantId"
  -> SimpleBillyRequest GetProductVariant MimeNoContent ProductVariant MimeJSON
getProductVariant (VariantId variantId) =
  _mkRequest "GET" ["/api/v1/product-variants/",toPath variantId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetProductVariant  
-- | @application/json@
instance Produces GetProductVariant MimeJSON


-- *** listProductVariants

-- | @GET \/api\/v1\/product-variants\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listProductVariants
  :: SimpleBillyRequest ListProductVariants MimeNoContent [ProductVariant] MimeJSON
listProductVariants =
  _mkRequest "GET" ["/api/v1/product-variants/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListProductVariants  
instance HasOptionalParam ListProductVariants Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam ListProductVariants PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam ListProductVariants ProductId where
  applyOptionalParam req (ProductId xs) =
    req `addQuery` toQuery ("product_id", Just xs)
instance HasOptionalParam ListProductVariants IsActive where
  applyOptionalParam req (IsActive xs) =
    req `addQuery` toQuery ("is_active", Just xs)
-- | @application/json@
instance Produces ListProductVariants MimeJSON


-- *** updateProductVariant

-- | @PUT \/api\/v1\/product-variants\/{variant_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateProductVariant
  :: (Consumes UpdateProductVariant MimeJSON, MimeRender MimeJSON Body)
  => Body -- ^ "body"
  -> VariantId -- ^ "variantId"
  -> SimpleBillyRequest UpdateProductVariant MimeJSON ProductVariant MimeJSON
updateProductVariant body (VariantId variantId) =
  _mkRequest "PUT" ["/api/v1/product-variants/",toPath variantId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` body

data UpdateProductVariant 
instance HasBodyParam UpdateProductVariant Body 

-- | @application/json@
instance Consumes UpdateProductVariant MimeJSON

-- | @application/json@
instance Produces UpdateProductVariant MimeJSON

