{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.ProductCategory
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.ProductCategory where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** ProductCategory

-- *** createProductCategory

-- | @POST \/api\/v1\/product-categories@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createProductCategory
  :: (Consumes CreateProductCategory MimeJSON, MimeRender MimeJSON ProductCategory)
  => ProductCategory -- ^ "productCategory"
  -> SimpleBillyRequest CreateProductCategory MimeJSON ProductCategory MimeJSON
createProductCategory productCategory =
  _mkRequest "POST" ["/api/v1/product-categories"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` productCategory

data CreateProductCategory 
instance HasBodyParam CreateProductCategory ProductCategory 

-- | @application/json@
instance Consumes CreateProductCategory MimeJSON

-- | @application/json@
instance Produces CreateProductCategory MimeJSON


-- *** deleteProductCategory

-- | @DELETE \/api\/v1\/product-categories\/{category_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteProductCategory
  :: CategoryId -- ^ "categoryId"
  -> SimpleBillyRequest DeleteProductCategory MimeNoContent NoContent MimeNoContent
deleteProductCategory (CategoryId categoryId) =
  _mkRequest "DELETE" ["/api/v1/product-categories/",toPath categoryId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteProductCategory  
instance Produces DeleteProductCategory MimeNoContent


-- *** getProductCategory

-- | @GET \/api\/v1\/product-categories\/{category_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getProductCategory
  :: CategoryId -- ^ "categoryId"
  -> SimpleBillyRequest GetProductCategory MimeNoContent ProductCategory MimeJSON
getProductCategory (CategoryId categoryId) =
  _mkRequest "GET" ["/api/v1/product-categories/",toPath categoryId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetProductCategory  
-- | @application/json@
instance Produces GetProductCategory MimeJSON


-- *** listProductCategories

-- | @GET \/api\/v1\/product-categories@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listProductCategories
  :: SimpleBillyRequest ListProductCategories MimeNoContent [ProductCategory] MimeJSON
listProductCategories =
  _mkRequest "GET" ["/api/v1/product-categories"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListProductCategories  
-- | @application/json@
instance Produces ListProductCategories MimeJSON


-- *** updateProductCategory

-- | @PUT \/api\/v1\/product-categories\/{category_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateProductCategory
  :: (Consumes UpdateProductCategory MimeJSON, MimeRender MimeJSON Body)
  => Body -- ^ "body"
  -> CategoryId -- ^ "categoryId"
  -> SimpleBillyRequest UpdateProductCategory MimeJSON ProductCategory MimeJSON
updateProductCategory body (CategoryId categoryId) =
  _mkRequest "PUT" ["/api/v1/product-categories/",toPath categoryId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` body

data UpdateProductCategory 
instance HasBodyParam UpdateProductCategory Body 

-- | @application/json@
instance Consumes UpdateProductCategory MimeJSON

-- | @application/json@
instance Produces UpdateProductCategory MimeJSON

