{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.ProductAttribute
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.ProductAttribute where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** ProductAttribute

-- *** createProductAttribute

-- | @POST \/api\/v1\/product-attributes@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createProductAttribute
  :: (Consumes CreateProductAttribute MimeJSON, MimeRender MimeJSON ProductAttributeCreate)
  => ProductAttributeCreate -- ^ "productAttributeCreate"
  -> SimpleBillyRequest CreateProductAttribute MimeJSON ProductAttribute MimeJSON
createProductAttribute productAttributeCreate =
  _mkRequest "POST" ["/api/v1/product-attributes"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` productAttributeCreate

data CreateProductAttribute 
instance HasBodyParam CreateProductAttribute ProductAttributeCreate 

-- | @application/json@
instance Consumes CreateProductAttribute MimeJSON

-- | @application/json@
instance Produces CreateProductAttribute MimeJSON


-- *** deleteProductAttribute

-- | @DELETE \/api\/v1\/product-attributes\/{attribute_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteProductAttribute
  :: AttributeId -- ^ "attributeId"
  -> SimpleBillyRequest DeleteProductAttribute MimeNoContent NoContent MimeNoContent
deleteProductAttribute (AttributeId attributeId) =
  _mkRequest "DELETE" ["/api/v1/product-attributes/",toPath attributeId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteProductAttribute  
instance Produces DeleteProductAttribute MimeNoContent


-- *** getProductAttribute

-- | @GET \/api\/v1\/product-attributes\/{attribute_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getProductAttribute
  :: AttributeId -- ^ "attributeId"
  -> SimpleBillyRequest GetProductAttribute MimeNoContent ProductAttribute MimeJSON
getProductAttribute (AttributeId attributeId) =
  _mkRequest "GET" ["/api/v1/product-attributes/",toPath attributeId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetProductAttribute  
-- | @application/json@
instance Produces GetProductAttribute MimeJSON


-- *** listProductAttributes

-- | @GET \/api\/v1\/product-attributes\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listProductAttributes
  :: SimpleBillyRequest ListProductAttributes MimeNoContent [ProductAttribute] MimeJSON
listProductAttributes =
  _mkRequest "GET" ["/api/v1/product-attributes/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListProductAttributes  
instance HasOptionalParam ListProductAttributes Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam ListProductAttributes PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam ListProductAttributes ProductId where
  applyOptionalParam req (ProductId xs) =
    req `addQuery` toQuery ("product_id", Just xs)
instance HasOptionalParam ListProductAttributes IsFilterable where
  applyOptionalParam req (IsFilterable xs) =
    req `addQuery` toQuery ("is_filterable", Just xs)
instance HasOptionalParam ListProductAttributes Search where
  applyOptionalParam req (Search xs) =
    req `addQuery` toQuery ("search", Just xs)
-- | @application/json@
instance Produces ListProductAttributes MimeJSON


-- *** updateProductAttribute

-- | @PUT \/api\/v1\/product-attributes\/{attribute_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateProductAttribute
  :: (Consumes UpdateProductAttribute MimeJSON, MimeRender MimeJSON ProductAttributeUpdate)
  => ProductAttributeUpdate -- ^ "productAttributeUpdate"
  -> AttributeId -- ^ "attributeId"
  -> SimpleBillyRequest UpdateProductAttribute MimeJSON ProductAttribute MimeJSON
updateProductAttribute productAttributeUpdate (AttributeId attributeId) =
  _mkRequest "PUT" ["/api/v1/product-attributes/",toPath attributeId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` productAttributeUpdate

data UpdateProductAttribute 
instance HasBodyParam UpdateProductAttribute ProductAttributeUpdate 

-- | @application/json@
instance Consumes UpdateProductAttribute MimeJSON

-- | @application/json@
instance Produces UpdateProductAttribute MimeJSON

