{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.ProductionOrder
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.ProductionOrder where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** ProductionOrder

-- *** createProductionOrder

-- | @POST \/api\/v1\/production-orders@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createProductionOrder
  :: (Consumes CreateProductionOrder MimeJSON, MimeRender MimeJSON ProductionOrder)
  => ProductionOrder -- ^ "productionOrder"
  -> SimpleBillyRequest CreateProductionOrder MimeJSON ProductionOrder MimeJSON
createProductionOrder productionOrder =
  _mkRequest "POST" ["/api/v1/production-orders"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` productionOrder

data CreateProductionOrder 
instance HasBodyParam CreateProductionOrder ProductionOrder 

-- | @application/json@
instance Consumes CreateProductionOrder MimeJSON

-- | @application/json@
instance Produces CreateProductionOrder MimeJSON


-- *** deleteProductionOrder

-- | @DELETE \/api\/v1\/production-orders\/{production_order_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteProductionOrder
  :: ProductionOrderId -- ^ "productionOrderId"
  -> SimpleBillyRequest DeleteProductionOrder MimeNoContent NoContent MimeNoContent
deleteProductionOrder (ProductionOrderId productionOrderId) =
  _mkRequest "DELETE" ["/api/v1/production-orders/",toPath productionOrderId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteProductionOrder  
instance Produces DeleteProductionOrder MimeNoContent


-- *** getProductionOrder

-- | @GET \/api\/v1\/production-orders\/{production_order_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getProductionOrder
  :: ProductionOrderId -- ^ "productionOrderId"
  -> SimpleBillyRequest GetProductionOrder MimeNoContent ProductionOrder MimeJSON
getProductionOrder (ProductionOrderId productionOrderId) =
  _mkRequest "GET" ["/api/v1/production-orders/",toPath productionOrderId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetProductionOrder  
-- | @application/json@
instance Produces GetProductionOrder MimeJSON


-- *** listProductionOrders

-- | @GET \/api\/v1\/production-orders\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listProductionOrders
  :: SimpleBillyRequest ListProductionOrders MimeNoContent [ProductionOrder] MimeJSON
listProductionOrders =
  _mkRequest "GET" ["/api/v1/production-orders/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListProductionOrders  
instance HasOptionalParam ListProductionOrders Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam ListProductionOrders PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("pageSize", Just xs)
instance HasOptionalParam ListProductionOrders Search where
  applyOptionalParam req (Search xs) =
    req `addQuery` toQuery ("search", Just xs)

-- | /Optional Param/ "status" - Filter by status.
instance HasOptionalParam ListProductionOrders Status where
  applyOptionalParam req (Status xs) =
    req `addQuery` toQuery ("status", Just xs)
-- | @application/json@
instance Produces ListProductionOrders MimeJSON


-- *** productionOrderCosting0

-- | @GET \/api\/v1\/production-orders\/{production_order_id}\/costing@
-- 
-- Actual-costing report (Nachkalkulation) — material costs from BOM components at their purchase price plus the resulting per-unit cost and margin against the finished product's sale price.
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
productionOrderCosting0
  :: ProductionOrderId -- ^ "productionOrderId"
  -> SimpleBillyRequest ProductionOrderCosting0 MimeNoContent ProductionOrderCosting MimeJSON
productionOrderCosting0 (ProductionOrderId productionOrderId) =
  _mkRequest "GET" ["/api/v1/production-orders/",toPath productionOrderId,"/costing"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ProductionOrderCosting0  
-- | @application/json@
instance Produces ProductionOrderCosting0 MimeJSON


-- *** updateProductionOrder

-- | @PUT \/api\/v1\/production-orders\/{production_order_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateProductionOrder
  :: (Consumes UpdateProductionOrder MimeJSON, MimeRender MimeJSON ProductionOrder)
  => ProductionOrder -- ^ "productionOrder"
  -> ProductionOrderId -- ^ "productionOrderId"
  -> SimpleBillyRequest UpdateProductionOrder MimeJSON ProductionOrder MimeJSON
updateProductionOrder productionOrder (ProductionOrderId productionOrderId) =
  _mkRequest "PUT" ["/api/v1/production-orders/",toPath productionOrderId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` productionOrder

data UpdateProductionOrder 
instance HasBodyParam UpdateProductionOrder ProductionOrder 

-- | @application/json@
instance Consumes UpdateProductionOrder MimeJSON

-- | @application/json@
instance Produces UpdateProductionOrder MimeJSON


-- *** updateProductionOrderStatus

-- | @PUT \/api\/v1\/production-orders\/{production_order_id}\/status@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateProductionOrderStatus
  :: (Consumes UpdateProductionOrderStatus MimeJSON, MimeRender MimeJSON ProductionOrderStatusUpdate)
  => ProductionOrderStatusUpdate -- ^ "productionOrderStatusUpdate"
  -> ProductionOrderId -- ^ "productionOrderId"
  -> SimpleBillyRequest UpdateProductionOrderStatus MimeJSON ProductionOrder MimeJSON
updateProductionOrderStatus productionOrderStatusUpdate (ProductionOrderId productionOrderId) =
  _mkRequest "PUT" ["/api/v1/production-orders/",toPath productionOrderId,"/status"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` productionOrderStatusUpdate

data UpdateProductionOrderStatus 
instance HasBodyParam UpdateProductionOrderStatus ProductionOrderStatusUpdate 

-- | @application/json@
instance Consumes UpdateProductionOrderStatus MimeJSON

-- | @application/json@
instance Produces UpdateProductionOrderStatus MimeJSON

