{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.Product
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.Product where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Product

-- *** createProductApi

-- | @POST \/api\/v1\/products@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createProductApi
  :: (Consumes CreateProductApi MimeJSON, MimeRender MimeJSON ProductCreate)
  => ProductCreate -- ^ "productCreate"
  -> SimpleBillyRequest CreateProductApi MimeJSON Product MimeJSON
createProductApi productCreate =
  _mkRequest "POST" ["/api/v1/products"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` productCreate

data CreateProductApi 
instance HasBodyParam CreateProductApi ProductCreate 

-- | @application/json@
instance Consumes CreateProductApi MimeJSON

-- | @application/json@
instance Produces CreateProductApi MimeJSON


-- *** deleteProductApi

-- | @DELETE \/api\/v1\/products\/{product_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteProductApi
  :: ProductId -- ^ "productId"
  -> SimpleBillyRequest DeleteProductApi MimeNoContent NoContent MimeNoContent
deleteProductApi (ProductId productId) =
  _mkRequest "DELETE" ["/api/v1/products/",toPath productId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteProductApi  
instance Produces DeleteProductApi MimeNoContent


-- *** getProductApi

-- | @GET \/api\/v1\/products\/{product_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getProductApi
  :: ProductId -- ^ "productId"
  -> SimpleBillyRequest GetProductApi MimeNoContent Product MimeJSON
getProductApi (ProductId productId) =
  _mkRequest "GET" ["/api/v1/products/",toPath productId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetProductApi  
-- | @application/json@
instance Produces GetProductApi MimeJSON


-- *** getProductStockApi

-- | @GET \/api\/v1\/products\/{product_id}\/stock@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getProductStockApi
  :: ProductId -- ^ "productId"
  -> SimpleBillyRequest GetProductStockApi MimeNoContent ProductStock MimeJSON
getProductStockApi (ProductId productId) =
  _mkRequest "GET" ["/api/v1/products/",toPath productId,"/stock"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetProductStockApi  
-- | @application/json@
instance Produces GetProductStockApi MimeJSON


-- *** getProductsApi

-- | @GET \/api\/v1\/products\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getProductsApi
  :: SimpleBillyRequest GetProductsApi MimeNoContent [Product] MimeJSON
getProductsApi =
  _mkRequest "GET" ["/api/v1/products/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetProductsApi  
instance HasOptionalParam GetProductsApi Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam GetProductsApi PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam GetProductsApi Search where
  applyOptionalParam req (Search xs) =
    req `addQuery` toQuery ("search", Just xs)

-- | /Optional Param/ "include_deleted" - Soft-delete entities: set true to include rows with `deleted_at` set.
instance HasOptionalParam GetProductsApi IncludeDeleted where
  applyOptionalParam req (IncludeDeleted xs) =
    req `addQuery` toQuery ("include_deleted", Just xs)
-- | @application/json@
instance Produces GetProductsApi MimeJSON


-- *** listLowStockProductsApi

-- | @GET \/api\/v1\/products\/low-stock@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listLowStockProductsApi
  :: SimpleBillyRequest ListLowStockProductsApi MimeNoContent [ProductStock] MimeJSON
listLowStockProductsApi =
  _mkRequest "GET" ["/api/v1/products/low-stock"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListLowStockProductsApi  
instance HasOptionalParam ListLowStockProductsApi Threshold where
  applyOptionalParam req (Threshold xs) =
    req `addQuery` toQuery ("threshold", Just xs)
-- | @application/json@
instance Produces ListLowStockProductsApi MimeJSON


-- *** productRestore

-- | @POST \/api\/v1\/products\/{product_id}\/restore@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
productRestore
  :: ProductId -- ^ "productId"
  -> SimpleBillyRequest ProductRestore MimeNoContent Product MimeJSON
productRestore (ProductId productId) =
  _mkRequest "POST" ["/api/v1/products/",toPath productId,"/restore"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ProductRestore  
-- | @application/json@
instance Produces ProductRestore MimeJSON


-- *** updateProductApi

-- | @PUT \/api\/v1\/products\/{product_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateProductApi
  :: (Consumes UpdateProductApi MimeJSON, MimeRender MimeJSON ProductUpdate)
  => ProductUpdate -- ^ "productUpdate"
  -> ProductId -- ^ "productId"
  -> SimpleBillyRequest UpdateProductApi MimeJSON Product MimeJSON
updateProductApi productUpdate (ProductId productId) =
  _mkRequest "PUT" ["/api/v1/products/",toPath productId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` productUpdate

data UpdateProductApi 
instance HasBodyParam UpdateProductApi ProductUpdate 

-- | @application/json@
instance Consumes UpdateProductApi MimeJSON

-- | @application/json@
instance Produces UpdateProductApi MimeJSON


-- *** updateProductStockApi

-- | @PUT \/api\/v1\/products\/{product_id}\/stock@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateProductStockApi
  :: (Consumes UpdateProductStockApi MimeJSON, MimeRender MimeJSON StockUpdateRequest)
  => StockUpdateRequest -- ^ "stockUpdateRequest"
  -> ProductId -- ^ "productId"
  -> SimpleBillyRequest UpdateProductStockApi MimeJSON ProductStock MimeJSON
updateProductStockApi stockUpdateRequest (ProductId productId) =
  _mkRequest "PUT" ["/api/v1/products/",toPath productId,"/stock"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` stockUpdateRequest

data UpdateProductStockApi 
instance HasBodyParam UpdateProductStockApi StockUpdateRequest 

-- | @application/json@
instance Consumes UpdateProductStockApi MimeJSON

-- | @application/json@
instance Produces UpdateProductStockApi MimeJSON

