{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.ProformaInvoice
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.ProformaInvoice where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** ProformaInvoice

-- *** convertProformaToInvoice

-- | @POST \/api\/v1\/proforma-invoices\/{proforma_id}\/convert@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
convertProformaToInvoice
  :: ProformaId -- ^ "proformaId"
  -> SimpleBillyRequest ConvertProformaToInvoice MimeNoContent ConvertResponse MimeJSON
convertProformaToInvoice (ProformaId proformaId) =
  _mkRequest "POST" ["/api/v1/proforma-invoices/",toPath proformaId,"/convert"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ConvertProformaToInvoice  
-- | @application/json@
instance Produces ConvertProformaToInvoice MimeJSON


-- *** createProformaInvoice

-- | @POST \/api\/v1\/proforma-invoices@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createProformaInvoice
  :: (Consumes CreateProformaInvoice MimeJSON, MimeRender MimeJSON ProformaInvoice)
  => ProformaInvoice -- ^ "proformaInvoice"
  -> SimpleBillyRequest CreateProformaInvoice MimeJSON ProformaInvoice MimeJSON
createProformaInvoice proformaInvoice =
  _mkRequest "POST" ["/api/v1/proforma-invoices"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` proformaInvoice

data CreateProformaInvoice 
instance HasBodyParam CreateProformaInvoice ProformaInvoice 

-- | @application/json@
instance Consumes CreateProformaInvoice MimeJSON

-- | @application/json@
instance Produces CreateProformaInvoice MimeJSON


-- *** deleteProformaInvoice

-- | @DELETE \/api\/v1\/proforma-invoices\/{proforma_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteProformaInvoice
  :: ProformaId -- ^ "proformaId"
  -> SimpleBillyRequest DeleteProformaInvoice MimeNoContent NoContent MimeNoContent
deleteProformaInvoice (ProformaId proformaId) =
  _mkRequest "DELETE" ["/api/v1/proforma-invoices/",toPath proformaId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteProformaInvoice  
instance Produces DeleteProformaInvoice MimeNoContent


-- *** getProformaInvoice

-- | @GET \/api\/v1\/proforma-invoices\/{proforma_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getProformaInvoice
  :: ProformaId -- ^ "proformaId"
  -> SimpleBillyRequest GetProformaInvoice MimeNoContent ProformaInvoice MimeJSON
getProformaInvoice (ProformaId proformaId) =
  _mkRequest "GET" ["/api/v1/proforma-invoices/",toPath proformaId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetProformaInvoice  
-- | @application/json@
instance Produces GetProformaInvoice MimeJSON


-- *** listProformaInvoices

-- | @GET \/api\/v1\/proforma-invoices\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listProformaInvoices
  :: SimpleBillyRequest ListProformaInvoices MimeNoContent [ProformaInvoice] MimeJSON
listProformaInvoices =
  _mkRequest "GET" ["/api/v1/proforma-invoices/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListProformaInvoices  
instance HasOptionalParam ListProformaInvoices Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam ListProformaInvoices PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam ListProformaInvoices Status where
  applyOptionalParam req (Status xs) =
    req `addQuery` toQuery ("status", Just xs)
instance HasOptionalParam ListProformaInvoices CustomerId where
  applyOptionalParam req (CustomerId xs) =
    req `addQuery` toQuery ("customer_id", Just xs)
instance HasOptionalParam ListProformaInvoices OrderNumber where
  applyOptionalParam req (OrderNumber xs) =
    req `addQuery` toQuery ("order_number", Just xs)
-- | @application/json@
instance Produces ListProformaInvoices MimeJSON


-- *** updateProformaInvoice

-- | @PUT \/api\/v1\/proforma-invoices\/{proforma_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateProformaInvoice
  :: (Consumes UpdateProformaInvoice MimeJSON, MimeRender MimeJSON Body)
  => Body -- ^ "body"
  -> ProformaId -- ^ "proformaId"
  -> SimpleBillyRequest UpdateProformaInvoice MimeJSON ProformaInvoice MimeJSON
updateProformaInvoice body (ProformaId proformaId) =
  _mkRequest "PUT" ["/api/v1/proforma-invoices/",toPath proformaId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` body

data UpdateProformaInvoice 
instance HasBodyParam UpdateProformaInvoice Body 

-- | @application/json@
instance Consumes UpdateProformaInvoice MimeJSON

-- | @application/json@
instance Produces UpdateProformaInvoice MimeJSON

