{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.PublicReturns
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.PublicReturns where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** PublicReturns

-- *** getPublicReturnStatus

-- | @GET \/api\/v1\/public\/returns\/status@
-- 
-- Customer checks the status of a return (public, no auth). The return is only revealed when its linked order's email matches.
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getPublicReturnStatus
  :: Email -- ^ "email"
  -> SimpleBillyRequest GetPublicReturnStatus MimeNoContent PublicReturnStatusResponse MimeJSON
getPublicReturnStatus (Email email) =
  _mkRequest "GET" ["/api/v1/public/returns/status"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `addQuery` toQuery ("email", Just email)

data GetPublicReturnStatus  

-- | /Optional Param/ "returnNumber" - Either return_number or return_order_id must be provided.
instance HasOptionalParam GetPublicReturnStatus ReturnNumber where
  applyOptionalParam req (ReturnNumber xs) =
    req `addQuery` toQuery ("returnNumber", Just xs)
instance HasOptionalParam GetPublicReturnStatus ReturnOrderId where
  applyOptionalParam req (ReturnOrderId xs) =
    req `addQuery` toQuery ("returnOrderId", Just xs)
instance HasOptionalParam GetPublicReturnStatus OrderNumber where
  applyOptionalParam req (OrderNumber xs) =
    req `addQuery` toQuery ("orderNumber", Just xs)
-- | @application/json@
instance Produces GetPublicReturnStatus MimeJSON


-- *** listPublicReturns

-- | @GET \/api\/v1\/public\/returns\/list@
-- 
-- List all returns for an order (public, no auth).
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listPublicReturns
  :: OrderNumber -- ^ "orderNumber"
  -> Email -- ^ "email"
  -> SimpleBillyRequest ListPublicReturns MimeNoContent [PublicReturnStatusResponse] MimeJSON
listPublicReturns (OrderNumber orderNumber) (Email email) =
  _mkRequest "GET" ["/api/v1/public/returns/list"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `addQuery` toQuery ("orderNumber", Just orderNumber)
    `addQuery` toQuery ("email", Just email)

data ListPublicReturns  
-- | @application/json@
instance Produces ListPublicReturns MimeJSON


-- *** requestPublicReturn

-- | @POST \/api\/v1\/public\/returns\/request@
-- 
-- Customer requests a return for an order (public, no auth).
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
requestPublicReturn
  :: (Consumes RequestPublicReturn MimeJSON, MimeRender MimeJSON PublicReturnRequest)
  => PublicReturnRequest -- ^ "publicReturnRequest"
  -> SimpleBillyRequest RequestPublicReturn MimeJSON PublicReturnResponse MimeJSON
requestPublicReturn publicReturnRequest =
  _mkRequest "POST" ["/api/v1/public/returns/request"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` publicReturnRequest

data RequestPublicReturn 
instance HasBodyParam RequestPublicReturn PublicReturnRequest 

-- | @application/json@
instance Consumes RequestPublicReturn MimeJSON

-- | @application/json@
instance Produces RequestPublicReturn MimeJSON

