{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.PurchaseOrder
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.PurchaseOrder where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** PurchaseOrder

-- *** createPurchaseOrder

-- | @POST \/api\/v1\/purchase-orders@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createPurchaseOrder
  :: (Consumes CreatePurchaseOrder MimeJSON, MimeRender MimeJSON PurchaseOrder)
  => PurchaseOrder -- ^ "purchaseOrder"
  -> SimpleBillyRequest CreatePurchaseOrder MimeJSON PurchaseOrder MimeJSON
createPurchaseOrder purchaseOrder =
  _mkRequest "POST" ["/api/v1/purchase-orders"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` purchaseOrder

data CreatePurchaseOrder 
instance HasBodyParam CreatePurchaseOrder PurchaseOrder 

-- | @application/json@
instance Consumes CreatePurchaseOrder MimeJSON

-- | @application/json@
instance Produces CreatePurchaseOrder MimeJSON


-- *** deletePurchaseOrder

-- | @DELETE \/api\/v1\/purchase-orders\/{purchase_order_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deletePurchaseOrder
  :: PurchaseOrderId -- ^ "purchaseOrderId"
  -> SimpleBillyRequest DeletePurchaseOrder MimeNoContent NoContent MimeNoContent
deletePurchaseOrder (PurchaseOrderId purchaseOrderId) =
  _mkRequest "DELETE" ["/api/v1/purchase-orders/",toPath purchaseOrderId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeletePurchaseOrder  
instance Produces DeletePurchaseOrder MimeNoContent


-- *** getPurchaseOrder

-- | @GET \/api\/v1\/purchase-orders\/{purchase_order_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getPurchaseOrder
  :: PurchaseOrderId -- ^ "purchaseOrderId"
  -> SimpleBillyRequest GetPurchaseOrder MimeNoContent PurchaseOrder MimeJSON
getPurchaseOrder (PurchaseOrderId purchaseOrderId) =
  _mkRequest "GET" ["/api/v1/purchase-orders/",toPath purchaseOrderId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetPurchaseOrder  
-- | @application/json@
instance Produces GetPurchaseOrder MimeJSON


-- *** listPurchaseOrders

-- | @GET \/api\/v1\/purchase-orders\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listPurchaseOrders
  :: SimpleBillyRequest ListPurchaseOrders MimeNoContent [PurchaseOrder] MimeJSON
listPurchaseOrders =
  _mkRequest "GET" ["/api/v1/purchase-orders/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListPurchaseOrders  
instance HasOptionalParam ListPurchaseOrders Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam ListPurchaseOrders PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam ListPurchaseOrders Status where
  applyOptionalParam req (Status xs) =
    req `addQuery` toQuery ("status", Just xs)
instance HasOptionalParam ListPurchaseOrders SupplierName where
  applyOptionalParam req (SupplierName xs) =
    req `addQuery` toQuery ("supplier_name", Just xs)
instance HasOptionalParam ListPurchaseOrders Search where
  applyOptionalParam req (Search xs) =
    req `addQuery` toQuery ("search", Just xs)
-- | @application/json@
instance Produces ListPurchaseOrders MimeJSON


-- *** matchInvoice

-- | @POST \/api\/v1\/purchase-orders\/{purchase_order_id}\/match-invoice@
-- 
-- 3-way invoice check (Rechnungsprüfung): compares the purchase order line items, the quantities received via goods receipts, and the supplier invoice line items, reporting quantity and price variances per product.
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
matchInvoice
  :: (Consumes MatchInvoice MimeJSON, MimeRender MimeJSON InvoiceMatchRequest)
  => InvoiceMatchRequest -- ^ "invoiceMatchRequest"
  -> PurchaseOrderId -- ^ "purchaseOrderId"
  -> SimpleBillyRequest MatchInvoice MimeJSON AnyType MimeJSON
matchInvoice invoiceMatchRequest (PurchaseOrderId purchaseOrderId) =
  _mkRequest "POST" ["/api/v1/purchase-orders/",toPath purchaseOrderId,"/match-invoice"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` invoiceMatchRequest

data MatchInvoice 
instance HasBodyParam MatchInvoice InvoiceMatchRequest 

-- | @application/json@
instance Consumes MatchInvoice MimeJSON

-- | @application/json@
instance Produces MatchInvoice MimeJSON


-- *** updatePurchaseOrder

-- | @PUT \/api\/v1\/purchase-orders\/{purchase_order_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updatePurchaseOrder
  :: (Consumes UpdatePurchaseOrder MimeJSON, MimeRender MimeJSON Body)
  => Body -- ^ "body"
  -> PurchaseOrderId -- ^ "purchaseOrderId"
  -> SimpleBillyRequest UpdatePurchaseOrder MimeJSON PurchaseOrder MimeJSON
updatePurchaseOrder body (PurchaseOrderId purchaseOrderId) =
  _mkRequest "PUT" ["/api/v1/purchase-orders/",toPath purchaseOrderId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` body

data UpdatePurchaseOrder 
instance HasBodyParam UpdatePurchaseOrder Body 

-- | @application/json@
instance Consumes UpdatePurchaseOrder MimeJSON

-- | @application/json@
instance Produces UpdatePurchaseOrder MimeJSON


-- *** updatePurchaseOrderStatus

-- | @PUT \/api\/v1\/purchase-orders\/{purchase_order_id}\/status@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updatePurchaseOrderStatus
  :: (Consumes UpdatePurchaseOrderStatus MimeJSON, MimeRender MimeJSON PurchaseOrderStatusUpdate)
  => PurchaseOrderStatusUpdate -- ^ "purchaseOrderStatusUpdate"
  -> PurchaseOrderId -- ^ "purchaseOrderId"
  -> SimpleBillyRequest UpdatePurchaseOrderStatus MimeJSON PurchaseOrder MimeJSON
updatePurchaseOrderStatus purchaseOrderStatusUpdate (PurchaseOrderId purchaseOrderId) =
  _mkRequest "PUT" ["/api/v1/purchase-orders/",toPath purchaseOrderId,"/status"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` purchaseOrderStatusUpdate

data UpdatePurchaseOrderStatus 
instance HasBodyParam UpdatePurchaseOrderStatus PurchaseOrderStatusUpdate 

-- | @application/json@
instance Consumes UpdatePurchaseOrderStatus MimeJSON

-- | @application/json@
instance Produces UpdatePurchaseOrderStatus MimeJSON

