{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.Quotation
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.Quotation where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Quotation

-- *** createQuotation

-- | @POST \/api\/v1\/quotations@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createQuotation
  :: (Consumes CreateQuotation MimeJSON, MimeRender MimeJSON QuotationCreate)
  => QuotationCreate -- ^ "quotationCreate"
  -> SimpleBillyRequest CreateQuotation MimeJSON Quotation MimeJSON
createQuotation quotationCreate =
  _mkRequest "POST" ["/api/v1/quotations"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` quotationCreate

data CreateQuotation 
instance HasBodyParam CreateQuotation QuotationCreate 

-- | @application/json@
instance Consumes CreateQuotation MimeJSON

-- | @application/json@
instance Produces CreateQuotation MimeJSON


-- *** deleteQuotation

-- | @DELETE \/api\/v1\/quotations\/{quotation_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteQuotation
  :: QuotationId -- ^ "quotationId"
  -> SimpleBillyRequest DeleteQuotation MimeNoContent NoContent MimeNoContent
deleteQuotation (QuotationId quotationId) =
  _mkRequest "DELETE" ["/api/v1/quotations/",toPath quotationId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteQuotation  
instance Produces DeleteQuotation MimeNoContent


-- *** downloadQuotationPdf

-- | @GET \/api\/v1\/quotations\/{quotation_id}\/pdf@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
downloadQuotationPdf
  :: QuotationId -- ^ "quotationId"
  -> SimpleBillyRequest DownloadQuotationPdf MimeNoContent NoContent MimeNoContent
downloadQuotationPdf (QuotationId quotationId) =
  _mkRequest "GET" ["/api/v1/quotations/",toPath quotationId,"/pdf"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DownloadQuotationPdf  
instance Produces DownloadQuotationPdf MimeNoContent


-- *** getQuotation

-- | @GET \/api\/v1\/quotations\/{quotation_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getQuotation
  :: QuotationId -- ^ "quotationId"
  -> SimpleBillyRequest GetQuotation MimeNoContent Quotation MimeJSON
getQuotation (QuotationId quotationId) =
  _mkRequest "GET" ["/api/v1/quotations/",toPath quotationId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetQuotation  
-- | @application/json@
instance Produces GetQuotation MimeJSON


-- *** listQuotations

-- | @GET \/api\/v1\/quotations\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listQuotations
  :: SimpleBillyRequest ListQuotations MimeNoContent [Quotation] MimeJSON
listQuotations =
  _mkRequest "GET" ["/api/v1/quotations/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListQuotations  
instance HasOptionalParam ListQuotations Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam ListQuotations PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam ListQuotations Search where
  applyOptionalParam req (Search xs) =
    req `addQuery` toQuery ("search", Just xs)

-- | /Optional Param/ "include_deleted" - Soft-delete entities: set true to include rows with `deleted_at` set.
instance HasOptionalParam ListQuotations IncludeDeleted where
  applyOptionalParam req (IncludeDeleted xs) =
    req `addQuery` toQuery ("include_deleted", Just xs)
-- | @application/json@
instance Produces ListQuotations MimeJSON


-- *** pursueQuotation

-- | @POST \/api\/v1\/quotations\/{quotation_id}\/pursue@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
pursueQuotation
  :: QuotationId -- ^ "quotationId"
  -> SimpleBillyRequest PursueQuotation MimeNoContent OrderConfirmation MimeJSON
pursueQuotation (QuotationId quotationId) =
  _mkRequest "POST" ["/api/v1/quotations/",toPath quotationId,"/pursue"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data PursueQuotation  
-- | @application/json@
instance Produces PursueQuotation MimeJSON


-- *** quotationRestore

-- | @POST \/api\/v1\/quotations\/{quotation_id}\/restore@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
quotationRestore
  :: QuotationId -- ^ "quotationId"
  -> SimpleBillyRequest QuotationRestore MimeNoContent Quotation MimeJSON
quotationRestore (QuotationId quotationId) =
  _mkRequest "POST" ["/api/v1/quotations/",toPath quotationId,"/restore"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data QuotationRestore  
-- | @application/json@
instance Produces QuotationRestore MimeJSON


-- *** updateQuotation

-- | @PUT \/api\/v1\/quotations\/{quotation_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateQuotation
  :: (Consumes UpdateQuotation MimeJSON, MimeRender MimeJSON Body)
  => Body -- ^ "body"
  -> QuotationId -- ^ "quotationId"
  -> SimpleBillyRequest UpdateQuotation MimeJSON Quotation MimeJSON
updateQuotation body (QuotationId quotationId) =
  _mkRequest "PUT" ["/api/v1/quotations/",toPath quotationId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` body

data UpdateQuotation 
instance HasBodyParam UpdateQuotation Body 

-- | @application/json@
instance Consumes UpdateQuotation MimeJSON

-- | @application/json@
instance Produces UpdateQuotation MimeJSON

