{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.RecurringTemplate
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.RecurringTemplate where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** RecurringTemplate

-- *** createRecurringTemplate

-- | @POST \/api\/v1\/recurring-templates@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createRecurringTemplate
  :: (Consumes CreateRecurringTemplate MimeJSON, MimeRender MimeJSON Body)
  => Body -- ^ "body"
  -> SimpleBillyRequest CreateRecurringTemplate MimeJSON RecurringTemplate MimeJSON
createRecurringTemplate body =
  _mkRequest "POST" ["/api/v1/recurring-templates"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` body

data CreateRecurringTemplate 
instance HasBodyParam CreateRecurringTemplate Body 

-- | @application/json@
instance Consumes CreateRecurringTemplate MimeJSON

-- | @application/json@
instance Produces CreateRecurringTemplate MimeJSON


-- *** deleteRecurringTemplate

-- | @DELETE \/api\/v1\/recurring-templates\/{template_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteRecurringTemplate
  :: TemplateId -- ^ "templateId"
  -> SimpleBillyRequest DeleteRecurringTemplate MimeNoContent NoContent MimeNoContent
deleteRecurringTemplate (TemplateId templateId) =
  _mkRequest "DELETE" ["/api/v1/recurring-templates/",toPath templateId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteRecurringTemplate  
instance Produces DeleteRecurringTemplate MimeNoContent


-- *** getRecurringTemplate

-- | @GET \/api\/v1\/recurring-templates\/{template_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getRecurringTemplate
  :: TemplateId -- ^ "templateId"
  -> SimpleBillyRequest GetRecurringTemplate MimeNoContent RecurringTemplate MimeJSON
getRecurringTemplate (TemplateId templateId) =
  _mkRequest "GET" ["/api/v1/recurring-templates/",toPath templateId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetRecurringTemplate  
-- | @application/json@
instance Produces GetRecurringTemplate MimeJSON


-- *** listRecurringTemplates

-- | @GET \/api\/v1\/recurring-templates\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listRecurringTemplates
  :: SimpleBillyRequest ListRecurringTemplates MimeNoContent [RecurringTemplate] MimeJSON
listRecurringTemplates =
  _mkRequest "GET" ["/api/v1/recurring-templates/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListRecurringTemplates  
-- | @application/json@
instance Produces ListRecurringTemplates MimeJSON

