{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.ReturnOrder
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.ReturnOrder where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** ReturnOrder

-- *** createReturnOrder

-- | @POST \/api\/v1\/returns@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createReturnOrder
  :: (Consumes CreateReturnOrder MimeJSON, MimeRender MimeJSON ReturnOrder)
  => ReturnOrder -- ^ "returnOrder"
  -> SimpleBillyRequest CreateReturnOrder MimeJSON ReturnOrder MimeJSON
createReturnOrder returnOrder =
  _mkRequest "POST" ["/api/v1/returns"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` returnOrder

data CreateReturnOrder 
instance HasBodyParam CreateReturnOrder ReturnOrder 

-- | @application/json@
instance Consumes CreateReturnOrder MimeJSON

-- | @application/json@
instance Produces CreateReturnOrder MimeJSON


-- *** deleteReturnOrder

-- | @DELETE \/api\/v1\/returns\/{return_order_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteReturnOrder
  :: ReturnOrderId -- ^ "returnOrderId"
  -> SimpleBillyRequest DeleteReturnOrder MimeNoContent NoContent MimeNoContent
deleteReturnOrder (ReturnOrderId returnOrderId) =
  _mkRequest "DELETE" ["/api/v1/returns/",toPath returnOrderId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteReturnOrder  
instance Produces DeleteReturnOrder MimeNoContent


-- *** getReturnOrder

-- | @GET \/api\/v1\/returns\/{return_order_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getReturnOrder
  :: ReturnOrderId -- ^ "returnOrderId"
  -> SimpleBillyRequest GetReturnOrder MimeNoContent ReturnOrder MimeJSON
getReturnOrder (ReturnOrderId returnOrderId) =
  _mkRequest "GET" ["/api/v1/returns/",toPath returnOrderId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetReturnOrder  
-- | @application/json@
instance Produces GetReturnOrder MimeJSON


-- *** listReturnOrders

-- | @GET \/api\/v1\/returns\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listReturnOrders
  :: SimpleBillyRequest ListReturnOrders MimeNoContent [ReturnOrder] MimeJSON
listReturnOrders =
  _mkRequest "GET" ["/api/v1/returns/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListReturnOrders  
instance HasOptionalParam ListReturnOrders Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam ListReturnOrders PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam ListReturnOrders Status where
  applyOptionalParam req (Status xs) =
    req `addQuery` toQuery ("status", Just xs)
instance HasOptionalParam ListReturnOrders CustomerName where
  applyOptionalParam req (CustomerName xs) =
    req `addQuery` toQuery ("customer_name", Just xs)
instance HasOptionalParam ListReturnOrders OrderNumber where
  applyOptionalParam req (OrderNumber xs) =
    req `addQuery` toQuery ("order_number", Just xs)
-- | @application/json@
instance Produces ListReturnOrders MimeJSON


-- *** returnLogisticsQueue

-- | @GET \/api\/v1\/returns\/logistics-queue@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
returnLogisticsQueue
  :: SimpleBillyRequest ReturnLogisticsQueue MimeNoContent [ReturnLogisticsQueueItem] MimeJSON
returnLogisticsQueue =
  _mkRequest "GET" ["/api/v1/returns/logistics-queue"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ReturnLogisticsQueue  
-- | @application/json@
instance Produces ReturnLogisticsQueue MimeJSON


-- *** returnLogisticsSummary0

-- | @GET \/api\/v1\/returns\/logistics-summary@
-- 
-- Returns-logistics aggregation for the dashboard: quantities received, restocked and scrapped per warehouse.
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
returnLogisticsSummary0
  :: SimpleBillyRequest ReturnLogisticsSummary0 MimeNoContent ReturnLogisticsSummary MimeJSON
returnLogisticsSummary0 =
  _mkRequest "GET" ["/api/v1/returns/logistics-summary"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ReturnLogisticsSummary0  
-- | @application/json@
instance Produces ReturnLogisticsSummary0 MimeJSON


-- *** updateReturnOrder

-- | @PUT \/api\/v1\/returns\/{return_order_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateReturnOrder
  :: (Consumes UpdateReturnOrder MimeJSON, MimeRender MimeJSON Body)
  => Body -- ^ "body"
  -> ReturnOrderId -- ^ "returnOrderId"
  -> SimpleBillyRequest UpdateReturnOrder MimeJSON ReturnOrder MimeJSON
updateReturnOrder body (ReturnOrderId returnOrderId) =
  _mkRequest "PUT" ["/api/v1/returns/",toPath returnOrderId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` body

data UpdateReturnOrder 
instance HasBodyParam UpdateReturnOrder Body 

-- | @application/json@
instance Consumes UpdateReturnOrder MimeJSON

-- | @application/json@
instance Produces UpdateReturnOrder MimeJSON


-- *** updateReturnOrderStatus

-- | @PUT \/api\/v1\/returns\/{return_order_id}\/status@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateReturnOrderStatus
  :: (Consumes UpdateReturnOrderStatus MimeJSON, MimeRender MimeJSON ReturnOrderStatusUpdate)
  => ReturnOrderStatusUpdate -- ^ "returnOrderStatusUpdate"
  -> ReturnOrderId -- ^ "returnOrderId"
  -> SimpleBillyRequest UpdateReturnOrderStatus MimeJSON ReturnOrder MimeJSON
updateReturnOrderStatus returnOrderStatusUpdate (ReturnOrderId returnOrderId) =
  _mkRequest "PUT" ["/api/v1/returns/",toPath returnOrderId,"/status"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` returnOrderStatusUpdate

data UpdateReturnOrderStatus 
instance HasBodyParam UpdateReturnOrderStatus ReturnOrderStatusUpdate 

-- | @application/json@
instance Consumes UpdateReturnOrderStatus MimeJSON

-- | @application/json@
instance Produces UpdateReturnOrderStatus MimeJSON

