{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.Rfq
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.Rfq where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Rfq

-- *** convertRfq

-- | @POST \/api\/v1\/rfqs\/{rfq_id}\/convert@
-- 
-- Convert an RFQ into a draft purchase order using the quoted unit prices (falling back to the requested prices, then leaving them blank). Marks the RFQ as `converted`.
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
convertRfq
  :: RfqId -- ^ "rfqId"
  -> SimpleBillyRequest ConvertRfq MimeNoContent AnyType MimeJSON
convertRfq (RfqId rfqId) =
  _mkRequest "POST" ["/api/v1/rfqs/",toPath rfqId,"/convert"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ConvertRfq  
-- | @application/json@
instance Produces ConvertRfq MimeJSON


-- *** createRfq

-- | @POST \/api\/v1\/rfqs@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createRfq
  :: (Consumes CreateRfq MimeJSON, MimeRender MimeJSON Rfq)
  => Rfq -- ^ "rfq"
  -> SimpleBillyRequest CreateRfq MimeJSON Rfq MimeJSON
createRfq rfq =
  _mkRequest "POST" ["/api/v1/rfqs"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` rfq

data CreateRfq 
instance HasBodyParam CreateRfq Rfq 

-- | @application/json@
instance Consumes CreateRfq MimeJSON

-- | @application/json@
instance Produces CreateRfq MimeJSON


-- *** deleteRfq

-- | @DELETE \/api\/v1\/rfqs\/{rfq_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteRfq
  :: RfqId -- ^ "rfqId"
  -> SimpleBillyRequest DeleteRfq MimeNoContent NoContent MimeNoContent
deleteRfq (RfqId rfqId) =
  _mkRequest "DELETE" ["/api/v1/rfqs/",toPath rfqId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteRfq  
instance Produces DeleteRfq MimeNoContent


-- *** getRfq

-- | @GET \/api\/v1\/rfqs\/{rfq_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getRfq
  :: RfqId -- ^ "rfqId"
  -> SimpleBillyRequest GetRfq MimeNoContent Rfq MimeJSON
getRfq (RfqId rfqId) =
  _mkRequest "GET" ["/api/v1/rfqs/",toPath rfqId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetRfq  
-- | @application/json@
instance Produces GetRfq MimeJSON


-- *** listRfqs

-- | @GET \/api\/v1\/rfqs\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listRfqs
  :: SimpleBillyRequest ListRfqs MimeNoContent [Rfq] MimeJSON
listRfqs =
  _mkRequest "GET" ["/api/v1/rfqs/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListRfqs  
instance HasOptionalParam ListRfqs Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam ListRfqs PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam ListRfqs Status where
  applyOptionalParam req (Status xs) =
    req `addQuery` toQuery ("status", Just xs)
instance HasOptionalParam ListRfqs SupplierName where
  applyOptionalParam req (SupplierName xs) =
    req `addQuery` toQuery ("supplier_name", Just xs)
-- | @application/json@
instance Produces ListRfqs MimeJSON


-- *** updateRfq

-- | @PUT \/api\/v1\/rfqs\/{rfq_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateRfq
  :: (Consumes UpdateRfq MimeJSON, MimeRender MimeJSON Body)
  => Body -- ^ "body"
  -> RfqId -- ^ "rfqId"
  -> SimpleBillyRequest UpdateRfq MimeJSON Rfq MimeJSON
updateRfq body (RfqId rfqId) =
  _mkRequest "PUT" ["/api/v1/rfqs/",toPath rfqId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` body

data UpdateRfq 
instance HasBodyParam UpdateRfq Body 

-- | @application/json@
instance Consumes UpdateRfq MimeJSON

-- | @application/json@
instance Produces UpdateRfq MimeJSON


-- *** updateRfqStatus

-- | @PUT \/api\/v1\/rfqs\/{rfq_id}\/status@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateRfqStatus
  :: (Consumes UpdateRfqStatus MimeJSON, MimeRender MimeJSON RfqStatusUpdate)
  => RfqStatusUpdate -- ^ "rfqStatusUpdate"
  -> RfqId -- ^ "rfqId"
  -> SimpleBillyRequest UpdateRfqStatus MimeJSON Rfq MimeJSON
updateRfqStatus rfqStatusUpdate (RfqId rfqId) =
  _mkRequest "PUT" ["/api/v1/rfqs/",toPath rfqId,"/status"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` rfqStatusUpdate

data UpdateRfqStatus 
instance HasBodyParam UpdateRfqStatus RfqStatusUpdate 

-- | @application/json@
instance Consumes UpdateRfqStatus MimeJSON

-- | @application/json@
instance Produces UpdateRfqStatus MimeJSON

