{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.ServiceJob
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.ServiceJob where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** ServiceJob

-- *** createServiceJob

-- | @POST \/api\/v1\/service-jobs@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createServiceJob
  :: (Consumes CreateServiceJob MimeJSON, MimeRender MimeJSON ServiceJobCreate)
  => ServiceJobCreate -- ^ "serviceJobCreate"
  -> SimpleBillyRequest CreateServiceJob MimeJSON ServiceJob MimeJSON
createServiceJob serviceJobCreate =
  _mkRequest "POST" ["/api/v1/service-jobs"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` serviceJobCreate

data CreateServiceJob 
instance HasBodyParam CreateServiceJob ServiceJobCreate 

-- | @application/json@
instance Consumes CreateServiceJob MimeJSON

-- | @application/json@
instance Produces CreateServiceJob MimeJSON


-- *** deleteServiceJob

-- | @DELETE \/api\/v1\/service-jobs\/{id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteServiceJob
  :: Id -- ^ "id"
  -> SimpleBillyRequest DeleteServiceJob MimeNoContent NoContent MimeNoContent
deleteServiceJob (Id id) =
  _mkRequest "DELETE" ["/api/v1/service-jobs/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteServiceJob  
instance Produces DeleteServiceJob MimeNoContent


-- *** getServiceJob

-- | @GET \/api\/v1\/service-jobs\/{id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getServiceJob
  :: Id -- ^ "id"
  -> SimpleBillyRequest GetServiceJob MimeNoContent ServiceJob MimeJSON
getServiceJob (Id id) =
  _mkRequest "GET" ["/api/v1/service-jobs/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetServiceJob  
-- | @application/json@
instance Produces GetServiceJob MimeJSON


-- *** getServiceJobs

-- | @GET \/api\/v1\/service-jobs\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getServiceJobs
  :: SimpleBillyRequest GetServiceJobs MimeNoContent [ServiceJob] MimeJSON
getServiceJobs =
  _mkRequest "GET" ["/api/v1/service-jobs/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetServiceJobs  
instance HasOptionalParam GetServiceJobs Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam GetServiceJobs PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam GetServiceJobs Search where
  applyOptionalParam req (Search xs) =
    req `addQuery` toQuery ("search", Just xs)

-- | /Optional Param/ "include_deleted" - Soft-delete entities: set true to include rows with `deleted_at` set.
instance HasOptionalParam GetServiceJobs IncludeDeleted where
  applyOptionalParam req (IncludeDeleted xs) =
    req `addQuery` toQuery ("include_deleted", Just xs)
-- | @application/json@
instance Produces GetServiceJobs MimeJSON


-- *** updateServiceJob

-- | @PUT \/api\/v1\/service-jobs\/{id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateServiceJob
  :: (Consumes UpdateServiceJob MimeJSON, MimeRender MimeJSON ServiceJobUpdate)
  => ServiceJobUpdate -- ^ "serviceJobUpdate"
  -> Id -- ^ "id"
  -> SimpleBillyRequest UpdateServiceJob MimeJSON ServiceJob MimeJSON
updateServiceJob serviceJobUpdate (Id id) =
  _mkRequest "PUT" ["/api/v1/service-jobs/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` serviceJobUpdate

data UpdateServiceJob 
instance HasBodyParam UpdateServiceJob ServiceJobUpdate 

-- | @application/json@
instance Consumes UpdateServiceJob MimeJSON

-- | @application/json@
instance Produces UpdateServiceJob MimeJSON

