{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.Shareholder
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.Shareholder where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Shareholder

-- *** createShareholder

-- | @POST \/api\/v1\/shareholders@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createShareholder
  :: (Consumes CreateShareholder MimeJSON, MimeRender MimeJSON ShareholderCreate)
  => ShareholderCreate -- ^ "shareholderCreate"
  -> SimpleBillyRequest CreateShareholder MimeJSON Shareholder MimeJSON
createShareholder shareholderCreate =
  _mkRequest "POST" ["/api/v1/shareholders"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` shareholderCreate

data CreateShareholder 
instance HasBodyParam CreateShareholder ShareholderCreate 

-- | @application/json@
instance Consumes CreateShareholder MimeJSON

-- | @application/json@
instance Produces CreateShareholder MimeJSON


-- *** deleteShareholder

-- | @DELETE \/api\/v1\/shareholders\/{id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteShareholder
  :: Id -- ^ "id"
  -> SimpleBillyRequest DeleteShareholder MimeNoContent NoContent MimeNoContent
deleteShareholder (Id id) =
  _mkRequest "DELETE" ["/api/v1/shareholders/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteShareholder  
instance Produces DeleteShareholder MimeNoContent


-- *** getShareholder

-- | @GET \/api\/v1\/shareholders\/{id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getShareholder
  :: Id -- ^ "id"
  -> SimpleBillyRequest GetShareholder MimeNoContent Shareholder MimeJSON
getShareholder (Id id) =
  _mkRequest "GET" ["/api/v1/shareholders/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetShareholder  
-- | @application/json@
instance Produces GetShareholder MimeJSON


-- *** getShareholders

-- | @GET \/api\/v1\/shareholders\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getShareholders
  :: SimpleBillyRequest GetShareholders MimeNoContent [Shareholder] MimeJSON
getShareholders =
  _mkRequest "GET" ["/api/v1/shareholders/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetShareholders  
instance HasOptionalParam GetShareholders Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam GetShareholders PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam GetShareholders Search where
  applyOptionalParam req (Search xs) =
    req `addQuery` toQuery ("search", Just xs)

-- | /Optional Param/ "include_deleted" - Soft-delete entities: set true to include rows with `deleted_at` set.
instance HasOptionalParam GetShareholders IncludeDeleted where
  applyOptionalParam req (IncludeDeleted xs) =
    req `addQuery` toQuery ("include_deleted", Just xs)
-- | @application/json@
instance Produces GetShareholders MimeJSON


-- *** updateShareholder

-- | @PUT \/api\/v1\/shareholders\/{id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateShareholder
  :: (Consumes UpdateShareholder MimeJSON, MimeRender MimeJSON ShareholderUpdate)
  => ShareholderUpdate -- ^ "shareholderUpdate"
  -> Id -- ^ "id"
  -> SimpleBillyRequest UpdateShareholder MimeJSON Shareholder MimeJSON
updateShareholder shareholderUpdate (Id id) =
  _mkRequest "PUT" ["/api/v1/shareholders/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` shareholderUpdate

data UpdateShareholder 
instance HasBodyParam UpdateShareholder ShareholderUpdate 

-- | @application/json@
instance Consumes UpdateShareholder MimeJSON

-- | @application/json@
instance Produces UpdateShareholder MimeJSON

