{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.ShippingRule
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.ShippingRule where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** ShippingRule

-- *** createShippingRule

-- | @POST \/api\/v1\/shipping-rules@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createShippingRule
  :: (Consumes CreateShippingRule MimeJSON, MimeRender MimeJSON ShippingRuleCreate)
  => ShippingRuleCreate -- ^ "shippingRuleCreate"
  -> SimpleBillyRequest CreateShippingRule MimeJSON ShippingRule MimeJSON
createShippingRule shippingRuleCreate =
  _mkRequest "POST" ["/api/v1/shipping-rules"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` shippingRuleCreate

data CreateShippingRule 
instance HasBodyParam CreateShippingRule ShippingRuleCreate 

-- | @application/json@
instance Consumes CreateShippingRule MimeJSON

-- | @application/json@
instance Produces CreateShippingRule MimeJSON


-- *** deleteShippingRule

-- | @DELETE \/api\/v1\/shipping-rules\/{rule_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteShippingRule
  :: RuleId -- ^ "ruleId"
  -> SimpleBillyRequest DeleteShippingRule MimeNoContent NoContent MimeNoContent
deleteShippingRule (RuleId ruleId) =
  _mkRequest "DELETE" ["/api/v1/shipping-rules/",toPath ruleId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteShippingRule  
instance Produces DeleteShippingRule MimeNoContent


-- *** getShippingRule

-- | @GET \/api\/v1\/shipping-rules\/{rule_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getShippingRule
  :: RuleId -- ^ "ruleId"
  -> SimpleBillyRequest GetShippingRule MimeNoContent ShippingRule MimeJSON
getShippingRule (RuleId ruleId) =
  _mkRequest "GET" ["/api/v1/shipping-rules/",toPath ruleId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetShippingRule  
-- | @application/json@
instance Produces GetShippingRule MimeJSON


-- *** listShippingRules

-- | @GET \/api\/v1\/shipping-rules\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listShippingRules
  :: SimpleBillyRequest ListShippingRules MimeNoContent [ShippingRule] MimeJSON
listShippingRules =
  _mkRequest "GET" ["/api/v1/shipping-rules/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListShippingRules  
instance HasOptionalParam ListShippingRules Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam ListShippingRules PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam ListShippingRules Country where
  applyOptionalParam req (Country xs) =
    req `addQuery` toQuery ("country", Just xs)
-- | @application/json@
instance Produces ListShippingRules MimeJSON


-- *** updateShippingRule

-- | @PUT \/api\/v1\/shipping-rules\/{rule_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateShippingRule
  :: (Consumes UpdateShippingRule MimeJSON, MimeRender MimeJSON ShippingRuleUpdate)
  => ShippingRuleUpdate -- ^ "shippingRuleUpdate"
  -> RuleId -- ^ "ruleId"
  -> SimpleBillyRequest UpdateShippingRule MimeJSON ShippingRule MimeJSON
updateShippingRule shippingRuleUpdate (RuleId ruleId) =
  _mkRequest "PUT" ["/api/v1/shipping-rules/",toPath ruleId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` shippingRuleUpdate

data UpdateShippingRule 
instance HasBodyParam UpdateShippingRule ShippingRuleUpdate 

-- | @application/json@
instance Consumes UpdateShippingRule MimeJSON

-- | @application/json@
instance Produces UpdateShippingRule MimeJSON

