{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.ShippingThreshold
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.ShippingThreshold where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** ShippingThreshold

-- *** createShippingThreshold

-- | @POST \/api\/v1\/shipping-thresholds@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createShippingThreshold
  :: (Consumes CreateShippingThreshold MimeJSON, MimeRender MimeJSON ShippingThresholdCreate)
  => ShippingThresholdCreate -- ^ "shippingThresholdCreate"
  -> SimpleBillyRequest CreateShippingThreshold MimeJSON ShippingThreshold MimeJSON
createShippingThreshold shippingThresholdCreate =
  _mkRequest "POST" ["/api/v1/shipping-thresholds"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` shippingThresholdCreate

data CreateShippingThreshold 
instance HasBodyParam CreateShippingThreshold ShippingThresholdCreate 

-- | @application/json@
instance Consumes CreateShippingThreshold MimeJSON

-- | @application/json@
instance Produces CreateShippingThreshold MimeJSON


-- *** deleteShippingThreshold

-- | @DELETE \/api\/v1\/shipping-thresholds\/{threshold_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteShippingThreshold
  :: ThresholdId -- ^ "thresholdId"
  -> SimpleBillyRequest DeleteShippingThreshold MimeNoContent NoContent MimeNoContent
deleteShippingThreshold (ThresholdId thresholdId) =
  _mkRequest "DELETE" ["/api/v1/shipping-thresholds/",toPath thresholdId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteShippingThreshold  
instance Produces DeleteShippingThreshold MimeNoContent


-- *** getDeliverable

-- | @GET \/api\/v1\/shipping-thresholds\/deliverable@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getDeliverable
  :: ProductId -- ^ "productId"
  -> SimpleBillyRequest GetDeliverable MimeNoContent DeliverableResponse MimeJSON
getDeliverable (ProductId productId) =
  _mkRequest "GET" ["/api/v1/shipping-thresholds/deliverable"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `addQuery` toQuery ("productId", Just productId)

data GetDeliverable  
instance HasOptionalParam GetDeliverable WarehouseId where
  applyOptionalParam req (WarehouseId xs) =
    req `addQuery` toQuery ("warehouseId", Just xs)
-- | @application/json@
instance Produces GetDeliverable MimeJSON


-- *** getShippingThreshold

-- | @GET \/api\/v1\/shipping-thresholds\/{threshold_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getShippingThreshold
  :: ThresholdId -- ^ "thresholdId"
  -> SimpleBillyRequest GetShippingThreshold MimeNoContent ShippingThreshold MimeJSON
getShippingThreshold (ThresholdId thresholdId) =
  _mkRequest "GET" ["/api/v1/shipping-thresholds/",toPath thresholdId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetShippingThreshold  
-- | @application/json@
instance Produces GetShippingThreshold MimeJSON


-- *** listShippingThresholds

-- | @GET \/api\/v1\/shipping-thresholds\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listShippingThresholds
  :: SimpleBillyRequest ListShippingThresholds MimeNoContent [ShippingThreshold] MimeJSON
listShippingThresholds =
  _mkRequest "GET" ["/api/v1/shipping-thresholds/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListShippingThresholds  
instance HasOptionalParam ListShippingThresholds Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam ListShippingThresholds PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam ListShippingThresholds ProductId where
  applyOptionalParam req (ProductId xs) =
    req `addQuery` toQuery ("product_id", Just xs)
instance HasOptionalParam ListShippingThresholds WarehouseId where
  applyOptionalParam req (WarehouseId xs) =
    req `addQuery` toQuery ("warehouse_id", Just xs)
instance HasOptionalParam ListShippingThresholds IsActive where
  applyOptionalParam req (IsActive xs) =
    req `addQuery` toQuery ("is_active", Just xs)
-- | @application/json@
instance Produces ListShippingThresholds MimeJSON


-- *** updateShippingThreshold

-- | @PUT \/api\/v1\/shipping-thresholds\/{threshold_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateShippingThreshold
  :: (Consumes UpdateShippingThreshold MimeJSON, MimeRender MimeJSON ShippingThresholdUpdate)
  => ShippingThresholdUpdate -- ^ "shippingThresholdUpdate"
  -> ThresholdId -- ^ "thresholdId"
  -> SimpleBillyRequest UpdateShippingThreshold MimeJSON ShippingThreshold MimeJSON
updateShippingThreshold shippingThresholdUpdate (ThresholdId thresholdId) =
  _mkRequest "PUT" ["/api/v1/shipping-thresholds/",toPath thresholdId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` shippingThresholdUpdate

data UpdateShippingThreshold 
instance HasBodyParam UpdateShippingThreshold ShippingThresholdUpdate 

-- | @application/json@
instance Consumes UpdateShippingThreshold MimeJSON

-- | @application/json@
instance Produces UpdateShippingThreshold MimeJSON

