{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.Shipment
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.Shipment where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Shipment

-- *** createShipment

-- | @POST \/api\/v1\/shipments@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createShipment
  :: (Consumes CreateShipment MimeJSON, MimeRender MimeJSON Shipment)
  => Shipment -- ^ "shipment"
  -> SimpleBillyRequest CreateShipment MimeJSON Shipment MimeJSON
createShipment shipment =
  _mkRequest "POST" ["/api/v1/shipments"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` shipment

data CreateShipment 
instance HasBodyParam CreateShipment Shipment 

-- | @application/json@
instance Consumes CreateShipment MimeJSON

-- | @application/json@
instance Produces CreateShipment MimeJSON


-- *** createShipmentFromOrder

-- | @POST \/api\/v1\/orders\/{order_number}\/shipments@
-- 
-- Create a real shipment for an order: calls the configured carrier's label API, stores the returned tracking/label on a new shipment row, and marks the order as shipped.
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createShipmentFromOrder
  :: (Consumes CreateShipmentFromOrder MimeJSON, MimeRender MimeJSON CreateShipmentRequest)
  => CreateShipmentRequest -- ^ "createShipmentRequest"
  -> OrderNumber -- ^ "orderNumber"
  -> SimpleBillyRequest CreateShipmentFromOrder MimeJSON Shipment MimeJSON
createShipmentFromOrder createShipmentRequest (OrderNumber orderNumber) =
  _mkRequest "POST" ["/api/v1/orders/",toPath orderNumber,"/shipments"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` createShipmentRequest

data CreateShipmentFromOrder 
instance HasBodyParam CreateShipmentFromOrder CreateShipmentRequest 

-- | @application/json@
instance Consumes CreateShipmentFromOrder MimeJSON

-- | @application/json@
instance Produces CreateShipmentFromOrder MimeJSON


-- *** deleteShipment

-- | @DELETE \/api\/v1\/shipments\/{shipment_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteShipment
  :: ShipmentId -- ^ "shipmentId"
  -> SimpleBillyRequest DeleteShipment MimeNoContent NoContent MimeNoContent
deleteShipment (ShipmentId shipmentId) =
  _mkRequest "DELETE" ["/api/v1/shipments/",toPath shipmentId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteShipment  
instance Produces DeleteShipment MimeNoContent


-- *** getShipment

-- | @GET \/api\/v1\/shipments\/{shipment_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getShipment
  :: ShipmentId -- ^ "shipmentId"
  -> SimpleBillyRequest GetShipment MimeNoContent Shipment MimeJSON
getShipment (ShipmentId shipmentId) =
  _mkRequest "GET" ["/api/v1/shipments/",toPath shipmentId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetShipment  
-- | @application/json@
instance Produces GetShipment MimeJSON


-- *** listShipments

-- | @GET \/api\/v1\/shipments@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listShipments
  :: SimpleBillyRequest ListShipments MimeNoContent [Shipment] MimeJSON
listShipments =
  _mkRequest "GET" ["/api/v1/shipments"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListShipments  
instance HasOptionalParam ListShipments Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam ListShipments PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam ListShipments Search where
  applyOptionalParam req (Search xs) =
    req `addQuery` toQuery ("search", Just xs)

-- | /Optional Param/ "include_deleted" - Soft-delete entities: set true to include rows with `deleted_at` set.
instance HasOptionalParam ListShipments IncludeDeleted where
  applyOptionalParam req (IncludeDeleted xs) =
    req `addQuery` toQuery ("include_deleted", Just xs)
-- | @application/json@
instance Produces ListShipments MimeJSON


-- *** trackOrderPublic

-- | @POST \/api\/v1\/public\/track@
-- 
-- Customer-facing tracking lookup: order number + email → shipment status and live carrier events. No auth (public storefront API).
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
trackOrderPublic
  :: (Consumes TrackOrderPublic MimeJSON, MimeRender MimeJSON TrackOrderRequest)
  => TrackOrderRequest -- ^ "trackOrderRequest"
  -> SimpleBillyRequest TrackOrderPublic MimeJSON TrackOrderResponse MimeJSON
trackOrderPublic trackOrderRequest =
  _mkRequest "POST" ["/api/v1/public/track"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` trackOrderRequest

data TrackOrderPublic 
instance HasBodyParam TrackOrderPublic TrackOrderRequest 

-- | @application/json@
instance Consumes TrackOrderPublic MimeJSON

-- | @application/json@
instance Produces TrackOrderPublic MimeJSON


-- *** trackShipmentApi

-- | @GET \/api\/v1\/shipments\/{shipment_id}\/tracking@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
trackShipmentApi
  :: ShipmentId -- ^ "shipmentId"
  -> SimpleBillyRequest TrackShipmentApi MimeNoContent TrackingInfo MimeJSON
trackShipmentApi (ShipmentId shipmentId) =
  _mkRequest "GET" ["/api/v1/shipments/",toPath shipmentId,"/tracking"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data TrackShipmentApi  
-- | @application/json@
instance Produces TrackShipmentApi MimeJSON


-- *** updateShipmentStatus

-- | @PUT \/api\/v1\/shipments\/{shipment_id}\/status@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateShipmentStatus
  :: (Consumes UpdateShipmentStatus MimeJSON, MimeRender MimeJSON ShipmentStatusUpdate)
  => ShipmentStatusUpdate -- ^ "shipmentStatusUpdate"
  -> ShipmentId -- ^ "shipmentId"
  -> SimpleBillyRequest UpdateShipmentStatus MimeJSON Shipment MimeJSON
updateShipmentStatus shipmentStatusUpdate (ShipmentId shipmentId) =
  _mkRequest "PUT" ["/api/v1/shipments/",toPath shipmentId,"/status"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` shipmentStatusUpdate

data UpdateShipmentStatus 
instance HasBodyParam UpdateShipmentStatus ShipmentStatusUpdate 

-- | @application/json@
instance Consumes UpdateShipmentStatus MimeJSON

-- | @application/json@
instance Produces UpdateShipmentStatus MimeJSON

