{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.Shipping
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.Shipping where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Shipping

-- *** getCredentialsApi

-- | @GET \/api\/v1\/shipping\/credentials@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getCredentialsApi
  :: SimpleBillyRequest GetCredentialsApi MimeNoContent ShippingCredentials MimeJSON
getCredentialsApi =
  _mkRequest "GET" ["/api/v1/shipping/credentials"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetCredentialsApi  
-- | @application/json@
instance Produces GetCredentialsApi MimeJSON


-- *** getRatesApi

-- | @POST \/api\/v1\/shipping\/rates@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getRatesApi
  :: (Consumes GetRatesApi MimeJSON, MimeRender MimeJSON RateRequest)
  => RateRequest -- ^ "rateRequest"
  -> SimpleBillyRequest GetRatesApi MimeJSON RateResponse MimeJSON
getRatesApi rateRequest =
  _mkRequest "POST" ["/api/v1/shipping/rates"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` rateRequest

data GetRatesApi 
instance HasBodyParam GetRatesApi RateRequest 

-- | @application/json@
instance Consumes GetRatesApi MimeJSON

-- | @application/json@
instance Produces GetRatesApi MimeJSON


-- *** listProvidersApi

-- | @GET \/api\/v1\/shipping\/providers@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listProvidersApi
  :: SimpleBillyRequest ListProvidersApi MimeNoContent [ProviderInfo] MimeJSON
listProvidersApi =
  _mkRequest "GET" ["/api/v1/shipping/providers"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListProvidersApi  
-- | @application/json@
instance Produces ListProvidersApi MimeJSON


-- *** saveCredentialsApi

-- | @PUT \/api\/v1\/shipping\/credentials@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
saveCredentialsApi
  :: (Consumes SaveCredentialsApi MimeJSON, MimeRender MimeJSON ShippingCredentials)
  => ShippingCredentials -- ^ "shippingCredentials"
  -> SimpleBillyRequest SaveCredentialsApi MimeJSON ShippingCredentials MimeJSON
saveCredentialsApi shippingCredentials =
  _mkRequest "PUT" ["/api/v1/shipping/credentials"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` shippingCredentials

data SaveCredentialsApi 
instance HasBodyParam SaveCredentialsApi ShippingCredentials 

-- | @application/json@
instance Consumes SaveCredentialsApi MimeJSON

-- | @application/json@
instance Produces SaveCredentialsApi MimeJSON

