{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.SupplierInvoice
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.SupplierInvoice where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** SupplierInvoice

-- *** createSupplierInvoice

-- | @POST \/api\/v1\/supplier-invoices@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createSupplierInvoice
  :: (Consumes CreateSupplierInvoice MimeJSON, MimeRender MimeJSON SupplierInvoice)
  => SupplierInvoice -- ^ "supplierInvoice"
  -> SimpleBillyRequest CreateSupplierInvoice MimeJSON SupplierInvoice MimeJSON
createSupplierInvoice supplierInvoice =
  _mkRequest "POST" ["/api/v1/supplier-invoices"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` supplierInvoice

data CreateSupplierInvoice 
instance HasBodyParam CreateSupplierInvoice SupplierInvoice 

-- | @application/json@
instance Consumes CreateSupplierInvoice MimeJSON

-- | @application/json@
instance Produces CreateSupplierInvoice MimeJSON


-- *** deleteSupplierInvoice

-- | @DELETE \/api\/v1\/supplier-invoices\/{supplier_invoice_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteSupplierInvoice
  :: SupplierInvoiceId -- ^ "supplierInvoiceId"
  -> SimpleBillyRequest DeleteSupplierInvoice MimeNoContent NoContent MimeNoContent
deleteSupplierInvoice (SupplierInvoiceId supplierInvoiceId) =
  _mkRequest "DELETE" ["/api/v1/supplier-invoices/",toPath supplierInvoiceId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteSupplierInvoice  
instance Produces DeleteSupplierInvoice MimeNoContent


-- *** getSupplierInvoice

-- | @GET \/api\/v1\/supplier-invoices\/{supplier_invoice_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getSupplierInvoice
  :: SupplierInvoiceId -- ^ "supplierInvoiceId"
  -> SimpleBillyRequest GetSupplierInvoice MimeNoContent SupplierInvoice MimeJSON
getSupplierInvoice (SupplierInvoiceId supplierInvoiceId) =
  _mkRequest "GET" ["/api/v1/supplier-invoices/",toPath supplierInvoiceId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetSupplierInvoice  
-- | @application/json@
instance Produces GetSupplierInvoice MimeJSON


-- *** listSupplierInvoices

-- | @GET \/api\/v1\/supplier-invoices\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listSupplierInvoices
  :: SimpleBillyRequest ListSupplierInvoices MimeNoContent [SupplierInvoice] MimeJSON
listSupplierInvoices =
  _mkRequest "GET" ["/api/v1/supplier-invoices/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListSupplierInvoices  
instance HasOptionalParam ListSupplierInvoices Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam ListSupplierInvoices PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam ListSupplierInvoices Status where
  applyOptionalParam req (Status xs) =
    req `addQuery` toQuery ("status", Just xs)
instance HasOptionalParam ListSupplierInvoices PurchaseOrderId where
  applyOptionalParam req (PurchaseOrderId xs) =
    req `addQuery` toQuery ("purchase_order_id", Just xs)
instance HasOptionalParam ListSupplierInvoices SupplierName where
  applyOptionalParam req (SupplierName xs) =
    req `addQuery` toQuery ("supplier_name", Just xs)
-- | @application/json@
instance Produces ListSupplierInvoices MimeJSON


-- *** updateSupplierInvoice

-- | @PUT \/api\/v1\/supplier-invoices\/{supplier_invoice_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateSupplierInvoice
  :: (Consumes UpdateSupplierInvoice MimeJSON, MimeRender MimeJSON Body)
  => Body -- ^ "body"
  -> SupplierInvoiceId -- ^ "supplierInvoiceId"
  -> SimpleBillyRequest UpdateSupplierInvoice MimeJSON SupplierInvoice MimeJSON
updateSupplierInvoice body (SupplierInvoiceId supplierInvoiceId) =
  _mkRequest "PUT" ["/api/v1/supplier-invoices/",toPath supplierInvoiceId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` body

data UpdateSupplierInvoice 
instance HasBodyParam UpdateSupplierInvoice Body 

-- | @application/json@
instance Consumes UpdateSupplierInvoice MimeJSON

-- | @application/json@
instance Produces UpdateSupplierInvoice MimeJSON


-- *** updateSupplierInvoiceStatus

-- | @PUT \/api\/v1\/supplier-invoices\/{supplier_invoice_id}\/status@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateSupplierInvoiceStatus
  :: (Consumes UpdateSupplierInvoiceStatus MimeJSON, MimeRender MimeJSON SupplierInvoiceStatusUpdate)
  => SupplierInvoiceStatusUpdate -- ^ "supplierInvoiceStatusUpdate"
  -> SupplierInvoiceId -- ^ "supplierInvoiceId"
  -> SimpleBillyRequest UpdateSupplierInvoiceStatus MimeJSON SupplierInvoice MimeJSON
updateSupplierInvoiceStatus supplierInvoiceStatusUpdate (SupplierInvoiceId supplierInvoiceId) =
  _mkRequest "PUT" ["/api/v1/supplier-invoices/",toPath supplierInvoiceId,"/status"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` supplierInvoiceStatusUpdate

data UpdateSupplierInvoiceStatus 
instance HasBodyParam UpdateSupplierInvoiceStatus SupplierInvoiceStatusUpdate 

-- | @application/json@
instance Consumes UpdateSupplierInvoiceStatus MimeJSON

-- | @application/json@
instance Produces UpdateSupplierInvoiceStatus MimeJSON

