{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.SupportTicket
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.SupportTicket where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** SupportTicket

-- *** createTicketApi

-- | @POST \/api\/v1\/support\/tickets@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createTicketApi
  :: (Consumes CreateTicketApi MimeJSON, MimeRender MimeJSON CreateTicketRequest)
  => CreateTicketRequest -- ^ "createTicketRequest"
  -> SimpleBillyRequest CreateTicketApi MimeJSON SupportTicket MimeJSON
createTicketApi createTicketRequest =
  _mkRequest "POST" ["/api/v1/support/tickets"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` createTicketRequest

data CreateTicketApi 
instance HasBodyParam CreateTicketApi CreateTicketRequest 

-- | @application/json@
instance Consumes CreateTicketApi MimeJSON

-- | @application/json@
instance Produces CreateTicketApi MimeJSON


-- *** deleteTicketApi

-- | @DELETE \/api\/v1\/support\/tickets\/{ticket_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteTicketApi
  :: TicketId -- ^ "ticketId"
  -> SimpleBillyRequest DeleteTicketApi MimeNoContent NoContent MimeNoContent
deleteTicketApi (TicketId ticketId) =
  _mkRequest "DELETE" ["/api/v1/support/tickets/",toPath ticketId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteTicketApi  
instance Produces DeleteTicketApi MimeNoContent


-- *** getTicketApi

-- | @GET \/api\/v1\/support\/tickets\/{ticket_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getTicketApi
  :: TicketId -- ^ "ticketId"
  -> SimpleBillyRequest GetTicketApi MimeNoContent SupportTicket MimeJSON
getTicketApi (TicketId ticketId) =
  _mkRequest "GET" ["/api/v1/support/tickets/",toPath ticketId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetTicketApi  
-- | @application/json@
instance Produces GetTicketApi MimeJSON


-- *** listTicketsApi

-- | @GET \/api\/v1\/support\/tickets@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listTicketsApi
  :: SimpleBillyRequest ListTicketsApi MimeNoContent [SupportTicket] MimeJSON
listTicketsApi =
  _mkRequest "GET" ["/api/v1/support/tickets"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListTicketsApi  
instance HasOptionalParam ListTicketsApi Status where
  applyOptionalParam req (Status xs) =
    req `addQuery` toQuery ("status", Just xs)
instance HasOptionalParam ListTicketsApi Priority where
  applyOptionalParam req (Priority xs) =
    req `addQuery` toQuery ("priority", Just xs)
instance HasOptionalParam ListTicketsApi AssignedTo where
  applyOptionalParam req (AssignedTo xs) =
    req `addQuery` toQuery ("assigned_to", Just xs)
instance HasOptionalParam ListTicketsApi ChannelType where
  applyOptionalParam req (ChannelType xs) =
    req `addQuery` toQuery ("channel_type", Just xs)
instance HasOptionalParam ListTicketsApi CustomerId where
  applyOptionalParam req (CustomerId xs) =
    req `addQuery` toQuery ("customer_id", Just xs)
instance HasOptionalParam ListTicketsApi Search where
  applyOptionalParam req (Search xs) =
    req `addQuery` toQuery ("search", Just xs)
instance HasOptionalParam ListTicketsApi Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam ListTicketsApi PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
-- | @application/json@
instance Produces ListTicketsApi MimeJSON


-- *** updateTicketApi

-- | @PUT \/api\/v1\/support\/tickets\/{ticket_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateTicketApi
  :: (Consumes UpdateTicketApi MimeJSON, MimeRender MimeJSON SupportTicketUpdate)
  => SupportTicketUpdate -- ^ "supportTicketUpdate"
  -> TicketId -- ^ "ticketId"
  -> SimpleBillyRequest UpdateTicketApi MimeJSON SupportTicket MimeJSON
updateTicketApi supportTicketUpdate (TicketId ticketId) =
  _mkRequest "PUT" ["/api/v1/support/tickets/",toPath ticketId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` supportTicketUpdate

data UpdateTicketApi 
instance HasBodyParam UpdateTicketApi SupportTicketUpdate 

-- | @application/json@
instance Consumes UpdateTicketApi MimeJSON

-- | @application/json@
instance Produces UpdateTicketApi MimeJSON

