{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.SupportChannel
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.SupportChannel where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** SupportChannel

-- *** createChannelApi

-- | @POST \/api\/v1\/support\/channels@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createChannelApi
  :: (Consumes CreateChannelApi MimeJSON, MimeRender MimeJSON CreateChannelDto)
  => CreateChannelDto -- ^ "createChannelDto"
  -> SimpleBillyRequest CreateChannelApi MimeJSON SupportChannel MimeJSON
createChannelApi createChannelDto =
  _mkRequest "POST" ["/api/v1/support/channels"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` createChannelDto

data CreateChannelApi 
instance HasBodyParam CreateChannelApi CreateChannelDto 

-- | @application/json@
instance Consumes CreateChannelApi MimeJSON

-- | @application/json@
instance Produces CreateChannelApi MimeJSON


-- *** deleteChannelApi

-- | @DELETE \/api\/v1\/support\/channels\/{channel_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteChannelApi
  :: ChannelId -- ^ "channelId"
  -> SimpleBillyRequest DeleteChannelApi MimeNoContent NoContent MimeNoContent
deleteChannelApi (ChannelId channelId) =
  _mkRequest "DELETE" ["/api/v1/support/channels/",toPath channelId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteChannelApi  
instance Produces DeleteChannelApi MimeNoContent


-- *** listChannelsApi

-- | @GET \/api\/v1\/support\/channels@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listChannelsApi
  :: SimpleBillyRequest ListChannelsApi MimeNoContent [SupportChannel] MimeJSON
listChannelsApi =
  _mkRequest "GET" ["/api/v1/support/channels"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListChannelsApi  
-- | @application/json@
instance Produces ListChannelsApi MimeJSON


-- *** updateChannelApi

-- | @PUT \/api\/v1\/support\/channels\/{channel_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateChannelApi
  :: (Consumes UpdateChannelApi MimeJSON, MimeRender MimeJSON UpdateChannelDto)
  => UpdateChannelDto -- ^ "updateChannelDto"
  -> ChannelId -- ^ "channelId"
  -> SimpleBillyRequest UpdateChannelApi MimeJSON SupportChannel MimeJSON
updateChannelApi updateChannelDto (ChannelId channelId) =
  _mkRequest "PUT" ["/api/v1/support/channels/",toPath channelId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` updateChannelDto

data UpdateChannelApi 
instance HasBodyParam UpdateChannelApi UpdateChannelDto 

-- | @application/json@
instance Consumes UpdateChannelApi MimeJSON

-- | @application/json@
instance Produces UpdateChannelApi MimeJSON

