{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.SupplierCondition
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.SupplierCondition where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** SupplierCondition

-- *** createSupplierCondition

-- | @POST \/api\/v1\/supplier-conditions@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createSupplierCondition
  :: (Consumes CreateSupplierCondition MimeJSON, MimeRender MimeJSON SupplierConditionCreate)
  => SupplierConditionCreate -- ^ "supplierConditionCreate"
  -> SimpleBillyRequest CreateSupplierCondition MimeJSON SupplierCondition MimeJSON
createSupplierCondition supplierConditionCreate =
  _mkRequest "POST" ["/api/v1/supplier-conditions"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` supplierConditionCreate

data CreateSupplierCondition 
instance HasBodyParam CreateSupplierCondition SupplierConditionCreate 

-- | @application/json@
instance Consumes CreateSupplierCondition MimeJSON

-- | @application/json@
instance Produces CreateSupplierCondition MimeJSON


-- *** deleteSupplierCondition

-- | @DELETE \/api\/v1\/supplier-conditions\/{supplier_condition_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteSupplierCondition
  :: SupplierConditionId -- ^ "supplierConditionId"
  -> SimpleBillyRequest DeleteSupplierCondition MimeNoContent NoContent MimeNoContent
deleteSupplierCondition (SupplierConditionId supplierConditionId) =
  _mkRequest "DELETE" ["/api/v1/supplier-conditions/",toPath supplierConditionId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteSupplierCondition  
instance Produces DeleteSupplierCondition MimeNoContent


-- *** getSupplierCondition

-- | @GET \/api\/v1\/supplier-conditions\/{supplier_condition_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getSupplierCondition
  :: SupplierConditionId -- ^ "supplierConditionId"
  -> SimpleBillyRequest GetSupplierCondition MimeNoContent SupplierCondition MimeJSON
getSupplierCondition (SupplierConditionId supplierConditionId) =
  _mkRequest "GET" ["/api/v1/supplier-conditions/",toPath supplierConditionId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetSupplierCondition  
-- | @application/json@
instance Produces GetSupplierCondition MimeJSON


-- *** listSupplierConditions

-- | @GET \/api\/v1\/supplier-conditions\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listSupplierConditions
  :: SimpleBillyRequest ListSupplierConditions MimeNoContent [SupplierCondition] MimeJSON
listSupplierConditions =
  _mkRequest "GET" ["/api/v1/supplier-conditions/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListSupplierConditions  
instance HasOptionalParam ListSupplierConditions Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam ListSupplierConditions PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam ListSupplierConditions SupplierContactId where
  applyOptionalParam req (SupplierContactId xs) =
    req `addQuery` toQuery ("supplier_contact_id", Just xs)
instance HasOptionalParam ListSupplierConditions Search where
  applyOptionalParam req (Search xs) =
    req `addQuery` toQuery ("search", Just xs)
-- | @application/json@
instance Produces ListSupplierConditions MimeJSON


-- *** updateSupplierCondition

-- | @PUT \/api\/v1\/supplier-conditions\/{supplier_condition_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateSupplierCondition
  :: (Consumes UpdateSupplierCondition MimeJSON, MimeRender MimeJSON SupplierConditionUpdate)
  => SupplierConditionUpdate -- ^ "supplierConditionUpdate"
  -> SupplierConditionId -- ^ "supplierConditionId"
  -> SimpleBillyRequest UpdateSupplierCondition MimeJSON SupplierCondition MimeJSON
updateSupplierCondition supplierConditionUpdate (SupplierConditionId supplierConditionId) =
  _mkRequest "PUT" ["/api/v1/supplier-conditions/",toPath supplierConditionId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` supplierConditionUpdate

data UpdateSupplierCondition 
instance HasBodyParam UpdateSupplierCondition SupplierConditionUpdate 

-- | @application/json@
instance Consumes UpdateSupplierCondition MimeJSON

-- | @application/json@
instance Produces UpdateSupplierCondition MimeJSON

