{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.Tax
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.Tax where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Tax

-- *** createTaxRate

-- | @POST \/api\/v1\/tax-rates@
-- 
-- Create a tax rate (`admin:settings`).
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createTaxRate
  :: (Consumes CreateTaxRate MimeJSON, MimeRender MimeJSON TaxRateCreate)
  => TaxRateCreate -- ^ "taxRateCreate"
  -> SimpleBillyRequest CreateTaxRate MimeJSON NoContent MimeNoContent
createTaxRate taxRateCreate =
  _mkRequest "POST" ["/api/v1/tax-rates"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` taxRateCreate

data CreateTaxRate 
instance HasBodyParam CreateTaxRate TaxRateCreate 

-- | @application/json@
instance Consumes CreateTaxRate MimeJSON

instance Produces CreateTaxRate MimeNoContent


-- *** deleteTaxRate

-- | @DELETE \/api\/v1\/tax-rates\/{id}@
-- 
-- Delete a tax rate by id (`admin:settings`).
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteTaxRate
  :: Id -- ^ "id"
  -> SimpleBillyRequest DeleteTaxRate MimeNoContent NoContent MimeNoContent
deleteTaxRate (Id id) =
  _mkRequest "DELETE" ["/api/v1/tax-rates/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteTaxRate  
instance Produces DeleteTaxRate MimeNoContent


-- *** listTaxRates

-- | @GET \/api\/v1\/tax-rates@
-- 
-- List the calling tenant's tax rates.
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listTaxRates
  :: SimpleBillyRequest ListTaxRates MimeNoContent NoContent MimeNoContent
listTaxRates =
  _mkRequest "GET" ["/api/v1/tax-rates"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListTaxRates  
instance Produces ListTaxRates MimeNoContent


-- *** updateTaxRate

-- | @PUT \/api\/v1\/tax-rates\/{id}@
-- 
-- Update a tax rate by id (`admin:settings`). Replaces all body fields.
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateTaxRate
  :: (Consumes UpdateTaxRate MimeJSON, MimeRender MimeJSON TaxRateCreate)
  => TaxRateCreate -- ^ "taxRateCreate"
  -> Id -- ^ "id"
  -> SimpleBillyRequest UpdateTaxRate MimeJSON NoContent MimeNoContent
updateTaxRate taxRateCreate (Id id) =
  _mkRequest "PUT" ["/api/v1/tax-rates/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` taxRateCreate

data UpdateTaxRate 
instance HasBodyParam UpdateTaxRate TaxRateCreate 

-- | @application/json@
instance Consumes UpdateTaxRate MimeJSON

instance Produces UpdateTaxRate MimeNoContent

