{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.TrainingAssignment
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.TrainingAssignment where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** TrainingAssignment

-- *** createTrainingAssignment

-- | @POST \/api\/v1\/training-assignments@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createTrainingAssignment
  :: (Consumes CreateTrainingAssignment MimeJSON, MimeRender MimeJSON TrainingAssignmentCreate)
  => TrainingAssignmentCreate -- ^ "trainingAssignmentCreate"
  -> SimpleBillyRequest CreateTrainingAssignment MimeJSON TrainingAssignment MimeJSON
createTrainingAssignment trainingAssignmentCreate =
  _mkRequest "POST" ["/api/v1/training-assignments"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` trainingAssignmentCreate

data CreateTrainingAssignment 
instance HasBodyParam CreateTrainingAssignment TrainingAssignmentCreate 

-- | @application/json@
instance Consumes CreateTrainingAssignment MimeJSON

-- | @application/json@
instance Produces CreateTrainingAssignment MimeJSON


-- *** deleteTrainingAssignment

-- | @DELETE \/api\/v1\/training-assignments\/{id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteTrainingAssignment
  :: Id -- ^ "id"
  -> SimpleBillyRequest DeleteTrainingAssignment MimeNoContent NoContent MimeNoContent
deleteTrainingAssignment (Id id) =
  _mkRequest "DELETE" ["/api/v1/training-assignments/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteTrainingAssignment  
instance Produces DeleteTrainingAssignment MimeNoContent


-- *** getTrainingAssignment

-- | @GET \/api\/v1\/training-assignments\/{id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getTrainingAssignment
  :: Id -- ^ "id"
  -> SimpleBillyRequest GetTrainingAssignment MimeNoContent TrainingAssignment MimeJSON
getTrainingAssignment (Id id) =
  _mkRequest "GET" ["/api/v1/training-assignments/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetTrainingAssignment  
-- | @application/json@
instance Produces GetTrainingAssignment MimeJSON


-- *** getTrainingAssignments

-- | @GET \/api\/v1\/training-assignments\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getTrainingAssignments
  :: SimpleBillyRequest GetTrainingAssignments MimeNoContent [TrainingAssignment] MimeJSON
getTrainingAssignments =
  _mkRequest "GET" ["/api/v1/training-assignments/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetTrainingAssignments  
instance HasOptionalParam GetTrainingAssignments Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam GetTrainingAssignments PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam GetTrainingAssignments Search where
  applyOptionalParam req (Search xs) =
    req `addQuery` toQuery ("search", Just xs)

-- | /Optional Param/ "include_deleted" - Soft-delete entities: set true to include rows with `deleted_at` set.
instance HasOptionalParam GetTrainingAssignments IncludeDeleted where
  applyOptionalParam req (IncludeDeleted xs) =
    req `addQuery` toQuery ("include_deleted", Just xs)
-- | @application/json@
instance Produces GetTrainingAssignments MimeJSON


-- *** updateTrainingAssignment

-- | @PUT \/api\/v1\/training-assignments\/{id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateTrainingAssignment
  :: (Consumes UpdateTrainingAssignment MimeJSON, MimeRender MimeJSON TrainingAssignmentUpdate)
  => TrainingAssignmentUpdate -- ^ "trainingAssignmentUpdate"
  -> Id -- ^ "id"
  -> SimpleBillyRequest UpdateTrainingAssignment MimeJSON TrainingAssignment MimeJSON
updateTrainingAssignment trainingAssignmentUpdate (Id id) =
  _mkRequest "PUT" ["/api/v1/training-assignments/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` trainingAssignmentUpdate

data UpdateTrainingAssignment 
instance HasBodyParam UpdateTrainingAssignment TrainingAssignmentUpdate 

-- | @application/json@
instance Consumes UpdateTrainingAssignment MimeJSON

-- | @application/json@
instance Produces UpdateTrainingAssignment MimeJSON

