{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.UserManagement
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.UserManagement where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** UserManagement

-- *** getUser

-- | @GET \/api\/v1\/users\/{user_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getUser
  :: UserId -- ^ "userId"
  -> SimpleBillyRequest GetUser MimeNoContent TenantUser MimeJSON
getUser (UserId userId) =
  _mkRequest "GET" ["/api/v1/users/",toPath userId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetUser  
-- | @application/json@
instance Produces GetUser MimeJSON


-- *** listUsers

-- | @GET \/api\/v1\/users@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listUsers
  :: SimpleBillyRequest ListUsers MimeNoContent [TenantUser] MimeJSON
listUsers =
  _mkRequest "GET" ["/api/v1/users"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListUsers  
-- | @application/json@
instance Produces ListUsers MimeJSON


-- *** removeUser

-- | @DELETE \/api\/v1\/users\/{user_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
removeUser
  :: UserId -- ^ "userId"
  -> SimpleBillyRequest RemoveUser MimeNoContent NoContent MimeNoContent
removeUser (UserId userId) =
  _mkRequest "DELETE" ["/api/v1/users/",toPath userId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data RemoveUser  
instance Produces RemoveUser MimeNoContent


-- *** updateUserPermissions

-- | @PUT \/api\/v1\/users\/{user_id}\/permissions@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateUserPermissions
  :: (Consumes UpdateUserPermissions MimeJSON, MimeRender MimeJSON UpdatePermissionsPayload)
  => UpdatePermissionsPayload -- ^ "updatePermissionsPayload"
  -> UserId -- ^ "userId"
  -> SimpleBillyRequest UpdateUserPermissions MimeJSON NoContent MimeNoContent
updateUserPermissions updatePermissionsPayload (UserId userId) =
  _mkRequest "PUT" ["/api/v1/users/",toPath userId,"/permissions"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` updatePermissionsPayload

data UpdateUserPermissions 
instance HasBodyParam UpdateUserPermissions UpdatePermissionsPayload 

-- | @application/json@
instance Consumes UpdateUserPermissions MimeJSON

instance Produces UpdateUserPermissions MimeNoContent


-- *** updateUserRole

-- | @PUT \/api\/v1\/users\/{user_id}\/role@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateUserRole
  :: (Consumes UpdateUserRole MimeJSON, MimeRender MimeJSON UpdateRolePayload)
  => UpdateRolePayload -- ^ "updateRolePayload"
  -> UserId -- ^ "userId"
  -> SimpleBillyRequest UpdateUserRole MimeJSON NoContent MimeNoContent
updateUserRole updateRolePayload (UserId userId) =
  _mkRequest "PUT" ["/api/v1/users/",toPath userId,"/role"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` updateRolePayload

data UpdateUserRole 
instance HasBodyParam UpdateUserRole UpdateRolePayload 

-- | @application/json@
instance Consumes UpdateUserRole MimeJSON

instance Produces UpdateUserRole MimeNoContent

