{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.User
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.User where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** User

-- *** changePassword

-- | @POST \/user\/change-password@
-- 
-- Change the current user's password (requires the current password).
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
changePassword
  :: (Consumes ChangePassword MimeJSON, MimeRender MimeJSON ChangePasswordRequest)
  => ChangePasswordRequest -- ^ "changePasswordRequest"
  -> SimpleBillyRequest ChangePassword MimeJSON NoContent MimeNoContent
changePassword changePasswordRequest =
  _mkRequest "POST" ["/user/change-password"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` changePasswordRequest

data ChangePassword 
instance HasBodyParam ChangePassword ChangePasswordRequest 

-- | @application/json@
instance Consumes ChangePassword MimeJSON

instance Produces ChangePassword MimeNoContent


-- *** createTeam

-- | @POST \/user\/teams@
-- 
-- Create a new team within the current tenant
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createTeam
  :: (Consumes CreateTeam MimeJSON, MimeRender MimeJSON TeamCreate)
  => TeamCreate -- ^ "teamCreate"
  -> SimpleBillyRequest CreateTeam MimeJSON ApiResponseTeam MimeJSON
createTeam teamCreate =
  _mkRequest "POST" ["/user/teams"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` teamCreate

data CreateTeam 
instance HasBodyParam CreateTeam TeamCreate 

-- | @application/json@
instance Consumes CreateTeam MimeJSON

-- | @application/json@
instance Produces CreateTeam MimeJSON


-- *** generateApiKey

-- | @POST \/user\/api-key@
-- 
-- Generate a new API key for the current user
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
generateApiKey
  :: SimpleBillyRequest GenerateApiKey MimeNoContent ApiResponseString MimeJSON
generateApiKey =
  _mkRequest "POST" ["/user/api-key"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GenerateApiKey  
-- | @application/json@
instance Produces GenerateApiKey MimeJSON


-- *** inviteUser

-- | @POST \/user\/invite@
-- 
-- Invite a user to the current tenant/organization
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
inviteUser
  :: (Consumes InviteUser MimeJSON, MimeRender MimeJSON InviteRequest)
  => InviteRequest -- ^ "inviteRequest"
  -> SimpleBillyRequest InviteUser MimeJSON NoContent MimeNoContent
inviteUser inviteRequest =
  _mkRequest "POST" ["/user/invite"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` inviteRequest

data InviteUser 
instance HasBodyParam InviteUser InviteRequest 

-- | @application/json@
instance Consumes InviteUser MimeJSON

instance Produces InviteUser MimeNoContent


-- *** listTeams

-- | @GET \/user\/teams@
-- 
-- List all teams in the current tenant
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listTeams
  :: SimpleBillyRequest ListTeams MimeNoContent ApiResponseVecTeam MimeJSON
listTeams =
  _mkRequest "GET" ["/user/teams"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListTeams  
-- | @application/json@
instance Produces ListTeams MimeJSON


-- *** removeUserFromOrg

-- | @DELETE \/user\/remove@
-- 
-- Remove a user from the current organization
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
removeUserFromOrg
  :: (Consumes RemoveUserFromOrg MimeJSON, MimeRender MimeJSON RemoveUserRequest)
  => RemoveUserRequest -- ^ "removeUserRequest"
  -> SimpleBillyRequest RemoveUserFromOrg MimeJSON NoContent MimeNoContent
removeUserFromOrg removeUserRequest =
  _mkRequest "DELETE" ["/user/remove"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` removeUserRequest

data RemoveUserFromOrg 
instance HasBodyParam RemoveUserFromOrg RemoveUserRequest 

-- | @application/json@
instance Consumes RemoveUserFromOrg MimeJSON

instance Produces RemoveUserFromOrg MimeNoContent


-- *** updateProfile

-- | @PUT \/user\/profile@
-- 
-- Update the current user's profile
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateProfile
  :: (Consumes UpdateProfile MimeJSON, MimeRender MimeJSON UpdateProfileRequest)
  => UpdateProfileRequest -- ^ "updateProfileRequest"
  -> SimpleBillyRequest UpdateProfile MimeJSON NoContent MimeNoContent
updateProfile updateProfileRequest =
  _mkRequest "PUT" ["/user/profile"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` updateProfileRequest

data UpdateProfile 
instance HasBodyParam UpdateProfile UpdateProfileRequest 

-- | @application/json@
instance Consumes UpdateProfile MimeJSON

instance Produces UpdateProfile MimeNoContent


-- *** userProfile0

-- | @GET \/user\/profile@
-- 
-- Get the current user's profile
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
userProfile0
  :: SimpleBillyRequest UserProfile0 MimeNoContent ApiResponseUserProfile MimeJSON
userProfile0 =
  _mkRequest "GET" ["/user/profile"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data UserProfile0  
-- | @application/json@
instance Produces UserProfile0 MimeJSON


-- *** userTenants

-- | @GET \/user\/tenants@
-- 
-- List all tenants (organizations) the current user belongs to
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
userTenants
  :: SimpleBillyRequest UserTenants MimeNoContent ApiResponseVecUserTenantInfo MimeJSON
userTenants =
  _mkRequest "GET" ["/user/tenants"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data UserTenants  
-- | @application/json@
instance Produces UserTenants MimeJSON

