{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.Voucher
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.Voucher where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Voucher

-- *** createVoucher

-- | @POST \/api\/v1\/vouchers@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createVoucher
  :: (Consumes CreateVoucher MimeJSON, MimeRender MimeJSON VoucherCreate)
  => VoucherCreate -- ^ "voucherCreate"
  -> SimpleBillyRequest CreateVoucher MimeJSON Voucher MimeJSON
createVoucher voucherCreate =
  _mkRequest "POST" ["/api/v1/vouchers"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` voucherCreate

data CreateVoucher 
instance HasBodyParam CreateVoucher VoucherCreate 

-- | @application/json@
instance Consumes CreateVoucher MimeJSON

-- | @application/json@
instance Produces CreateVoucher MimeJSON


-- *** deleteVoucher

-- | @DELETE \/api\/v1\/vouchers\/{voucher_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteVoucher
  :: VoucherId -- ^ "voucherId"
  -> SimpleBillyRequest DeleteVoucher MimeNoContent NoContent MimeNoContent
deleteVoucher (VoucherId voucherId) =
  _mkRequest "DELETE" ["/api/v1/vouchers/",toPath voucherId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteVoucher  
instance Produces DeleteVoucher MimeNoContent


-- *** getVoucher

-- | @GET \/api\/v1\/vouchers\/{voucher_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
getVoucher
  :: VoucherId -- ^ "voucherId"
  -> SimpleBillyRequest GetVoucher MimeNoContent Voucher MimeJSON
getVoucher (VoucherId voucherId) =
  _mkRequest "GET" ["/api/v1/vouchers/",toPath voucherId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GetVoucher  
-- | @application/json@
instance Produces GetVoucher MimeJSON


-- *** listVouchers

-- | @GET \/api\/v1\/vouchers\/@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listVouchers
  :: SimpleBillyRequest ListVouchers MimeNoContent [Voucher] MimeJSON
listVouchers =
  _mkRequest "GET" ["/api/v1/vouchers/"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListVouchers  
instance HasOptionalParam ListVouchers Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)
instance HasOptionalParam ListVouchers PageSize where
  applyOptionalParam req (PageSize xs) =
    req `addQuery` toQuery ("page_size", Just xs)
instance HasOptionalParam ListVouchers VoucherTypeText where
  applyOptionalParam req (VoucherTypeText xs) =
    req `addQuery` toQuery ("voucher_type", Just xs)
instance HasOptionalParam ListVouchers VoucherStatusText where
  applyOptionalParam req (VoucherStatusText xs) =
    req `addQuery` toQuery ("voucher_status", Just xs)
instance HasOptionalParam ListVouchers ContactName where
  applyOptionalParam req (ContactName xs) =
    req `addQuery` toQuery ("contact_name", Just xs)
instance HasOptionalParam ListVouchers DateFromDate where
  applyOptionalParam req (DateFromDate xs) =
    req `addQuery` toQuery ("date_from", Just xs)
instance HasOptionalParam ListVouchers DateToDate where
  applyOptionalParam req (DateToDate xs) =
    req `addQuery` toQuery ("date_to", Just xs)
-- | @application/json@
instance Produces ListVouchers MimeJSON


-- *** updateVoucher

-- | @PUT \/api\/v1\/vouchers\/{voucher_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateVoucher
  :: (Consumes UpdateVoucher MimeJSON, MimeRender MimeJSON Body)
  => Body -- ^ "body"
  -> VoucherId -- ^ "voucherId"
  -> SimpleBillyRequest UpdateVoucher MimeJSON Voucher MimeJSON
updateVoucher body (VoucherId voucherId) =
  _mkRequest "PUT" ["/api/v1/vouchers/",toPath voucherId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` body

data UpdateVoucher 
instance HasBodyParam UpdateVoucher Body 

-- | @application/json@
instance Consumes UpdateVoucher MimeJSON

-- | @application/json@
instance Produces UpdateVoucher MimeJSON


-- *** voucherRestore

-- | @POST \/api\/v1\/vouchers\/{voucher_id}\/restore@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
voucherRestore
  :: VoucherId -- ^ "voucherId"
  -> SimpleBillyRequest VoucherRestore MimeNoContent Voucher MimeJSON
voucherRestore (VoucherId voucherId) =
  _mkRequest "POST" ["/api/v1/vouchers/",toPath voucherId,"/restore"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data VoucherRestore  
-- | @application/json@
instance Produces VoucherRestore MimeJSON

