{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.WarehouseStock
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.WarehouseStock where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** WarehouseStock

-- *** createWarehouseStock

-- | @POST \/api\/v1\/warehouses\/{warehouse_id}\/stock@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createWarehouseStock
  :: (Consumes CreateWarehouseStock MimeJSON, MimeRender MimeJSON StockAdjustment)
  => StockAdjustment -- ^ "stockAdjustment"
  -> WarehouseId -- ^ "warehouseId"
  -> SimpleBillyRequest CreateWarehouseStock MimeJSON WarehouseStock MimeJSON
createWarehouseStock stockAdjustment (WarehouseId warehouseId) =
  _mkRequest "POST" ["/api/v1/warehouses/",toPath warehouseId,"/stock"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` stockAdjustment

data CreateWarehouseStock 
instance HasBodyParam CreateWarehouseStock StockAdjustment 

-- | @application/json@
instance Consumes CreateWarehouseStock MimeJSON

-- | @application/json@
instance Produces CreateWarehouseStock MimeJSON


-- *** deleteWarehouseStock

-- | @DELETE \/api\/v1\/warehouses\/{warehouse_id}\/stock\/{product_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteWarehouseStock
  :: WarehouseId -- ^ "warehouseId"
  -> ProductId -- ^ "productId"
  -> SimpleBillyRequest DeleteWarehouseStock MimeNoContent NoContent MimeNoContent
deleteWarehouseStock (WarehouseId warehouseId) (ProductId productId) =
  _mkRequest "DELETE" ["/api/v1/warehouses/",toPath warehouseId,"/stock/",toPath productId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteWarehouseStock  
instance Produces DeleteWarehouseStock MimeNoContent


-- *** listWarehouseStock

-- | @GET \/api\/v1\/warehouses\/{warehouse_id}\/stock@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listWarehouseStock
  :: WarehouseId -- ^ "warehouseId"
  -> SimpleBillyRequest ListWarehouseStock MimeNoContent [WarehouseStock] MimeJSON
listWarehouseStock (WarehouseId warehouseId) =
  _mkRequest "GET" ["/api/v1/warehouses/",toPath warehouseId,"/stock"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListWarehouseStock  
-- | @application/json@
instance Produces ListWarehouseStock MimeJSON


-- *** updateWarehouseStock

-- | @PUT \/api\/v1\/warehouses\/{warehouse_id}\/stock\/{product_id}@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateWarehouseStock
  :: (Consumes UpdateWarehouseStock MimeJSON, MimeRender MimeJSON StockAdjustment)
  => StockAdjustment -- ^ "stockAdjustment"
  -> WarehouseId -- ^ "warehouseId"
  -> ProductId -- ^ "productId"
  -> SimpleBillyRequest UpdateWarehouseStock MimeJSON WarehouseStock MimeJSON
updateWarehouseStock stockAdjustment (WarehouseId warehouseId) (ProductId productId) =
  _mkRequest "PUT" ["/api/v1/warehouses/",toPath warehouseId,"/stock/",toPath productId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` stockAdjustment

data UpdateWarehouseStock 
instance HasBodyParam UpdateWarehouseStock StockAdjustment 

-- | @application/json@
instance Consumes UpdateWarehouseStock MimeJSON

-- | @application/json@
instance Produces UpdateWarehouseStock MimeJSON

