{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.Webhooks
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.Webhooks where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Webhooks

-- *** createSubscription

-- | @POST \/api\/v1\/webhook-subscriptions@
-- 
-- Create a webhook subscription (outbound hook).
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
createSubscription
  :: (Consumes CreateSubscription MimeJSON, MimeRender MimeJSON CreateSubscriptionRequest)
  => CreateSubscriptionRequest -- ^ "createSubscriptionRequest"
  -> SimpleBillyRequest CreateSubscription MimeJSON WebhookSubscription MimeJSON
createSubscription createSubscriptionRequest =
  _mkRequest "POST" ["/api/v1/webhook-subscriptions"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` createSubscriptionRequest

data CreateSubscription 
instance HasBodyParam CreateSubscription CreateSubscriptionRequest 

-- | @application/json@
instance Consumes CreateSubscription MimeJSON

-- | @application/json@
instance Produces CreateSubscription MimeJSON


-- *** deleteSubscription

-- | @DELETE \/api\/v1\/webhook-subscriptions\/{subscription_id}@
-- 
-- Delete a webhook subscription.
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
deleteSubscription
  :: SubscriptionId -- ^ "subscriptionId"
  -> SimpleBillyRequest DeleteSubscription MimeNoContent NoContent MimeNoContent
deleteSubscription (SubscriptionId subscriptionId) =
  _mkRequest "DELETE" ["/api/v1/webhook-subscriptions/",toPath subscriptionId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data DeleteSubscription  
instance Produces DeleteSubscription MimeNoContent


-- *** emitApi

-- | @POST \/api\/v1\/webhooks\/emit@
-- 
-- Manually fire an event against matching hooks (for testing/flows).
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
emitApi
  :: (Consumes EmitApi MimeJSON, MimeRender MimeJSON EmitEventRequest)
  => EmitEventRequest -- ^ "emitEventRequest"
  -> SimpleBillyRequest EmitApi MimeJSON NoContent MimeNoContent
emitApi emitEventRequest =
  _mkRequest "POST" ["/api/v1/webhooks/emit"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` emitEventRequest

data EmitApi 
instance HasBodyParam EmitApi EmitEventRequest 

-- | @application/json@
instance Consumes EmitApi MimeJSON

instance Produces EmitApi MimeNoContent


-- *** listEvent

-- | @GET \/api\/v1\/webhook-events@
-- 
-- List webhook events (inbound + outbound log).
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listEvent
  :: SimpleBillyRequest ListEvent MimeNoContent [WebhookEvent] MimeJSON
listEvent =
  _mkRequest "GET" ["/api/v1/webhook-events"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListEvent  
-- | @application/json@
instance Produces ListEvent MimeJSON


-- *** listSubscriptions

-- | @GET \/api\/v1\/webhook-subscriptions@
-- 
-- List webhook subscriptions for the tenant.
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
listSubscriptions
  :: SimpleBillyRequest ListSubscriptions MimeNoContent [WebhookSubscription] MimeJSON
listSubscriptions =
  _mkRequest "GET" ["/api/v1/webhook-subscriptions"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data ListSubscriptions  
-- | @application/json@
instance Produces ListSubscriptions MimeJSON


-- *** updateSubscription

-- | @PUT \/api\/v1\/webhook-subscriptions\/{subscription_id}@
-- 
-- Update a webhook subscription.
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
updateSubscription
  :: (Consumes UpdateSubscription MimeJSON, MimeRender MimeJSON UpdateSubscriptionRequest)
  => UpdateSubscriptionRequest -- ^ "updateSubscriptionRequest"
  -> SubscriptionId -- ^ "subscriptionId"
  -> SimpleBillyRequest UpdateSubscription MimeJSON WebhookSubscription MimeJSON
updateSubscription updateSubscriptionRequest (SubscriptionId subscriptionId) =
  _mkRequest "PUT" ["/api/v1/webhook-subscriptions/",toPath subscriptionId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)
    `setBodyParam` updateSubscriptionRequest

data UpdateSubscription 
instance HasBodyParam UpdateSubscription UpdateSubscriptionRequest 

-- | @application/json@
instance Consumes UpdateSubscription MimeJSON

-- | @application/json@
instance Produces UpdateSubscription MimeJSON

