{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API.Zugferd
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SimpleBilly.API.Zugferd where

import SimpleBilly.Core
import SimpleBilly.MimeTypes
import SimpleBilly.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Zugferd

-- *** generateZugferdApi

-- | @GET \/api\/v1\/invoices\/{id}\/zugferd@
-- 
-- AuthMethod: 'AuthBasicBearerToken'
-- 
generateZugferdApi
  :: Id -- ^ "id"
  -> SimpleBillyRequest GenerateZugferdApi MimeNoContent NoContent MimeNoContent
generateZugferdApi (Id id) =
  _mkRequest "GET" ["/api/v1/invoices/",toPath id,"/zugferd"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicBearerToken)

data GenerateZugferdApi  
instance HasOptionalParam GenerateZugferdApi SupplierName where
  applyOptionalParam req (SupplierName xs) =
    req `addQuery` toQuery ("supplier_name", Just xs)
instance HasOptionalParam GenerateZugferdApi SupplierStreet where
  applyOptionalParam req (SupplierStreet xs) =
    req `addQuery` toQuery ("supplier_street", Just xs)
instance HasOptionalParam GenerateZugferdApi SupplierCity where
  applyOptionalParam req (SupplierCity xs) =
    req `addQuery` toQuery ("supplier_city", Just xs)
instance HasOptionalParam GenerateZugferdApi SupplierZip where
  applyOptionalParam req (SupplierZip xs) =
    req `addQuery` toQuery ("supplier_zip", Just xs)
instance HasOptionalParam GenerateZugferdApi SupplierCountry where
  applyOptionalParam req (SupplierCountry xs) =
    req `addQuery` toQuery ("supplier_country", Just xs)
instance HasOptionalParam GenerateZugferdApi SupplierVatId where
  applyOptionalParam req (SupplierVatId xs) =
    req `addQuery` toQuery ("supplier_vat_id", Just xs)
instance Produces GenerateZugferdApi MimeNoContent

