{-
   SimpleBilly API

   Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

   OpenAPI Version: 3.1.0
   SimpleBilly API API version: 0.1.0
   Contact: support@simplebilly.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SimpleBilly.API
-}

module SimpleBilly.API
  ( module SimpleBilly.API.Absence
  , module SimpleBilly.API.Activity
  , module SimpleBilly.API.Admin
  , module SimpleBilly.API.Ai
  , module SimpleBilly.API.AnlageEks
  , module SimpleBilly.API.AnlageG
  , module SimpleBilly.API.AnlageS
  , module SimpleBilly.API.Attachment
  , module SimpleBilly.API.AttachmentVersion
  , module SimpleBilly.API.Auth
  , module SimpleBilly.API.Automations
  , module SimpleBilly.API.Banking
  , module SimpleBilly.API.Billing
  , module SimpleBilly.API.Bom
  , module SimpleBilly.API.Bookkeeping
  , module SimpleBilly.API.Budgets
  , module SimpleBilly.API.ComplianceTraining
  , module SimpleBilly.API.Contact
  , module SimpleBilly.API.Coupon
  , module SimpleBilly.API.CreateSepaDirectDebit
  , module SimpleBilly.API.CreditNote
  , module SimpleBilly.API.Customer
  , module SimpleBilly.API.CustomerCommunication
  , module SimpleBilly.API.CustomerGroup
  , module SimpleBilly.API.Datev
  , module SimpleBilly.API.DatevImport
  , module SimpleBilly.API.Declaration
  , module SimpleBilly.API.DeliveryAppointment
  , module SimpleBilly.API.DeliveryDate
  , module SimpleBilly.API.DeliveryNote
  , module SimpleBilly.API.DownPaymentInvoice
  , module SimpleBilly.API.Ebilanz
  , module SimpleBilly.API.EmailTemplate
  , module SimpleBilly.API.Emissions
  , module SimpleBilly.API.Employee
  , module SimpleBilly.API.Euer
  , module SimpleBilly.API.EventSubscription
  , module SimpleBilly.API.Fristen
  , module SimpleBilly.API.Gdpr
  , module SimpleBilly.API.GenerateQrcode
  , module SimpleBilly.API.GenerateXrechnung
  , module SimpleBilly.API.Gewerbesteuer
  , module SimpleBilly.API.Gewinnverwendung
  , module SimpleBilly.API.Gez
  , module SimpleBilly.API.GobdExport
  , module SimpleBilly.API.GoodsReceipt
  , module SimpleBilly.API.GroupFigure
  , module SimpleBilly.API.ImportRunner
  , module SimpleBilly.API.Institute
  , module SimpleBilly.API.InstituteProfile
  , module SimpleBilly.API.InventoryCount
  , module SimpleBilly.API.InventoryValue
  , module SimpleBilly.API.Invoice
  , module SimpleBilly.API.JobApplication
  , module SimpleBilly.API.JobPosting
  , module SimpleBilly.API.Konzern
  , module SimpleBilly.API.KostenVorschau
  , module SimpleBilly.API.Kst
  , module SimpleBilly.API.KycRecord
  , module SimpleBilly.API.Lead
  , module SimpleBilly.API.LegalDocument
  , module SimpleBilly.API.ListOpenItems
  , module SimpleBilly.API.MarketplaceApi
  , module SimpleBilly.API.Notifications
  , module SimpleBilly.API.Offenlegung
  , module SimpleBilly.API.Onlineshop
  , module SimpleBilly.API.Order
  , module SimpleBilly.API.OrderConfirmation
  , module SimpleBilly.API.OssReport
  , module SimpleBilly.API.Packing
  , module SimpleBilly.API.Participation
  , module SimpleBilly.API.Paygap
  , module SimpleBilly.API.Payment
  , module SimpleBilly.API.PaymentCondition
  , module SimpleBilly.API.PaymentGateway
  , module SimpleBilly.API.Payroll
  , module SimpleBilly.API.Peppol
  , module SimpleBilly.API.Plausibility
  , module SimpleBilly.API.Pos
  , module SimpleBilly.API.PostingCategory
  , module SimpleBilly.API.PriceTier
  , module SimpleBilly.API.Product
  , module SimpleBilly.API.ProductAttribute
  , module SimpleBilly.API.ProductCategory
  , module SimpleBilly.API.ProductVariant
  , module SimpleBilly.API.ProductionOrder
  , module SimpleBilly.API.ProformaInvoice
  , module SimpleBilly.API.ProposeAssignments
  , module SimpleBilly.API.PublicReturns
  , module SimpleBilly.API.PurchaseOrder
  , module SimpleBilly.API.Quotation
  , module SimpleBilly.API.RecurringTemplate
  , module SimpleBilly.API.ReorderProposal
  , module SimpleBilly.API.Replenishment
  , module SimpleBilly.API.Reports
  , module SimpleBilly.API.ReturnOrder
  , module SimpleBilly.API.Rfq
  , module SimpleBilly.API.Search
  , module SimpleBilly.API.ServiceAssignment
  , module SimpleBilly.API.ServiceJob
  , module SimpleBilly.API.Shareholder
  , module SimpleBilly.API.Shipment
  , module SimpleBilly.API.Shipping
  , module SimpleBilly.API.ShippingRule
  , module SimpleBilly.API.ShippingThreshold
  , module SimpleBilly.API.Shop
  , module SimpleBilly.API.SilentPartner
  , module SimpleBilly.API.Stille
  , module SimpleBilly.API.StockMovement
  , module SimpleBilly.API.StockTransfer
  , module SimpleBilly.API.Suitability
  , module SimpleBilly.API.SupplierCondition
  , module SimpleBilly.API.SupplierInvoice
  , module SimpleBilly.API.SupportChannel
  , module SimpleBilly.API.SupportTicket
  , module SimpleBilly.API.Tax
  , module SimpleBilly.API.TenantSettings
  , module SimpleBilly.API.TicketMessage
  , module SimpleBilly.API.TimeEntries
  , module SimpleBilly.API.TrainingAssignment
  , module SimpleBilly.API.Trainings
  , module SimpleBilly.API.User
  , module SimpleBilly.API.UserManagement
  , module SimpleBilly.API.Ustva
  , module SimpleBilly.API.Voucher
  , module SimpleBilly.API.Warehouse
  , module SimpleBilly.API.WarehouseStock
  , module SimpleBilly.API.Webhooks
  , module SimpleBilly.API.Workflows
  , module SimpleBilly.API.Zugferd
  ) where

import SimpleBilly.API.Absence
import SimpleBilly.API.Activity
import SimpleBilly.API.Admin
import SimpleBilly.API.Ai
import SimpleBilly.API.AnlageEks
import SimpleBilly.API.AnlageG
import SimpleBilly.API.AnlageS
import SimpleBilly.API.Attachment
import SimpleBilly.API.AttachmentVersion
import SimpleBilly.API.Auth
import SimpleBilly.API.Automations
import SimpleBilly.API.Banking
import SimpleBilly.API.Billing
import SimpleBilly.API.Bom
import SimpleBilly.API.Bookkeeping
import SimpleBilly.API.Budgets
import SimpleBilly.API.ComplianceTraining
import SimpleBilly.API.Contact
import SimpleBilly.API.Coupon
import SimpleBilly.API.CreateSepaDirectDebit
import SimpleBilly.API.CreditNote
import SimpleBilly.API.Customer
import SimpleBilly.API.CustomerCommunication
import SimpleBilly.API.CustomerGroup
import SimpleBilly.API.Datev
import SimpleBilly.API.DatevImport
import SimpleBilly.API.Declaration
import SimpleBilly.API.DeliveryAppointment
import SimpleBilly.API.DeliveryDate
import SimpleBilly.API.DeliveryNote
import SimpleBilly.API.DownPaymentInvoice
import SimpleBilly.API.Ebilanz
import SimpleBilly.API.EmailTemplate
import SimpleBilly.API.Emissions
import SimpleBilly.API.Employee
import SimpleBilly.API.Euer
import SimpleBilly.API.EventSubscription
import SimpleBilly.API.Fristen
import SimpleBilly.API.Gdpr
import SimpleBilly.API.GenerateQrcode
import SimpleBilly.API.GenerateXrechnung
import SimpleBilly.API.Gewerbesteuer
import SimpleBilly.API.Gewinnverwendung
import SimpleBilly.API.Gez
import SimpleBilly.API.GobdExport
import SimpleBilly.API.GoodsReceipt
import SimpleBilly.API.GroupFigure
import SimpleBilly.API.ImportRunner
import SimpleBilly.API.Institute
import SimpleBilly.API.InstituteProfile
import SimpleBilly.API.InventoryCount
import SimpleBilly.API.InventoryValue
import SimpleBilly.API.Invoice
import SimpleBilly.API.JobApplication
import SimpleBilly.API.JobPosting
import SimpleBilly.API.Konzern
import SimpleBilly.API.KostenVorschau
import SimpleBilly.API.Kst
import SimpleBilly.API.KycRecord
import SimpleBilly.API.Lead
import SimpleBilly.API.LegalDocument
import SimpleBilly.API.ListOpenItems
import SimpleBilly.API.MarketplaceApi
import SimpleBilly.API.Notifications
import SimpleBilly.API.Offenlegung
import SimpleBilly.API.Onlineshop
import SimpleBilly.API.Order
import SimpleBilly.API.OrderConfirmation
import SimpleBilly.API.OssReport
import SimpleBilly.API.Packing
import SimpleBilly.API.Participation
import SimpleBilly.API.Paygap
import SimpleBilly.API.Payment
import SimpleBilly.API.PaymentCondition
import SimpleBilly.API.PaymentGateway
import SimpleBilly.API.Payroll
import SimpleBilly.API.Peppol
import SimpleBilly.API.Plausibility
import SimpleBilly.API.Pos
import SimpleBilly.API.PostingCategory
import SimpleBilly.API.PriceTier
import SimpleBilly.API.Product
import SimpleBilly.API.ProductAttribute
import SimpleBilly.API.ProductCategory
import SimpleBilly.API.ProductVariant
import SimpleBilly.API.ProductionOrder
import SimpleBilly.API.ProformaInvoice
import SimpleBilly.API.ProposeAssignments
import SimpleBilly.API.PublicReturns
import SimpleBilly.API.PurchaseOrder
import SimpleBilly.API.Quotation
import SimpleBilly.API.RecurringTemplate
import SimpleBilly.API.ReorderProposal
import SimpleBilly.API.Replenishment
import SimpleBilly.API.Reports
import SimpleBilly.API.ReturnOrder
import SimpleBilly.API.Rfq
import SimpleBilly.API.Search
import SimpleBilly.API.ServiceAssignment
import SimpleBilly.API.ServiceJob
import SimpleBilly.API.Shareholder
import SimpleBilly.API.Shipment
import SimpleBilly.API.Shipping
import SimpleBilly.API.ShippingRule
import SimpleBilly.API.ShippingThreshold
import SimpleBilly.API.Shop
import SimpleBilly.API.SilentPartner
import SimpleBilly.API.Stille
import SimpleBilly.API.StockMovement
import SimpleBilly.API.StockTransfer
import SimpleBilly.API.Suitability
import SimpleBilly.API.SupplierCondition
import SimpleBilly.API.SupplierInvoice
import SimpleBilly.API.SupportChannel
import SimpleBilly.API.SupportTicket
import SimpleBilly.API.Tax
import SimpleBilly.API.TenantSettings
import SimpleBilly.API.TicketMessage
import SimpleBilly.API.TimeEntries
import SimpleBilly.API.TrainingAssignment
import SimpleBilly.API.Trainings
import SimpleBilly.API.User
import SimpleBilly.API.UserManagement
import SimpleBilly.API.Ustva
import SimpleBilly.API.Voucher
import SimpleBilly.API.Warehouse
import SimpleBilly.API.WarehouseStock
import SimpleBilly.API.Webhooks
import SimpleBilly.API.Workflows
import SimpleBilly.API.Zugferd